### ISSUE TITLE
QueryObject as DataSource

### ISSUE THREAD

**Issue by Achse** [ublaboo/datagrid#100]
Currently, doctrine is supported via `\Kdyby\Doctrine\QueryBuilder` -> `Ublaboo\DataGrid\DataSource\DoctrineDataSource`

Using `QueryObject` would provide:
1. better paging thanks to: `doCreateCountQuery`,
2. `postFetch`.

Ad 1. - There is a problem with totalCount calculation and if you want to optimaze your query to avoid aditional selects you have to hack it like:
```php
$this->extraordinaryExpensesRepository->createQueryBuilder('e')
	->innerJoin('e.www', 'w')->addSelect('w')
	->innerJoin('w.ccc', 'c')->addSelect('c')
	->innerJoin('e.ttt', 't')->addSelect('t')
	->leftJoin('e.confirmations', 'conf')->addSelect('conf')
	->getQuery()->getResult();

return $this->extraordinaryExpensesRepository->createQueryBuilder('e');
```

**Comment by paveljanda** [comment]
How much would be "DoctrineQueryObjectDataSource" different implementing from "DoctrineQueryBuilderDataSource"? A do not have any practical experience with Doctrine.

Either you can send a PR, where Doctrine data source will be split into these two data sources (version 2 is on its way anyway) or i will look deep in doctrine a couple days/weeks later i will introduce these split datasources. :)

**Comment by juniwalk** [comment]
QueryObject is just wrapper around QueryBuilder,
I don't see how this is useful. You would have to add methods to add filtering to the QueryObject, you would be basically re-implementing QueryBuilder.

By me, this is :-1:

**Comment by JakubKontra** [comment]
I agree with @juniwalk. 
By me, this is :-1:

**Comment by paveljanda** [comment]
Closing this, I agree with @JakubKontra and @juniwalk .

**Comment by Achse** [comment]
You was little bit rash here. Due to weekend I hadn't time to respond.

`QueryObject` is indeed wrapper around `QueryBuilder`. But beside it it a very good pattern of separation queris from "repositories" it also provides `doCountQuery` and `postFetch` functionality whitch AFAIK you cannot easily achieve with just QueryBuilder.

Here I would talk mainly about the first one.

When you need in `DoctrineDataSource` count of rows for creating pagination you do:
```php
$paginator = new Doctrine\ORM\Tools\Pagination\Paginator($this->getQuery());
$count = count($paginator);
```

This lead to `Paginator::getCountQuery`. It clone query a transform it to `COUNT`-Query. Example here:
```sql
SELECT COUNT(*) AS dctrn_count 
FROM (
SELECT DISTINCT id_2 
FROM (
SELECT ... thousands of selects ...
FROM tabel_a d0_ 
INNER JOIN tabel_b d1_ ON d0_.b_id = d1_.id 
INNER JOIN tabel_c c2_ ON d1_.c_id = c2_.id AND (c2_.brand_id = '1') 
INNER JOIN tabel_d d3_ ON d0_.type = d3_.id 
LEFT JOIN tabel_e d4_ ON d0_.id = d4_.e_id 
WHERE d0_.type IN ('extraordinaryExpense')) dctrn_result) dctrn_table
```

This could also lead to invalid count and you need to hack it as I described in my frost post.

As @juniwalk mentioned, you cannot easily use filtering upon QueryObject because its Query is encapsulated into object itself and QueryObject has no public API to extend it. 

Have any idea how to be able to write your own COUNT queries? Naive solution is to create another DataSourceObject that can take two QueryBuilders but I dont like this. We would probably have to solve this in our project soon becaouse we would need `preFetch` functionality also. I would also share that solutione here.  **If you have any other ideas, how to elegantly do that I'll be glad for 'em.**

**Comment by juniwalk** [comment]
@Achse Best way I see is to write custom DataSource if you need such high level modifications to count query OR maybe add callback option to current DoctrineDataSource to modify count query logic.
