### ISSUE TITLE
Possibility to download javascript and css files by Bower

### ISSUE THREAD

**Issue by radekhubner** [ublaboo/datagrid#102]
Can yoo add possibility to download javascript and css files by [Bower](http://bower.io/)?

**Comment by JakubKontra** [comment]
+1

**Comment by paveljanda** [comment]
It is in master. After releasing v2, package will be available through `bower install ublaboo-datagrid` without specifying target commit.

**Comment by romanmatyus** [comment]
Bower archive not contain bower.json file. It's possible add them?

**Comment by paveljanda** [comment]
Okey.

**Comment by paveljanda** [comment]
It does.. Or what do you mean by archive? When I run command `bower install ublaboo-datagrid`, bower.json file is located in `/bower_components/ublaboo-datagrid/bower.json`

**Comment by romanmatyus** [comment]
No only `.bower.json`?

![image](https://cloud.githubusercontent.com/assets/1110294/13494513/05efc1f4-e145-11e5-86c6-c99a6c95c47c.png)

**Comment by paveljanda** [comment]
I don't know, what `.bower.json` is. Bower probably generates that file itself.

**Comment by romanmatyus** [comment]
Yes, `.bower.json` generates Bower. You realy has `bower.json` in directory?

**Comment by paveljanda** [comment]
<img width="914" alt="screen shot 2016-03-03 at 16 05 12" src="https://cloud.githubusercontent.com/assets/1488874/13498378/f87f0006-e159-11e5-8292-3e2fcf8ac747.png">

**Comment by romanmatyus** [comment]
Thanks, I had installed old version.

**Comment by paveljanda** [comment]
:+1:
