### ISSUE TITLE
JS error with datagrid.min.js and datagrid.js

### ISSUE THREAD

**Issue by zemnet** [ublaboo/datagrid#107]
Hi, your datagrid is nice work.

If I make filtering input, and the ajax request was ended, I have js error on console in datagrid.min.js file:

`TypeError: window.happy is undefined
...on(){var t,e,a,d,r,i,n,o,l,s,u,c,g;for(window.happy.reset(),n=$(".datagrid"),g=[...` 

![datagrid-window happy-error](https://cloud.githubusercontent.com/assets/17403818/13214427/cd058a92-d94f-11e5-8010-74bfa60de956.JPG)

PS: sorry for my english...

**Comment by paveljanda** [comment]
Thanks, i will look at it

**Comment by paveljanda** [comment]
For proper functionality you should also include happy.min.js or happy.js in your project (it is mentioned in documentation on the first site). Or use standalone.min.js, where are more scripts compiled together (jquery-ui.sortable.js, bootstrap-datepicker.js, happy.js and datagrid.js).

**Comment by juniwalk** [comment]
@paveljanda It would be great if you add link to the happy repository in the datagrid docs :)

**Comment by paveljanda** [comment]
I will more probably add happy.js directly to the datarid.js file. It is just a few lines of code and datagrid relies on it.

**Comment by JakubKontra** [comment]
I think the best solution will be -  bower package with dependencies.

**Comment by juniwalk** [comment]
I think those checkboxes should be optional, someone could use different one.

**Comment by zemnet** [comment]
Yes, this would be fine, because I have included happy.js downloaded from web...and error is still.

**Comment by paveljanda** [comment]
@zemnet That is weird. Try to include the happy.js script before datagrid.js. Anyway, in master are the happy components optional (`DataGrid->useHappyComponents(FALSE)`).

**Comment by zemnet** [comment]
Yes, order is right...ok, thank you
`


<script src="{$basePath}/js/standalone.min.js"></script>
`

**Comment by zemnet** [comment]
But if I have included standalone.min.js, filtering of hidden columns was not remembered.
On datagrid.min.js filtering work correctly.

**Comment by zemnet** [comment]
But if I have included standalone.min.js, filtering of hidden columns was not remembered. On datagrid.min.js work correctly.
PS: sorry for spaming, I am new in github :)

**Comment by paveljanda** [comment]
Standalone.min.js and standalone.js is no longer distributed within ublaboo/datagrid package.

Try to look at updated documentation: http://ublaboo.paveljanda.com/datagrid/#assets.

**Comment by zemnet** [comment]
Thank you.
