### ISSUE TITLE
Sorting not work with Nette\Database\Table datasource

### ISSUE THREAD

**Issue by zemnet** [ublaboo/datagrid#108]
Hi,
I am using Nette\Database\Table datasource and sorting is not working.

Request is sended by ajax and succeeded correctly back, 
but data, what is loaded over json, is not sorted correctly.

Thank you for your help.

**Comment by paveljanda** [comment]
Here is working NDBT sorting: http://ublaboo.paveljanda.com/datagrid/export.

Can you show me please your code where you are creating NDBT selection?

**Comment by zemnet** [comment]
this?

`$grid->setDataSource($this->obec->getGridData());`

obec->getGridData() is model with return of table:

`public function getGridData() {
      return $this->database->table($this->tableName);
  }`

**Comment by zemnet** [comment]
default sort not work too: `$grid->setDefaultSort(['obec' => 'DESC']);`

**Comment by paveljanda** [comment]
Can you please show me whole code of your datagrid factory? I can not reproduce this error.

**Comment by zemnet** [comment]
Main Factory:
`namespace App\Grids;

use Nette,
    Ublaboo\DataGrid\DataGrid;

class GridFactory extends Nette\Object
{

	/**
	 * @return Grid
	 */
	public function create($presenter,$name)
	{
		$grid = new DataGrid($presenter, $name);
    $grid->setColumnsHideable();
    $grid->setPagination(FALSE);
    return $grid;
	}

}`

Factory for Adresar

`namespace App\Grids;

use Nette,
    App\Model;
    
class AdresarGridFactory extends Nette\Object
{   
    /** @var GridFactory */
    private $gridfactory;
    
    /** @var Model\Obec */
    private $obec;
    
    /** @var Model\Adresar */
    private $adresar;
   
    public function __construct(GridFactory $gridfactory, \Nette\Database\Context $database)
	  {
		    $this->gridfactory = $gridfactory;
        $this->obec = new Model\Obec($database);
        $this->adresar = new Model\Adresar($database);
	  }
    
    public function create($presenter,$name)
    {
	    $grid = $this->gridfactory->create($presenter,$name);
      
      $grid->setDataSource($this->adresar->getGridData());

      $typ = ['' => 'Všetky', 'O' => 'Osoby', 'F' => 'Firmy'];

      $grid->addColumnText('typ', 'Typ')
          ->setReplacement($typ);
	    
      $grid->addColumnText('priezvisko', 'Priezvisko, meno')
        ->setRenderer(function($item) {
      		return $item->priezvisko.', '.$item->meno;
      	})
        ->sortable();
              
      $grid->addColumnText('firma', 'Firma')
        ->sortable();
        
      $grid->addColumnText('obec_id', 'Obec')
          ->setReplacement($this->obec->getSelectData())
          ->sortable();
                
      $grid->addColumnText('email1', 'Kontakt')
        ->setRenderer(function($item) {
	        return $item->tel1.", <a href='mailto:".$item->email1."'>".$item->email1."</a>";
         })
        ->setTemplateEscaping(FALSE);

      $grid->addColumnText('deleted', 'Stav')
        ->setReplacement([0 => 'Aktívne', 1 => 'Neaktívne']);
              
      $grid->addFilterSelect('deleted', 'Stav', [
      		'' => 'Všetky',
          0 => 'Aktívne',
      		1 => 'Neaktívne'
      	]);

      $grid->addFilterText('priezvisko', 'Vyhľadávanie', ['priezvisko','meno']);
      $grid->addFilterText('firma', 'Firma', 'firma');
      $grid->addFilterText('email1', 'Kontakt:', ['email1', 'tel1']);
      $grid->addFilterSelect('typ', 'Typ:', $typ);
      
      $grid->addAction('edit','')
    		  ->title('Upraviť')
          ->setIcon('pencil')
    		  ->class('btn btn-xs btn-warning');
          
      $grid->addAction('delete','')
    		  ->title('Zamazať')
          ->setIcon('trash')
    		  ->class('btn btn-xs btn-danger')
          ->confirm('Naozaj vymazať položku?');  	    
    }
}`

**Comment by paveljanda** [comment]
Wasn't that due to your previous issue, where the scripts were not working correctly? Try it following this scripts structure: http://ublaboo.paveljanda.com/datagrid/#assets

**Comment by zemnet** [comment]
Today I am include your scripts over fresh install of bower from actual manual, and grid shorting not work. Cache cleared.

PS: U have mismatch in inlude manual. You link css as script and script as css :)
PS2: on include is missing script bootstrap.min.js

**Comment by paveljanda** [comment]
Thanks, I will fix that.

bootstrap.min.js should not required. Where did you find usage of bootstrap.js?

**Comment by zemnet** [comment]
If it was not included, dropdown menu in hide column and other not work for me.

**Comment by zemnet** [comment]
And I dont know why, but after includes from your manual, filtering is not rendered over ajax.

**Comment by paveljanda** [comment]
Did you write this in some of your scripts?

```html
<script>
	$.nette.init();
</script>
```

It is required when using some nette scripts (netteForms.js or nette.ajax.js). I will add that to the documentation.

**Comment by zemnet** [comment]
oh, sorry, filtering over no ajax request is, because I remove my included JS script, where I have nette init. sorry, I am new in Nette :)

**Comment by zemnet** [comment]
But data sorting is not working, 
I think, data is sorted in DataSource, right?
Because response data from server in payload is not sorted.
I will create new temp project for testing is this in clear install.
Thank you...

**Comment by paveljanda** [comment]
Did you create that temp project? You can upload it on github and i will look at it. Or you can paste it here as zip. It would be great to have a sql dump within the zip or repo.

**Comment by paveljanda** [comment]
@zemnet Is all clear to you by now? Or do you have still some problems?

**Comment by zemnet** [comment]
Sorry, I has no time up to now, now I am work on test, 30 mins and I will have report...

**Comment by zemnet** [comment]
in clear sandbox instalation with your component all work fine :( 
but after that I dont know, where is the problem on other project.
For now I will compare versions of components...
thank you for your interest.

**Comment by zemnet** [comment]
@paveljanda 
I find where is the problem.
If I have disabled pagination $grid->setPagination(FALSE),
ordering not work....with enabled pagination all work well.

**Comment by paveljanda** [comment]
You're right, i will take a look at it.

**Comment by zemnet** [comment]
And If I have enabled pagination, and I am set to view all lines in grid, ordering not work too....

**Comment by paveljanda** [comment]
@zemnet Thank a lot! I have fixed that behaviour in version 2.2.3.

**Comment by zemnet** [comment]
thank you :) good luck
