### ISSUE TITLE
Column: Link column throws an error

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#112]
I don't know if this is on my end or not but I get error from this column:
```php
$grid->addColumnLink('user', 'client.stock.user', ':Admin:User:edit', 'user.name', ['id' => 'user.id']);
```
The error is as follows: `Component or subcomponent name must not be empty string.`

It looks like the Link column is trying to transform given href argument to component name.

**Comment by paveljanda** [comment]
Is there any chance to get some chunk of your databse schema dump? Or just a schema itself. It would help reproduce this behaviour.

**Comment by juniwalk** [comment]
It is little messy I am in the process of restructuring it. By the way I use Doctrine.

[schema.zip](https://github.com/ublaboo/datagrid/files/144359/schema.zip)

**Comment by paveljanda** [comment]
First i tried it on my simple schema with OneToMany relation. I had almost same column definition as you have and there was no problem:

```php
$grid->setDataSource(
	$exampleRowRepository->createQueryBuilder('a')
		->addSelect('b')
		->leftJoin('er.info', 'b')
);

$grid->addColumnLink('info_age', 'bla.blu.ble', 'Datagrid:edit', 'info.age', ['id' => 'info.id']);
```

**Comment by juniwalk** [comment]
I see I will walk trough my code once again and get back to you then.

**Comment by juniwalk** [comment]
I don't get it, problem lies in ':Admin:User:edit', nette is trying to look for component instead of presenter and I have no idea why. When I enter 'delete' (signal in current component) then all works correctly.

**Comment by juniwalk** [comment]
```php
try {
	$parent = $this->grid->getParent();
} catch (DataGridHasToBeAttachedToPresenterComponentException $e) {
	$parent = $this->grid->getPresenter();
}
```
You added this a while ago and this is what is causing the problems, I gave datagrid in component and that component in the presenter, that is why it does not work, it does not generate the link on presenter.

**Comment by paveljanda** [comment]
Maybe i know where is the problem..

You added the try-catch block and it probably does not know the proper exception class.

**Comment by paveljanda** [comment]
Aah.

**Comment by paveljanda** [comment]
I see. I will add another catch statement. :)

**Comment by juniwalk** [comment]
I will switch to dev-master to test it out

**Comment by paveljanda** [comment]
Can you please test in? It is possible BC break, so i will write some more features and release v3. :D

**Comment by juniwalk** [comment]
Sorry I was having launch. Well it does work, I am checking the code, to be honest, I have no idea why are you doing this way, could you fill me in?

I would check if the href leads to signal and use $this->link and if not, I would use presenter.

**Comment by paveljanda** [comment]
Flow of getting link to specified destination:
1, Try to create link directly to component (or something) that created DataGrid
2, If that parent is not `PresenterComponent` (`ISignalReceiver`), try to find Presenter and call `::link()` on that presenter
3, If parent component could not create link (link is i.e. `Users:edit`), find component presenter and call `::link()` on that presenter

**Comment by juniwalk** [comment]
So you expose internal signals to this link column?

**Comment by paveljanda** [comment]
Those signals would be exposed anyway, don't they? Or how do you mean exposing signal? If you write in presenter something like this: `$this->link('grid-foo!')`, it would be also link to internal signal receiver..

**Comment by juniwalk** [comment]
Sure, but why would you expose them explicitly in the Link column? What if someone has signal in presenter that has the same name as signal in your grid? Which one will you pick?

If someone wants to link to grids signal, he should do so by explicitly mentioning the grid, you should not guess where he wants to link.

The most use cases for this column will be signal in parent component / presenter or link to presenter action, that should be the priority.

**Comment by paveljanda** [comment]
Wait, there was a misunderstanding:

Neither `Action` or `ColumnLink` can not explicitly create link to class `Ublaboo\DataGrid`.

Let's discuss an example.
1, I have a `UsersPresenter` and this presenter is creating component called `GridControl`.
2, `GridControl` can create component `usersGrid`.

Now, I you make link: `$grid->addAction('delete', '', 'page!')`, `Ublaboo\DataGrid` will:
1, Try to call `GridControl::link('page!')` - that won't succeed
2, Try to find `$parent` - some parent class of type `PresenterComponent` - in that case `UsersPresenter`
2, Try to call `$parent::link('page!')` - that also won't succeed

**Comment by juniwalk** [comment]
I see, that is alright then, thanks for filling me up. The code works, we can close this. :)

**Comment by paveljanda** [comment]
Is it or not a BC break?

Maybe not. Maybe the only behaviour changed is that datagrid can create links from subcomponent to component parent presenter.

I will test it and release either v2.1.2 or v3.0.0. :D

**Comment by juniwalk** [comment]
I did not have to change anything, it just started working again! :)
