### ISSUE TITLE
Remove / deprecate ->icon, ->class feature

### ISSUE THREAD

**Issue by Achse** [ublaboo/datagrid#113]
> **Disclaimer**: I understant I open theme that can be controversal.

I suggest:
* Deprecate this feature,
* and remove it from doc, replace it with proper method calls (`setIcon`, `setClass`, `addXyz`)

------

Motivation:
* It's magic (which causes everything I mention below),
* does not provide typehint in IDEs,
* cannot be checked by static syntax analyzers (code-sniffers),
* leads to mistakes and typos.

------

> Well, just don't use it? Its not mandatory to do it like this.

* Magic is not good for new users, makes bad habits.
* Copy & paste from docs is harder (IDE yaps about it, refactoring is needed).

**Comment by paveljanda** [comment]
I agree.

What do you suggest me to do with existing projects? I do not want to release v3 two days after v2 because of just one BC break.

Options:
1, Create methods `::class()`, `::icon`, etc and throw @deprecated exception within them
2, Right, release v3

Any other idea?

**Comment by Achse** [comment]
I suggest:
* remove it from documentation and replace it with non-magic method there. This will fix most of problems. Nobody know, nobody uses. :)
* add it to v3 release, which can be releases anytime in the future (with some other BC breaks and feature, etc...)

**Comment by paveljanda** [comment]
Right.
