### ISSUE TITLE
Problem with sorting

### ISSUE THREAD

**Issue by vastlik** [ublaboo/datagrid#119]
` $grid->addColumnNumber('value', 'Value')
            ->setSortable()
            ->setAlign('left');`
when using this, the arrows next to name doesn't show. On the other side, when using 
`$grid->addColumnNumber('id', 'Value')
            ->setSortable()
            ->setAlign('left');`
arrows for sorting appear.
It seems, when name of row contains word value, then arrows doesn't show.

**Comment by paveljanda** [comment]
@vastlik 

I am sure it is not as you described "when name of row contains word value, then arrows doesn't show".

Also when i tested your code, both examples worked well. Isn't there some css that might hide the link? Please try to look inside you html code and tell me whether it's hidden or really not there.

**Comment by vastlik** [comment]
As you can see, when refreshed page, it shows class fa-up instead fa-sorted. When i change class name to fa-sorted, it works as indeed. 
[css](http://s15.postimg.org/5gdboltor/issue.png)
I checked my css and nothing  changes the class name.

**Comment by paveljanda** [comment]
DataGrid remembers the "sort" in session. Try deleting session and refreshing url.

I can not reproduce that behaviour. I created column with name "value" and added exactly same code as you wrote above. And it works well..

Can you please create an example sandbox wth possible sqlite database and behaviour of yours and upload it here in zip?

**Comment by vastlik** [comment]
Deleting session resolved this issue. Thanks for help.
