### ISSUE TITLE
Datetimepicker

### ISSUE THREAD

**Issue by harmim** [ublaboo/datagrid#121]
It would be useful create datetimepicker in date and dateRange filter.

There are two options:

1. Create `FilterDateTime` and `FilterDateTimeRange` components
2. Somehow it merge and turns on datetimepicker based on date format

- [ ] Anyway it´s required find appropriate javascript datetimepicker package

**Comment by paveljanda** [comment]
Option 1 is ok. But the js library would have to be changed for both date and time picking. Do you know any?

**Comment by harmim** [comment]
This does not look bad http://www.malot.fr/bootstrap-datetimepicker/demo.php

**Comment by paveljanda** [comment]
Sorry, i decided not to implement this. The reasons are:
1) It is not so hard to implement something like this by user using custom ColumnText template
2) I would not use it
3) I didn't really met anyone else who would also want to us it
4, I do not like the JS libraries for date & **time** picking

Again, sorry.
