### ISSUE TITLE
Take out dictionary to neon file

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#124]
If be translates in separate files, users can send PR with native translates to other languages.
SimpleTranslator let only used `ublaboo_datagrid.en_US.neon`, but If someone thinks seriously translations, only add dictionaries and exchange ITranslator.

**Comment by paveljanda** [comment]
The thing is, i do not really want to provide translations already within this repo. Each programmer/client can have different ideas about particular translation.

**Comment by romanmatyus** [comment]
Now, I need extract translation strings from `SimpleTranslator` and duplicate all strings.
If there were file `ublaboo_datagrid.en_US.neon`, I use it and rewrite only some strings.
