### ISSUE TITLE
DataGrid can not take [Doctrine\ORM\QueryBuilder] as data source?

### ISSUE THREAD

**Issue by bazo** [ublaboo/datagrid#127]
i don't know if i am stupid or what, but the docs clearly state i can use doctrine query builder as data source. so i did that, but i get this exception

Ublaboo\DataGrid\Exception\DataGridWrongDataSourceException
DataGrid can not take [Doctrine\ORM\QueryBuilder] as data source

the code
````
$grid = new DataGrid;
$source = $this->blogManager->getPostsSource(); //source is a QueryBuilder
$grid->setDataSource($source);
````

basically the same code as on your examples page.

wtf is going on?

**Comment by bazo** [comment]
now i see it needs Kdyby\Doctrine\QueryBuilder

this is real WTF

why??

not everybody uses kdyby doctrine

**Comment by paveljanda** [comment]
No, that's not your fault.

Kdyby\Doctrine\QueryBuilder vs Doctrine\ORM\QueryBuilder. I have a check on the first class although it is not really needed.

I will change that.

**Comment by fprochazka** [comment]
Never depend on specific implementation, unless you really must :)

**Comment by paveljanda** [comment]
That was not intended.

@bazo `composer update`

**Comment by bazo** [comment]
great! thanks
