### ISSUE TITLE
CSV export ignores column template

### ISSUE THREAD

**Issue by RadekDvorak** [ublaboo/datagrid#128]
The `CsvDataModel::getRow` ignores column templates.

**Comment by paveljanda** [comment]
Yes that is true.

Column templates are used only for rendering into html. If you would like to modify data output, you can use custom renderer (Column::setRenderer()).

Or you can export data with totally different columns that are not used for html output.

I could probably change this bahaviour, but:
1, Latte is templating engine fo HTML
2, Idea of using this engine for exporting data into CSV format sounds wrong bad to me.

**Comment by RadekDvorak** [comment]
Well, coul you add a notice into the documentation?

**Comment by paveljanda** [comment]
Right, I will fix that.
