### ISSUE TITLE
Make happy buttons optional

### ISSUE THREAD

**Issue by AntikCz** [ublaboo/datagrid#130]
If I have not loaded happy.js console prints error "Uncaught TypeError: Cannot read property 'reset' of undefined"

Solution:
```js
if (window.happy) {
    $.nette.ext(); // ...
}
```

or:
```js
$.nette.ext('...', {
    success: function () {
        if (!window.happy) { return; }
        // ...
    }
});
```

https://github.com/ublaboo/datagrid/blob/master/assets/dist/datagrid.js#L203

**Comment by paveljanda** [comment]
v2.3.4
