### ISSUE TITLE
custom js datagridSortableTree function

### ISSUE THREAD

**Issue by vaclavpavek** [ublaboo/datagrid#133]
You can edit the file datagrid.js like the one below? I do not know how I can do it minified js :-(

```js
if(typeof datagridSortableTree === 'undefined') {
  var datagridSortableTree;

  datagridSortableTree = function () {
    ....
  };
};

datagridSortableTree()
```

**Comment by paveljanda** [comment]
Can please send a PR? It is the file datagrid.coffee. Once you send a PR, i will make a build of compiled + minified version.
