### ISSUE TITLE
Hiding / showing columns

### ISSUE THREAD

**Issue by jelen07** [ublaboo/datagrid#135]
It would be nice if the **show all columns** feature will be replaced with list of available columns where you can directly select required columns.
Anyway when you adding column to the grid, it will be also so cool if you can call something like
```php
$grid->addColumnText('name', 'Name')->setHidden();
```
which is default *visibility* option (column can be added from the grid).
Some "restart columns visibility" function should be available.

<img width="225" alt="Preview" src="https://cloud.githubusercontent.com/assets/2346295/13663600/bc3bd864-e6a2-11e5-901b-26e12cd3f630.png">

:+1:

**Comment by paveljanda** [comment]
I implemented the list of hidden columns (i will wrote about it more on we when v3.0 is ready).

Sorry, but i decided not to implement the `Column::setHidden` and "restart column visibility" functionality. I had some ideas, but i didn't like the implementation. If you have any great idea ho to do it some clear way, please send a PR. :)

**Comment by jelen07** [comment]
OK. No problem with that, just the PR will be :)
I would like to redesign templates for twbs4 this way.

![dagrid](https://cloud.githubusercontent.com/assets/2346295/13879321/287e7cd2-ed17-11e5-9805-5b64dc38f690.gif)

Column::setHidden will be feature, not required function, so it is not necessary now.

**Comment by paveljanda** [comment]
That is an interesting preview.

It is also a great idea to include more themes within ublaboo/datagrid repo. Where did you inspire with that one? :)

**Comment by jelen07** [comment]
Yeah :+1:  
You can find this and more on [dribbble](https://dribbble.com/shots/1903644-Data-Grid).
