### ISSUE TITLE
Custom condition on sorting columns

### ISSUE THREAD

**Issue by harmim** [ublaboo/datagrid#137]
Addition option set custom condition when you setting sortable each column (`Ublaboo\DataGrid\Column\Column`). Argument of this setter should be callback where you get data source like `DibiFluent` or `QueryBuilder`. A similar solution is setting condition to filter.

**Comment by paveljanda** [comment]
Je to v masteru. Jenže, upravil jsem datasourcy + IDataSource = možný BC break.

Dodělám tedy časem některé ostatní issues a vyjde v3.
