### ISSUE TITLE
redrawItem not working

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#139]
Zdarec, pokouším se implementovat do tabulky akce pro změnu statusu.

V presenteru (zpracování ajaxového požadavku)
```
    public function anchorChange($id, $new_status)
    {
        $this->db->table('question')->where('id', $id)->update([
            'is_anchor'=>$new_status,
        ]);

        if ($this->isAjax())
        {
            $this['questionGrid']->redrawItem($id);
        }
    }
```

Datagrid mám nastavený 
```
        $grid->addColumnStatus('is_anchor', 'Ukotvit?')
            ->setAlign('center')
            ->addOption(true, 'Ano')
            ->setClass('btn-success')
            ->endOption()
            ->addOption(false, 'Ne')
            ->setClass('btn-danger')
            ->endOption()
            ->onChange[] = [$this, 'anchorChange'];
```

Po změně statusu se provede update v databázi, ale již nedojde k překreslení řádku, nevíš kde může být problém? díky

**Comment by paveljanda** [comment]
Co se ti pošle v odpovědi? Je tam snippet položky? Nehlásí console nějaký bug?

**Comment by misaon** [comment]
Chyby v konzoli právě že nejsou, myslím si, že Ajaxový signál se pošle..
Přijde mi to až jako ostuda, ale jak zjistím odpověď ajaxu, na kterou se ptáš? :smiley:

**Comment by misaon** [comment]
Pro jistotu posílám i celou komponentu z presenteru (kdyby ti to nějak pomohlo)

```
    public function createComponentQuestionGrid($name)
    {
        $grid = new DataGrid($this, $name);

        $grid->setDataSource(
            $this->db->query('
            SELECT
              question.id,
              question.question_type,
              question_text.text,
              question.order,
              question.created,
              question.is_anchor,
              question.is_supplement,
              question.is_bonus,
              topic.name as topic_name,
              CONCAT(user.first_name, " ", user.last_name) as username
            FROM
              question
              LEFT JOIN topic ON topic.id=question.topic_id
              LEFT JOIN user ON user.id=question.user_id
              LEFT JOIN question_text ON question_text.question_id=question.id
            WHERE question.topic_id=?
            GROUP BY question.id
            ORDER BY question.order ASC
            ', $this->topicID)->fetchAll()
        );
        $grid->setTranslator(Shean\Ublaboo\UblabooTranslator::getTranslator());
        $grid->setItemsPerPageList([17]);

        $grid->addColumnText('topic_name', 'Téma')
            ->setSortable();
        $grid->addColumnText('question_type', 'Typ otázky')
            ->setAlign('center')
            ->setReplacement([
                'simple' => 'Otevřená',
                'order' => 'Seřazovací',
                'select' => 'Výběrová',
            ])
            ->setSortable();
        $grid->addColumnText('text', 'Otázka')
            ->setSortable();
        $grid->addColumnText('order', 'Pořadí')
            ->setAlign('center')
            ->setSortable();
        $grid->addColumnText('is_supplement', 'Je doplňková?')
            ->setAlign('center')
            ->setTemplateEscaping(false)
            ->setRenderer(function($item) {
                if ($item->is_supplement) {
                    return "<i class='fa fa-check text-success'></i>";
                } else {
                    return "<i class='fa fa-times text-danger'></i>";
                }
            })
            ->setSortable();
        $grid->addColumnText('is_bonus', 'je bonusová?')
            ->setAlign('center')
            ->setTemplateEscaping(false)
            ->setRenderer(function($item) {
                if ($item->is_bonus) {
                    return "<i class='fa fa-check text-success'></i>";
                } else {
                    return "<i class='fa fa-times text-danger'></i>";
                }
            })
            ->setSortable();
        $grid->addColumnStatus('is_anchor', 'Ukotvit?')
            ->setAlign('center')
            ->addOption(true, 'Ano')
            ->setClass('btn-success')
            ->endOption()
            ->addOption(false, 'Ne')
            ->setClass('btn-danger')
            ->endOption()
            ->onChange[] = [$this, 'anchorChange'];
        $grid->addColumnText('username', 'Založil')
            ->setSortable();
        $grid->addColumnDateTime('created', 'Založeno')
            ->setAlign('center')
            ->setSortable();

        $grid->addAction('Question:edit', 'Upravit', null, ['questionID'=>'id'])
            ->setClass('btn btn-xs btn-primary');

    }
```

**Comment by paveljanda** [comment]
Chrome -> Developer Tools -> Network.
Pak refreshni stránku, pošli ajaxový request a rozklikni odpověď.

<img width="1068" alt="screen shot 2016-03-11 at 13 32 33" src="https://cloud.githubusercontent.com/assets/1488874/13702291/c1583446-e78d-11e5-8962-2d3f727f688c.png">

**Comment by misaon** [comment]
![aaa](https://cloud.githubusercontent.com/assets/15806356/13702464/31c4f33a-e78f-11e5-9611-6e0bc7e12173.png)

**Comment by misaon** [comment]
Další poznatek...

Když změním status, provede se SQL dotaz ale řádek se nepřekreslí.
Kliknuli (bez refreshe stránky) znovu na změnu statusu, najednou se řádek překreslí.
Takže musím akci vykonat dvakrát, aby došlo k překreslení

**Comment by paveljanda** [comment]
Už vidím, v čem by mohl být problém.

Zkus v tom bloku

```php
if ($this->isAjax())
{
    $this['questionGrid']->redrawItem($id);
}
```

ještě před tím `::redrawItem()` nastavit znovu stejný data source.

**Comment by paveljanda** [comment]
Totiž, pokud se ti nejdřív vytvoří grid (se starým data sourcem) a ty pak změníš prvek v databázi, jsou stále stejná data v datagridu, takže se překresli položka se starým obsahem.

**Comment by paveljanda** [comment]
Používáš totiž array jako data source.  (`ResultSet::fetchAll()` == `array`)

**Comment by misaon** [comment]
Můžeš to nějak vyřešit na své straně, nebo je potřeba tohle ošetřovat pokaždé u mě?

**Comment by paveljanda** [comment]
DataGrid nemá k dispozici připojení k databázi v tomto případě. Předáváš mu pole. Těžko může "odněkud" to pole obnovit.

**Comment by paveljanda** [comment]
Ale je to divné, handle metoda by měla být volána ještě před vytvořením té komponenty. Ještě se nad tím zamyslím.

**Comment by misaon** [comment]
Tvoje rada funguje, ale přijde mi to trošku divné tak jak říkáš, třeba u Grida, co sem dřív testoval tohle fungovalo :/ Nevím jestli jedeš na stejných principech jako Grido..

Budu rád, když se ti to podaří nějak vyřešit, poladit, protože tvoje komponenta je dosti návyková :smile:

**Comment by paveljanda** [comment]
Jj, večer na to mrknu a třeba pošlu zip se sandboxem.

**Comment by misaon** [comment]
Díky moc, budu sledovat tuhle issue :+1:

**Comment by paveljanda** [comment]
Problém je tento:

Handler se nevolá nad presenterem, ale nad datagridem. Až ten ho distribuuje na další callbacky. Funguje to tedy stejně jako formulář.

1, Vytvoří se komponenta datagrid s polem (starým)
2, Zavolá se handler nad vytvořenou komponentou
3, Zavolá se tvůj handler
4, Pokud používáš array jako datasource, je třeba jej znovu nastavit s aktuálními položkami. U všech ostatních datasourců to je netřeba. A nebo si napiš svůj IDataSource, nemělo by to trvat dlouho. :)

Doporučuju ten vlastní datasource, a nebo si holt dát získání toho pole stranou a volat ho už jen krátce z toho anchorChange/createComponentXXXGrid.

[web-project.zip](https://github.com/ublaboo/datagrid/files/170859/web-project.zip)

**Comment by paveljanda** [comment]
Rád bych napsal nějaký ukázkový datasource, který by bylo vhodné používat s Nette\Database. Mrknu na to. Tohle zatím zavírám.

**Comment by misaon** [comment]
Paráda, bylo by dobré tohle nějak vyřešit, prakticky teď běžím jen na DataSource, který je součástí Nette a tvoje komponenta taky, tak kdyby si to spolu rozumělo, měl bys u mě pivko :smile:
