### ISSUE TITLE
Split bower dependencies

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#142]
Bylo by moc fajn, kdyby si vytvořil bower balíček jen s datagridem.
Myslím to tak, že pro bootstrap i nette-forms apod. již mám nastavené závislosti, a když použiji ublaboo-datagrid, stáhnou se mi znovu.
Problém je, že samotné Ublaboo-datagrid soubory v žádném jiném balíčku nejsou.
Můžeš to tedy prosím rozdělit? Nette ajax apod. si dotahám separátně :) Dík

**Comment by paveljanda** [comment]
Tomu úplně nerozumím.. ublaboo-datagrid potřebuje nějaké scripty - závisí na nich. Proto jsou specifikované v bower.json. Tak to má být, ne? nebo to špatně chápu?

**Comment by misaon** [comment]
![nepojmenovany 1](https://cloud.githubusercontent.com/assets/15806356/13731531/c6ceeac0-e96b-11e5-9d7f-505d6871346a.jpg)

Navíc je teď něco špatně, nedaří se mi natahat ublaboo-datagrid ..

**Comment by paveljanda** [comment]
Mám v bower.json podmínku nette-forms >= 2.3.0, nette.ajax.js potřebuje jen 2.2. Upravím. - Pravděpodobně nepotřebuji nette-forms 2.3, budou stačit 2.2. Prozkoumám to.

**Comment by misaon** [comment]
Jinak je to v pořádku, už jsem si to upravil u sebe :)

**Comment by misaon** [comment]
Píšu to protože v bower.json musím mít

    "datagrid-css": "https://github.com/ublaboo/datagrid/blob/master/assets/dist/datagrid.min.css",
    "datagrid-js": "https://github.com/ublaboo/datagrid/blob/master/assets/dist/datagrid.min.js"

aby se mi stáhly jen knihovny čistě použitelné pro tento grid. Víš co myslím?

**Comment by paveljanda** [comment]
No chápu to tak, že nechceš, aby se ti načítaly závislosti assetů datagridu..?
Ale to je přeci nesmysl, když bower.json je od toho, aby definoval závislosti. Nebo mi stále něco uniká?

**Comment by JakubKontra** [comment]
@misaon why close? Any reaction?
