### ISSUE TITLE
Icon name as function in actionCallback

### ISSUE THREAD

**Issue by Attanon** [ublaboo/datagrid#143]
Hi, if I have action like this

```
$grid->addActionCallback('duplicate', 'Duplikovat')
	->setTitle('Duplikovat')
	->setIcon('unlink')
	->setClass('btn btn-xs btn-default')
	->onClick[] = function($item_id) use ($presenter) {
	$presenter->redirect('variationEdit', [
		$item_id
	]);
};
```

I god this error from tracy in nette

![image](https://cloud.githubusercontent.com/assets/3205711/13760483/b3657e86-ea33-11e5-83f3-81d17e63002b.png)

It`s seems to transfer icon as callback. So if I have icon number like php function it is not working.

![image](https://cloud.githubusercontent.com/assets/3205711/13760537/f656a30a-ea33-11e5-9088-85eb653541e7.png)

**Comment by paveljanda** [comment]
Thanks, fixed in 2.3.11
