### ISSUE TITLE
Allow $column->setRenderer for Status column

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#144]
Allow setRenderer for values NOT included in options list, currently the value is just spited into the template, it would be great to have an option to style those values in some way in addition to the status buttons.

**Comment by paveljanda** [comment]
It is already there:

```
$columnStatus::setRendererOnCondition()
```

**Comment by paveljanda** [comment]
Oh, i see, my fault, sorry.

**Comment by paveljanda** [comment]
The thing is, templates have greater priority that user renderers. I am sorry, i will remove the milestone for now before i will figure out whether i want to implement that or not. (it is probably easier to achieve by ColumnText with custom tempalte)

**Comment by paveljanda** [comment]
@juniwalk Ha!
I released new version with this functionality: http://ublaboo.paveljanda.com/datagrid/column#column-callback.

Now, you can easily (more or less..) modify ColumnStatusRenderer though it has template set:

```
$grid->addColumnCallback('status', function($column, $item) {
	if ($item->id == 2) {
		$column->setTemplate(NULL);
		$column->setRenderer(function() {
			return 'a';
		});
	}
});
```

**Comment by juniwalk** [comment]
Thanks, this is sufficient.
