### ISSUE TITLE
onChange invocation of Status column is failing

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#147]
`Fatal error: Call to undefined method Ublaboo\DataGrid\Column\ColumnStatus::onChange() in ~/vendor/ublaboo/datagrid/src/DataGrid.php on line 1634` [see here](https://github.com/ublaboo/datagrid/blob/master/src/DataGrid.php#L1634)

http://ublaboo.paveljanda.com/datagrid/ does not work either.

**Comment by paveljanda** [comment]
God, i am an idiot, a removed extending Nette\Object..... Fixed. :D

Thanks

**Comment by juniwalk** [comment]
Well it happens :D Thanks for the fix.
