### ISSUE TITLE
Big inline edit (save/cancel) translate

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#148]
Ahoj, chci se zeptat, lze si nastavit vlastní překlad tlačítek + seticon apod.?

**Comment by paveljanda** [comment]
v3.0.2, "zanamespacoval" jsem překlady těch tlačítek, nyní je to:
ublaboo_datagrid.cancel
ublaboo_datagrid.save

**Comment by misaon** [comment]
Ok díky

**Comment by paveljanda** [comment]
Ano, ikony, třídy, titulky jsou volitelné:

```
$grid->addInlineEdit()
	->setIcon('user')
```

**Comment by misaon** [comment]
Ještě dotaz na inline editaci.. Je zde možnost přidat metodu addSelect ?
Hodil by se tam selectbox :)

**Comment by paveljanda** [comment]
Kam přesně?

**Comment by misaon** [comment]
Představoval bych si něco takového

```
        // BIG inline editace
        $grid->addInlineEdit()
            ->onControlAdd[] = function($container) {
            $container->addText('order', '');
            $container->addSelect('topic_id')->setItems(['item1', 'item2']);
        };
```

**Comment by paveljanda** [comment]
S tím containerem si můžeš dělat, co chceš.. Je to normálně `Nette\Forms\Container`. :)

**Comment by misaon** [comment]
Jasně, ale hezky by se s tím pracovalo, kdyby tam byla implementovaná i tahle metoda, ber to jen jako návrh :)

**Comment by paveljanda** [comment]
Ale ta metoda tam přeci je. Container, co dostaneš jako parametr v té anonymní funkci, je `Nette\Forms\Container`, takže tam můžeš přidávat všechny input věci, které normálně přidáváš do formulář.

Přidal jsem příklad do dema: http://ublaboo.paveljanda.com/datagrid/edit

**Comment by misaon** [comment]
Ježiš omlouvám se, už to vidím, díky..

**Comment by paveljanda** [comment]
:)
