### ISSUE TITLE
filtering - inline_edit - submit

### ISSUE THREAD

**Issue by hlavacm** [ublaboo/datagrid#149]
Hi, I upgraded to version 3.0.2, and filtering didn't work now. I have a data source from Doctrine with two string columns: name and code with active sorting and filtering. I checked the configuration first, but it seemed okay. 
I found an exception in the method filterSucceeded on line in 1180 (DataGrid class), which followed by: Nette\InvalidArgumentException: Component with name 'submit' does not exist. 
(AJAX) URL was: /www/presenter/?filter%5Bname%5D=&filter%5Bcode%5D=&do=overviewGrid-filter-submit. 
Can you help me? :)

**Comment by paveljanda** [comment]
Can you please show me the code of the factory that returns your datagrid?

**Comment by hlavacm** [comment]
public function createComponentOverviewGrid() {
    $grid = new DataGrid($this, "overviewGrid");

    // data source
    $dataSource = $this->initializeGridSource($this->manager->getQueryBuilder()); // note: it is with alias
    $grid->setDataSource($dataSource);

    // columns
    $grid->addColumnLink("name", "Name", "show")->setSortable();
    $grid->addColumnText("code", "Code")->setSortable();

    // filtering
    $grid->addFilterText("name", "Name:");
    $grid->addFilterText("code", "Code:");

    // translations
    $grid->setTranslator(new SimpleTranslator([
        ...
    ]));

    // actions
    $grid->addAction("show", "")
            ->setIcon("eye")
            ->setClass("btn btn-xs btn-default");
    $grid->addAction("edit", "")
            ->setIcon("edit")
            ->setClass("btn btn-xs btn-info");
    $grid->addAction("delete", "", "deleteOne!")
            ->setIcon("trash")
            ->setTitle("Delete")
            ->setClass("btn btn-xs btn-danger ajax")
            ->setConfirm("Do you really want to delete the record (nr.%s)?", "id");
    // (group)
    $grid->addGroupAction("Delete selected")
            ->onSelect[] = [$this, "handleDeleteMany"];

    // hideable
    $grid->setColumnsHideable();

    // export
    $exportFileName = strtolower($this->getPresenterTitle());
    $grid->addExportCsv("Export to CSV (all)", "$exportFileName.csv");
    $grid->addExportCsvFiltered("Export to CSV (filtered)", "$exportFileName.csv");
}

PS: I use Kdyby/Autowired...

**Comment by paveljanda** [comment]
My fault, v3.0.4 fixes that.

Thanks

**Comment by hlavacm** [comment]
Thanks man, you're doing a really good job (not only with this project :)
