### ISSUE TITLE
Filter range

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#15]
Je nejak možné filtrovať čísla/dátumy od-do, podobne ako cez TwiGrid?

**Comment by JakubKontra** [comment]
Neznám TwiGrid, ale máme tu: https://github.com/ublaboo/datagrid/blob/master/src/Filter/FilterRange.php
a potom 
https://github.com/ublaboo/datagrid/blob/master/src/Filter/FilterDateRange.php

**Comment by romanmatyus** [comment]
Pravdepodobne vyriešené ;) Dobrá práca.
