### ISSUE TITLE
Cizí klíče u MSSQL

### ISSUE THREAD

**Issue by sibka** [ublaboo/datagrid#152]
Data mám uložena na MSSQL 2014. Přidán sloupec s hodnotou načítanou přes cizí klíč
`$grid->addColumnText('odbor_id', 'Odbor')
->setRenderer((function($item) {
 return $item->odbor->hodnota;
}));`
Do verze 3.0.0 vše fungovalo dobře, nyní hlásí chybu: Cannot read an undeclared column 'odbor'
Vyzkoušeno na verzi dev-master.

**Comment by paveljanda** [comment]
Už vím. Přidal jsem zpracování LIMIT (tedy => `OFFSET <offset> ROWS FETCH <limit> ROWS ONLY`) tím způsobem, že se ze selection dostane query a ta se pak spustí přes `Context::query()`, což už není `Table`, ale Result, který nevrací `ActiveRow`, ale `Row` a tenhle objekt už nemá reference.

Předtím ti fungovalo stránkování?

**Comment by sibka** [comment]
Ano fungovalo.

**Comment by paveljanda** [comment]
Můžeš zkusit master?

Koukám, že Nette\...\SqlSrvDriver injectuje totéž do query, ale MsSqlDriver ne. Udělám tedy další datasource ještě pro `MsSqlDriver` a tam to nějak pořeším - aby byl limit podporován i tam.

**Comment by sibka** [comment]
Oprava, moc se omlouvám, nepoužívám MSSQL driver, ale SQLSRV, asi jsem se špatně vyjádřila.

**Comment by paveljanda** [comment]
A funguje ti teď master? Odebral jsem konverzi z Table do ResultSetu při zachování nativního volání limit().

**Comment by sibka** [comment]
Vše funguje, super, díky.
