### ISSUE TITLE
Implement textbox suggestion list

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#154]
Ahoj, bylo by moc fajn, kdyby Datagrid uměl našeptávat textovému filtru :)
Doporučuji JS plugin: https://github.com/LeaVerou/awesomplete
Odkoukal jsem to od projektu GRIDO, a je to užitečná věc.

Díky a držím pěsti s dalším vývojem. :+1:

**Comment by paveljanda** [comment]
Zapřemýšlím nad tím, ale jelikož se neustále filtruje ajaxově, je to podle mě zbytečnost.

Ale ještě na to mrknu.

**Comment by juniwalk** [comment]
Není našeptávačem prakticky celá tabulka, když to filtruje ihned?

**Comment by paveljanda** [comment]
@juniwalk No právě že je. Další našeptávač mi přijde dost zbytečný..
