### ISSUE TITLE
ItemDetail problem

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#155]
Zdar, po kliknutí na "oko" se provede Ajax s chybou 500.
Konzole vyplivne tohle:
` console.log("Cannot access protected property Ublaboo\\DataGrid\\Column\\ItemDetail::$type in …/cache/latte/ublaboo-datagrid-src-templates-datagrid-latte-Template38fa ... ")`
při použití `$grid->setItemsDetail(function() { return 'Lorem Ipsum'; });`

Nenapadá tě, čím by to mohlo být způsobené?

**Comment by paveljanda** [comment]
Fixed in v3.0.9, thx
