### ISSUE TITLE
Cannot access protected property Ublaboo\DataGrid\Column\ItemDetail::$template

### ISSUE THREAD

**Issue by chapcz** [ublaboo/datagrid#157]
When I call item detail I have this error (change ItemDetail::$template to public fixes the problem ):

> Error: Cannot access protected property Ublaboo\DataGrid\Column\ItemDetail::$template in /var/www/html/vendor/latte/latte/src/Latte/Engine.php(219) : eval()'d code:335 Stack trace: #0 /var/www/html/vendor/nette/application/src/Bridges/ApplicationLatte/UIRuntime.php(32): _lbd6ad120575__items(Object(stdClass), Array) #1 /var/www/html/vendor/latte/latte/src/Latte/Engine.php(219) : eval()'d code(441): Nette\Bridges\ApplicationLatte\UIRuntime::renderSnippets(Object(Ublaboo\DataGrid\DataGrid), Object(stdClass), Array) #2 /var/www/html/vendor/latte/latte/src/Latte/Engine.php(98): Template87b775024ad908699b1fcb2c1036a24e->render() #3 /var/www/html/vendor/nette/application/src/Bridges/ApplicationLatte/Template.php(50): Latte\Engine->render('/var/www/html/v...', Array) #4 /var/www/html/vendor/ublaboo/datagrid/src/DataGrid.php(386): Nette\Bridges\ApplicationLatte\Template->render() #5 /var/www/html/vendor/nette/application/src/Bridges/ApplicationLatte/UIRuntime.php(50): Ublaboo\DataGrid\DataGrid->render() #6 /var/www/html/vendor/latte/latte/src/Latte/Engine.php(219) : eval()'d code(42): Nette\Bridges\ApplicationLatte\UIRuntime::renderSnippets(Object(App\Presenters\PeoplePresenter), Object(stdClass), Array) #7 /var/www/html/vendor/latte/latte/src/Latte/Engine.php(98): Template1b14bee810853522975ec9dc97a2ba46->render() #8 /var/www/html/vendor/latte/latte/src/Latte/Template.php(91): Latte\Engine->render('/var/www/html/a...', Array) #9 /var/www/html/vendor/latte/latte/src/Latte/Engine.php(219) : eval()'d code(43): Latte\Template->renderChildTemplate('/var/www/html/a...', Array) #10 /var/www/html/vendor/latte/latte/src/Latte/Engine.php(98): Template4b1e64f8384e0552b4482515638b3a6f->render() #11 /var/www/html/vendor/nette/application/src/Bridges/ApplicationLatte/Template.php(50): Latte\Engine->render('/var/www/html/a...', Array) #12 /var/www/html/vendor/nette/application/src/Application/Responses/TextResponse.php(47): Nette\Bridges\ApplicationLatte\Template->render() #13 /var/www/html/vendor/nette/application/src/Application/UI/Presenter.php(228): Nette\Application\Responses\TextResponse->send(Object(Nette\Http\Request), Object(Nette\Http\Response)) #14 /var/www/html/vendor/nette/application/src/Application/Application.php(141): Nette\Application\UI\Presenter->run(Object(Nette\Application\Request)) #15 /var/www/html/vendor/nette/application/src/Application/Application.php(81): Nette\Application\Application->processRequest(Object(Nette\Application\Request)) #16 /var/www/html/www/index.php(10): Nette\Application\Application->run() #17 {main} Unable to log error: Argument 1 passed to Kdyby\Translation\Diagnostics\Panel::renderException() must be an instance of Exception, instance of Error given

**Comment by misaon** [comment]
Fixed in version 3.0.9

**Comment by paveljanda** [comment]
@chapcz Is it true? Does this problem solve version 3.0.9?

**Comment by chapcz** [comment]
Yes it does - sorry for false issue (my composer held older version even I use tag dev-master - remove and add again solved it).
