### ISSUE TITLE
tfoot block

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#16]
Bolo by možné pridať blok tfoot?

V rendereri stĺpcov by tak bolo možné nastaviť čiastkové výpočty a v päte vypísať sumár hodnôt a pod.

Vďaka!

**Comment by JakubKontra** [comment]
Jasně, implementujeme! :)
+1

**Comment by JakubKontra** [comment]
btw @romanmatyus  pokud bys poslal PR vůbec bychom se nezlobili :-)

**Comment by romanmatyus** [comment]
Žiaľ minulý týždeň som zapracoval do projektu [TwiGrid](http://twigrid.1991.cz/full). O tomto gride som nevedel :(

Ak sa dostanem k výmene, nejaké PR pribudnú ;)

**Comment by paveljanda** [comment]
Je to v masteru.
