### ISSUE TITLE
How to filter column if it is defined in latte?

### ISSUE THREAD

**Issue by devpcz** [ublaboo/datagrid#161]
Hi,
i have defined column:
`{define col-customerName}`
`{$item->customer->name}`
`{/define}`
in file which is set to DataGrid by $grid->setTemplateFile() method.

Filtering in not working for this defined column:
`$grid->addFilterText('customerName', 'Zákazník');`

Please, how to properly filter column?

Data source is result from Nette\Database\Context (Active rows).

Thnx
Pavel

**Comment by paveljanda** [comment]
So you are filtering in array? That is a problem. Array data source thoughts that each item is also array - it is used for simple data representation.

My suggestion is, do not use ArrayDataSource, but this: http://ublaboo.paveljanda.com/datagrid-nette-database-data-source/.

You can still use direct query, but with perfect data source build just for this purpose.

**Comment by paveljanda** [comment]
@devpcz Does my suggestion help you?

**Comment by devpcz** [comment]
I'm sorry, I haven't tried it. I will try it and report it.

**Comment by paveljanda** [comment]
Ping @devpcz 

If my suggestion helped, can a close this issue?

**Comment by devpcz** [comment]
@paveljanda I'm very sorry that I didn't reply (today I don't know what to reply). Thank you for your work.
