### ISSUE TITLE
Session: Default Sort

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#165]
Narazil som na nepríjemný problém.

Vytváram Grid cez továrničku:
```php
protected function createComponent($name)
{
	switch ($name) {
		case 'listGrid':
			$grid = new DataGrid($this, $name);
			$grid->setDefaultSort(['created' => 'DESC']);
			// ...
			return $grid;
	}
}
```

Grid je vložený do komponenty, ktorá je v presentri.
Komponenta je už k presentru pripojená a tak sa v okamihu volania `DataGrid::__construct()` ihneď zavolá aj `DataGrid::attached()`.

```php
public function attached($presenter)
{
	parent::attached($presenter);
	if ($presenter instanceof Nette\Application\UI\Presenter) {
		// ...
		$this->findDefaultSort();
	}
}
```

Problém je, že takto nie je možné nastaviť `defaultSort`.

Bolo by možné presunúť volanie `$this->findDefaultSort();` na neskôr?

Prípadne iný nápad ako to vyriešiť?

> Predpokladám, že rovnaký problém bude aj s filtrovaním, ale potiaľ som sa ešte nedostal.

Vďaka!

**Comment by romanmatyus** [comment]
Dá sa to obísť vytvorením továrničky s manuálnym volaním `findDefaultSort()`, ale nie je to zrovna *systémové riešenie*.

```php
protected function createComponent($name)
{
	switch ($name) {
		case 'listGrid':
			$grid = new DataGrid($this, $name);
			$grid->setDefaultSort(['created' => 'DESC']);
			$grid->findDefaultSort();
			// ...
			return $grid;
	}
}
```

**Comment by romanmatyus** [comment]
Možno by stačilo do `setDefaultSort()` pridať volanie `findDefaultSort()`.

```php
public function setDefaultSort($sort)
{
	// ...
	$this->default_sort = $sort;
	$this->findDefaultSort();

	return $this;
}
```

**Comment by paveljanda** [comment]
Fixed. Chyběl sloupec v databázi.


On April 6, 2016 at 11:36:05, Roman Mátyus (notifications@github.com) wrote:

Možno by stačilo do setDefaultSort() pridať volanie findDefaultSort().

public function setDefaultSort($sort)
{
    // ...
    $this->default_sort = $sort;
    $this->findDefaultSort();

    return $this;
}

**Comment by paveljanda** [comment]
Je to v masteru. Můžeš pls prozkoušet různé varianty?

Půjde to potom v další verze (3.2).

**Comment by romanmatyus** [comment]
Vyzerá, že to funguje. Vďaka.
