### ISSUE TITLE
Translate SelectFilter options

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#166]
I see that you clear out the filter from the Select of the form element, why is that? See https://github.com/ublaboo/datagrid/blob/master/src/Filter/FilterSelect.php#L51

**Comment by paveljanda** [comment]
I do not really understand what you mean, but the translator is "nulled" because it is easier to add already translated values than trying not to translate select options of this form.

**Comment by juniwalk** [comment]
`$grid->addFilterSelect('role', 'client.user.role', ['' => ''] + $this->authorizator->getRoles(), 'u.role');`
![untitled-2](https://cloud.githubusercontent.com/assets/451918/14316767/19663bac-fc05-11e5-9238-ca493b8ca937.png)

**Comment by juniwalk** [comment]
I am used to getting options translated in the form so I get the list of roles and send it into the filter, and then I wonder why they are not translated.

**Comment by paveljanda** [comment]
DataGrid does not know, if you want to translate options or not:

1, Translatable exmaple:
 - User roles
 - Privileges
 - Actions

2, Not-
 - Countries
 - Product names
 - Users names
- ...

You see? What if a don't want to translate the options?

**Comment by juniwalk** [comment]
If I don't, then I don't have translations defined for them, translator then returns them as they are without modification.

**Comment by paveljanda** [comment]
You can't rely on that. Example:

Dictionary defined value: "Blue". Now what if someone is called "Peter Blue"? Than the list of translated options containing users surnames would be translated at one place.

It wasn't so good example, but you see my point.

This way is much more complex.

**Comment by juniwalk** [comment]
That is why all my translations are namespaced, see `client.role.admin`

**Comment by juniwalk** [comment]
The way I see it, using `{_This is my string.}` is wrong, it should be `{_alias.for.my.string}`

**Comment by paveljanda** [comment]
That is true, but not everybody sticks to good practise.

**Comment by juniwalk** [comment]
So I have to create hacks in my app becaue somebody is doing it wrong :/
