### ISSUE TITLE
[QUESTION] How can init JS init after render table rows?

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#169]
Ahoj,
chci-li použít na action v datagridu třeba JS tooltip, nefunguje. Počítám že je to tím, že prvek se vytvoří (vyrenderuje na základě filtru) až po načtení stránky. Jak tedy ošetřit (zprovoznit) kousek JS kódu, aby fungoval?

Dík

**Comment by paveljanda** [comment]
Udělej si `$.nette.ext`, kdy po dokončení ajaq rq inicializuješ bootstrap tooltip.
