### ISSUE TITLE
Skrývanie/zobrazovanie stĺpcov

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#17]
Use case:
Mám obrovské množstvo parametrov - potenciálne veľké množstvo stĺpcov. Každého klienta môžu zaujímať iné.
Grid obsahuje nastavenia a filtre pre všetky. V nastavení gridu je zoznam predvolene zobrazených stĺpcov.
Grid obsahuje komponentu (napr. checkbox dropdown list) so zoznamom všetkých definovaných stĺpcov.
Po označení/zrušení ktoréhokoľvek sa grid prekreslí podla nového nastavenia.
Poradie stĺpcov sa dá meniť - drag&drop.
Nastavenie sa ukladá do session.

Ak by som na toto poslal PR, bol by prijatý?

**Comment by paveljanda** [comment]
Myslím, že je to dobrý nápad.

Jen pár bodů:
1, Už bych neřešil drag & drop sloupců - je to hodně specifické a ještě nikdy jsem na to nenarazil. Mohlo by to taky potencionálně bordelit custom šablony gridu.
2, Ještě chvilku, prosím, s PR počkej, tuto sobotu datagrid v 5 minutách odprezentujeme na posobotě a do té doby ještě musíme dopracovat některé věci. Jakmile bude venku verze 1.0.0, budeme za PR rádi. :)

**Comment by paveljanda** [comment]
Tak verzování už začalo. Pokud budeš mít chuť, můžeš zobrazování/skrývání sloupců přidat. :)

**Comment by paveljanda** [comment]
Vyšlo ve verzi 1.3.0
