### ISSUE TITLE
add RefreshMethod

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#172]
Ahoj,
potřeboval bych překreslit aktuálně vyfiltrovanou tabulku, ve které jsou změněná data Ajaxem. Existuje u tebe nějaká metoda, která je toho schopna?

**Comment by paveljanda** [comment]
Klasicky `DataGrid::redrawControl()`.

Konkrétní snippety, které obsahují položky pak jsou: `table`, `tbody`, `items`, `item-{id}`.

Doporučuji použít `items` snippet:

```
DataGrid::redrawControl('items')
```

**Comment by misaon** [comment]
Deprecated: Non-static method Nette\Application\UI\Control::redrawControl() should not be called statically, assuming $this from incompatible context

**Comment by paveljanda** [comment]
Of course, you have to call `redrawControl()` on `UI\Control` instance.

**Comment by misaon** [comment]
Tak chyba byla asi u mě,

přes handle

```
    public function handleAktualizuj($id)
    {
        if ($this->isAjax()) {
            $this['passwordGrid']->redrawControl('items');
        }
    }
```
to funguje dobře, jakmile jej chci provolat po FormSucceeded, nic se nepřekreslí
```
    public function EditContentFormSucceeded($form)
    {

        $formValues = $form->values;

        .................

        $this['passwordGrid']->redrawControl('items');
        $this->redrawControl('flashMessagesSnip');

    }
```

**Comment by misaon** [comment]
Tak jsme to vyřešili, vše fungkční, ALE, stejně nám nefunguje překreslení snippetu s konkrétním ID... Jinak vše ostatní ano

```
    public function handleUpdatePasswordGrid($itemID)
    {
        if ($this->isAjax()) {
            $this['passwordGrid']->redrawControl('item-'.$itemID);
        }
    }
```

**Comment by paveljanda** [comment]
Zkus tohle:

```
$this['grid']->setDataSource(/*Vybrat úplně vše*/);
$this['grid']->redrawItem($id);
```

**Comment by paveljanda** [comment]
@misaon Funguje?

**Comment by misaon** [comment]
Takhle..
Funguje, pouze snippety table, tbody a items. 
První překreslení se provede, chci jej ale překreslit znovu (AJAXem) již k žádnému překreslení nedojde.

**Comment by paveljanda** [comment]
Netriggruješ náhodou ten další ajax nějak manuálně? Bohužel ti takhle do hloubky asi neporadím..

**Comment by paveljanda** [comment]
@misaon Je tu ještě nějaký problém ohledně datagridu, nebo něco, co by sis přál vyřešit? Nebo mohu zavřít?

**Comment by misaon** [comment]
Klidně zavři, ještě nad tím zadumám. Díky
