### ISSUE TITLE
idea: add $grid->setColumnXxx('','')->setDefaultHide()

### ISSUE THREAD

**Issue by steinbauer** [ublaboo/datagrid#177]
All columns are default 'show' -> missing: 'hide by default'

**Comment by paveljanda** [comment]
This is a good idea, you can send a pull request. :)

**Comment by steinbauer** [comment]
my skill is very small ;o)

(snad pod odborným dohledem, tuším jak na to, ale nikdy jsem nic negithuboval)

**Comment by paveljanda** [comment]
It is in master. I will probably release version 3.2.0 soon and this feature will be in that release.
