### ISSUE TITLE
Pridávanie nových záznamov

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#18]
Inline pridávanie nových záznamov.

Použitie formulára z inline editácie v hlavičke/päte po kliknutí na pridanie záznamu + callback na uloženie.

**Comment by chapcz** [comment]
Nešlo by toto řešit stejně jako Big inline edit #85 (stejný formulář)? => v3 :)

**Comment by romanmatyus** [comment]
Šlo, spolu by to bolo najlepšie.

**Comment by paveljanda** [comment]
Akorát musím nejdřív napsat velkou inline editaci. :) Je to v plánu. Zatím mám jako prioritu NetteDatabaseDataSrouce (pro native query, nikoliv NDBT - ta už je).

**Comment by misaon** [comment]
:+1:

**Comment by paveljanda** [comment]
Otagováno ve verzi 3.3.0
