### ISSUE TITLE
Inline file upload

### ISSUE THREAD

**Issue by vaclavpavek** [ublaboo/datagrid#180]
Bylo by možné nějakým způsobem implementovat inline file upload s následným překreslením řádku? Případně nějaké info jak toto implementovat přes vlastní handler. Děkuji

**Comment by paveljanda** [comment]
Kde by byl ten formulář? Přímo v řádku? Nebo jsi to myslel jinak? Zkus to trošku rozvést/nakreslit.

Možná bys to rád udělal do formuláře v `ItemDetailu`, jako je to plánováno v issue #ref179

**Comment by vaclavpavek** [comment]
Máme řádkový výpis souborů s náhledem obrázku, popisem apod. Do tohoto řádku bychom ještě rádi přidali sloupec kde by pro každý soubor byl upload = změna obrázku.

Zkoušeli jsme udělat vlastní render kdy jsme byly schopní vypsat input který si nesl v atributech data-url=<url vlastniho handleru> a pri vybrani souboru jsme provedli ajax upload na danou url, ale už nedokážeme ovládat grid resp. vynutit překreslení daného řádku. 

Škoda, že form který používá datagrid je odesílaný přes GET a tudíž nelze do kontejneru přidat klasický file input.

Snad jsem situaci popsal dostatečně.

**Comment by paveljanda** [comment]
To, co jsi psal, jsem chtěl nastínit později, protože je to prostě custom řešení. Ale překreslení řádků vynutíš naprosto jednoduše.

1, Ajax uděláš pomocí `$.nette.ajax()`
2, Na serveru vynutíš překreslení řádků úplně stejně, jako když třeba v demu u mě na webu meníš status položky. Taky nechci, aby se posílaly všechny řádky, když stačí jeden.
Příklad překreslení řádku je například zde: http://ublaboo.paveljanda.com/datagrid/action#redrawing-one-row

**Comment by vaclavpavek** [comment]
Pavle díky, tohle mi nějak uteklo :-)
Vyzkouším a prozatím uzavírám.
