### ISSUE TITLE
Nahrazení textarea v malé editaci

### ISSUE THREAD

**Issue by xhulav** [ublaboo/datagrid#182]
lze v malé inline editaci místo textarea vkládat něco jiného? Po úpravě textu jsem zvyklý zmáčknout enter, což mi udělá další řádek. Ideální možnost by bylo si daný input vybrat, protože docela často bych využil i datepicker a selectbox.

**Comment by paveljanda** [comment]
Otagované to bude ve verzi 3.2. Docu najdeš zde:

http://ublaboo.paveljanda.com/datagrid/edit#different-input-types-and-element-attributes
