### ISSUE TITLE
3-stavový multisort

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#19]
Každý stĺpec je po prvom kliknutí zoradený ASC, po druhom DESC a po treťom sa nezoraďuje.

Kliknutím na 1+N stĺpec sa nastavuje poradie zoradenia.

**Comment by paveljanda** [comment]
Souhlas.

Tomu druhému úplně nerozumím. Mohl bys to, prosím, rozvést?

**Comment by paveljanda** [comment]
Implementoval jsem 3 stavy řazení, zavírám.

Pokud jsi myslel ještě něco jiného, prosím znovuotevři. Koncem týdne bude na webu datagridu aktuální verze.

**Comment by romanmatyus** [comment]
Tým druhým som myslel podporu multisortu - zoraďovanie podla viacerých stĺpcov.

Pre inšpiráciu fungovania [TwiGrid](http://twigrid.1991.cz/filtering).

**Comment by paveljanda** [comment]
Zatím zavírám. Multisort jsem zatím nikdy nepotřeboval, ale přidám to v sobotu v noci to oficiálního vlákna a pokud to pr lidí bude chtít, implementuji.
