### ISSUE TITLE
ItemDetailForm error

### ISSUE THREAD

**Issue by JanPosolda** [ublaboo/datagrid#191]
Zdar,
zkouším zobrazení formuláře v detailu položky. Dle dokumentace:
$presenter = $this;
$grid->setItemsDetail();

$grid->setItemsDetailForm(function(Nette\Forms\Container $container) use ($grid, $presenter) {
 $container->addHidden('id');
 $container->addText('name');

 $container->addSubmit('save', 'Save')
  ->onClick[] = function($button) use ($grid, $presenter) {
  $values = $button->getParent()->getValues();

  $presenter['grid']->redrawItem($values->id);
 };
});

Při volání $grid->setItemsDetail() s prázdným parametrem mi vyhazuje vyjímku: 
call_user_func() expects parameter 1 to be a valid callback, no array or string given

**Comment by paveljanda** [comment]
Do masteru jsem přidal exception, která lépe vysvětlí situaci.

Jelikož jsi volal `DataGrid:: setItemsDetail()` bez parametrů, šablona datagridu očekávala, že budeš mít definovaný blok `{block #detail}...{/block}` v šabloně. Jelikož jsi ho neměl definován, pokoušel se datagrid spustit custom renderer, který by vykreslil detail položky...

**Comment by JanPosolda** [comment]
Díky za vysvětlení, nyní mi vše funguje.
