### ISSUE TITLE
setEditableCallback: Value parameter si bad in url

### ISSUE THREAD

**Issue by daihousl** [ublaboo/datagrid#193]
It pass only `&value` to the url not as paramter of grid: `&examplesGrid-value`.
Nice example is your example. It has this problem too. :)
http://ublaboo.paveljanda.com/datagrid/

**http://ublaboo.paveljanda.com/datagrid/?examplesGrid-key=name&examplesGrid-id=10&do=examplesGrid-edit&value=vmkppicf1zsdasd**

This is reason why second paramter of `setEditableCallback` is empty, everytime.
I have last version of grid.

**Comment by paveljanda** [comment]
How did you achieve this behaviour? If i click on the Name column and edit the textarea, POST request is sent to the server and correct answer && flashMesage is received.

I can not make the datagrid behave as you said - sending the value as a GET parameter.

**Comment by daihousl** [comment]
@paveljanda Česky to bude lepší. Je jedno jestli GET nebo POST. Problém je v tom, že druhý parameter je vždy prázdný. A dostanu se k němu jedině přes ``$this->presenter->getParameter('value')`. Ta url kterou jsem sem dal nění nijak upravená. To je to co najdu v kozoli po ukončení editace (odeslání).

**Comment by paveljanda** [comment]
FlashMessages na to v demu nejsou navázané (jen se hodí echo do konzole), ale dík za připomínku, navážu. S příští verzí už to bude na webu.

Ale stále to nechápu. Editoval jsem textové pole, klikl vedle a xhr vypadá takto:

Url: http://ublaboo.paveljanda.com/datagrid/?examplesGrid-key=name&examplesGrid-id=9&do=examplesGrid-edit
POST data:
    value: aaaa

A správně se v presenteru odchytí ID `9` a new_value `aaaa`.

**Comment by paveljanda** [comment]
Nebo já to přidám hned do těch flashmessages, ať je to vidět.

**Comment by paveljanda** [comment]
http://ublaboo.paveljanda.com/datagrid/edit

**Comment by daihousl** [comment]
@paveljanda Aha. Tak v tom případě mám špatně v kodu něco já :(
Bohužel nechápu co, když jsem jen zkopíroval http://ublaboo.paveljanda.com/datagrid/edit#small-inline-editing A $value je vždy bez hodnoty :(

**Comment by paveljanda** [comment]
Zkusím si to hodit do komponenty a ještě napíšu.

**Comment by daihousl** [comment]
@paveljanda Zjistil jsi něco? :)

**Comment by paveljanda** [comment]
Nic. Je to u mě v pohodě. V POSTU mám formulářová data: ['value' => 'nova hodnota'] a vše funguje jak má..

**Comment by paveljanda** [comment]
@daihousl Stále potíže? nebo již mohu tuto issue zavřít?

**Comment by daihousl** [comment]
Stále mi to ten parameter nepředává. Ale nevadí. Workaround do budoucna mám a ted jsme případný grid nahradili externí službou. Takže zatím nebude potřeba.
