### ISSUE TITLE
Aktualizace ItemsDetail

### ISSUE THREAD

**Issue by JanPosolda** [ublaboo/datagrid#195]
Zdar,
mám problém s aktualizací dat při zobrazení ItemsDetail.
Nastavím si dataSource pro grid a setItemsDetail

`$grid->setDataSource($source);`
`$grid->setItemsDetail(function($item) {`
`return $item->email;`
`});`

ItemsDetail funguje správně.
Pak když aktualizuji dataSource

`$this['grid']->setDataSource($updatedSource);`

tak se ItemsDetail zobrazují pro stará data, nezohlední se aktualizace dataSource gridu

**Comment by paveljanda** [comment]
Mohl bys ukázat celou factory datagridu?

**Comment by JanPosolda** [comment]
```
public function createComponentGrid($name)
{
    $grid = new DataGrid($this, $name);
    $allOrders = $this->eshopAPI->GetAllOrders();

	$grid->setDataSource($allOrders);

	$grid->addColumnText('email', 'Email');

	$grid->setItemsDetail(function($item) {
		return $item['email'];

	});
    return $grid;
}
```

Pak při zpracování formuláře, který provádí nějakou filtraci vstupních dat, chci dataSource aktualizovat

```
public function ConditionFormSucceeded($form)
	{		
		$result = $this->eshopAPI->GetQueryResult($condition, $values->value);

		$this['grid']->setDataSource($result);
		$this['grid']->redrawControl();
	}
```

**Comment by paveljanda** [comment]
A co je to za formulář? Odkud se submituje?

**Comment by JanPosolda** [comment]
Na základě formuláře se vyberou data z databáze a má se aktualizovat zobrazení gridu.

```
public function createComponentConditionForm($name)
	{
		$form = new Nette\Application\UI\Form();
		$form->addSelect('column')
			->setItems(EshopAPI::$columnsMapping);
		$form->addSelect('operator')
			->setItems(EshopAPI::$operators, false);
		$form->addText('value');
		$form->onSuccess[] = array($this, 'ConditionFormSucceeded');

		return $form;

	}
```

**Comment by paveljanda** [comment]
Pravděpodobně máš někde z nějakého důvodu přehozené vytváření komponent? nebo něco takového asi. Zkus si v tom `conditionFormSucceeded()` jenom nastavit `$this->neco = $values->neco` jako property presenteru a pak to neco posílat jako argument v `createComponentGrid `

**Comment by JanPosolda** [comment]
Ještě tedy dodám, že dataSource se mi aktualizuje a položky gridu se překreslí správně. Jen při zobrazení detailu jsou hodnoty pro stará data.

**Comment by paveljanda** [comment]
Aha, už asi vím, čím to je. JS si "cachuje" ItemDetail, aby se pokaždé nevytvářel požadavek na server. Přidám nějaký payload argument, který to zresetuje.

**Comment by paveljanda** [comment]
Můžeš to zkusit i na masteru? Mně normálně `$p['examplesGrid']->redrawControl();` funguje. Překreslí to i všechny item detaily..

**Comment by JanPosolda** [comment]
Zkoušel jsem i na masteru a item detaily se nepřekreslí.

**Comment by JanPosolda** [comment]
Ještě jsem zjistil, že pokud aktualizuji dataSource ve funkci formSucceeded, tak se mi překreslí data, ale ne item detaily. Pokud aktualizaci udělám ve startupu (pomocí property si zadetekuji formSucceeded a na jejím základě ve startupu provedu update gridu), tak vše funguje jak má, tj. i detaily se překreslí.

**Comment by paveljanda** [comment]
Hmm, tak to máš asi nějak popřeházené vytváření komponent? Opravdu v tomto asi už víc neodkážu poradit.

**Comment by JanPosolda** [comment]
Mohl bys mi prosím poslat příklad použití, kde ti to funguje? Třeba jen jednoduchý projekt s datagridem.

**Comment by JanPosolda** [comment]
Problém jsem již vyřešil správným nastavením dataSource - předávát jako parametr do funkce createComponent.
