### ISSUE TITLE
Toggle detail blok

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#20]
Každý riadok môže mať svoj detail renderer.

Po definovaní bloku šablóny *detail* sa zobrazí pre každý riadok button *detail*.

Po kliknutí na tlačidlo sa načíta snippet s vykreslenou šablónou - samostatný riadok pod riadkom na ktorý bolo kliknuté.

Využitie
----------
Mám zoznam faktúr. Všetky potrebné informácie sa mi do gridu nezmestia. Štandardne musím vytvoriť samostatnú stránku s náhľadom faktúry, presenter atď.

S touto úpravou definujem iba časť šablóny s detailom priamo do gridu.

*Inšpirácia - detaily platieb v internetovom bankovníctve mBank.*
![grid](https://cloud.githubusercontent.com/assets/1110294/12570252/49c167b6-c3d6-11e5-85a4-d509d5751ca9.png)

**Comment by JakubKontra** [comment]
Můžeš prosím přiložit screenshot z internetového bankovnictví mBank? děkuji.

**Comment by paveljanda** [comment]
Ajaxové načítání by znamenalo mnohem víc obsluhy. Souhlasím s featurou - dobrý nápad, ale radši bych rovnou vyrenderoval data do gridu a při rozkliknutí už by se jen zobrazovaly načtené informace. Zase tolik systémových prostředků si to nevezme - znamená to pár znaků na každý row - se stránkováním po 50 je to zanedbatelné.

**Comment by romanmatyus** [comment]
Popravde nezisťoval som v zdrojáku koľko úsila by ten Ajax stál, ale podla mňa je to dobrý nápad ;)

Predpokladám, že reálne, napríklad pri faktúrach a pod., používateľa zaujme nanajvýš jedna položka, zväčša žiadna. Nezdá sa mi správne kvôli tomu prenášať N, potenciálne rozsiahlych, šablón.

Konkrétne ja spravujem projekt, kde klient vyslovene nechce stránkovanie, pri čom ide o vyše 800 riadkovú tabuľku.
Detail jednej položky v tej tabuľke má viac ako 3 kB - prenášalo by sa pri každom novom requeste ~2,4 MB zbytočne, nehovoriac o náročnosti renderu.

**Comment by paveljanda** [comment]
Implementováno - první načtení ajaxové, podruhé už se jen toggluje element, ale nenačítá se.

Večer to přidám na web (do dokumentace) spolu s ukázkou.

**Comment by paveljanda** [comment]
@romanmatyus Je to už i na webu: http://ublaboo.paveljanda.com/datagrid/

**Comment by romanmatyus** [comment]
Žasnem! Skvelá práca!
