### ISSUE TITLE
AddColumnLink, access to a element?

### ISSUE THREAD

**Issue by dakorpar** [ublaboo/datagrid#201]
Hi, it would be nice if it would be possible that we can get access to link element, for example
`$grid->addColumnLink()->getInnerElement()`
would return instance of a element so we can set up all attributes needed.
Currently I'm having issues with setting target attribute...
I can create pull request as well for this, just want to see if I'm missing something first...

**Comment by paveljanda** [comment]
http://ublaboo.paveljanda.com/datagrid/column#column-td-th-attributes

**Comment by paveljanda** [comment]
Is that what u needed? If not, please reopen this issue.

**Comment by paveljanda** [comment]
Ah, I see, you mean the `<a>` element?

**Comment by paveljanda** [comment]
In that case simply use `ColumnText` and custom renderer, template or block.

**Comment by dakorpar** [comment]
Hi, yes, that was my case, thought it could be usefull to do it directly, but currently there's no option to do that, thanks for quick reply.

**Comment by paveljanda** [comment]
Yes it would be nice to have access to the `<a>` element. But that would stand against the simplicity of ColumnLink. In each case you need to customize that element, it is better to use `Column` with template, block or renderer callback.
