### ISSUE TITLE
Inline Editing/ adding, when editing validation alert received for add form

### ISSUE THREAD

**Issue by dakorpar** [ublaboo/datagrid#202]
Hi, I have a form which has inline editing and inline adding feature, all was ok before adding some validation.
When I add setRequired() to field that is in inlineAdd, I cannot do inline edit anymore since I get alert box (this field is required) when editing... (I'm also using live validation and works on all forms)

**Comment by paveljanda** [comment]
That is a duplicit issue. (https://github.com/ublaboo/datagrid/issues/197)
