### ISSUE TITLE
vlastní vykreslení objektu v setItemsDetail

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#203]
Zdarec, chci se zeptat, jestli lze v metodě setItemsDetail vykreslit objekt.

```
        $grid->setItemsDetail(function ($item) {
            return $this->renderProjectItemTable($item->id);
        })
```

Konkrétně bych chtěl v této metodě setItemsDetail vykreslit novou tabulku Ublaboo, ale nevím, jestli to není prasárna. Co myslíš?

**Comment by paveljanda** [comment]
@misaon Wow. :D To nevím, můžeš to zkusit, no. Ale principiálně by to nemělo jít minimálně z hlediska html. Ublaboo\datagrid používá jeden velká formulář. Tudíž by v detailu byl další vnořený formulář. A v html nelze mít formulář ve formuláři (https://www.w3.org/TR/xhtml1/#prohibitions).

Ale vykresli si tam jak chceš, když ti to bude fungovat. :)

**Comment by paveljanda** [comment]
@misaon Máš stále s něčím trable? Můžu ještě nějak pomoci, nebo mohu issue zavřít?

**Comment by misaon** [comment]
V pohodě, nakonec jsem si vytvořil vlastní komponentu, ale škoda, že to technicky není možné :smile:
