### ISSUE TITLE
Aktualizace dataSource

### ISSUE THREAD

**Issue by JanPosolda** [ublaboo/datagrid#209]
Zdar,
měl bych dotaz, zda je nějak možné provést aktualizaci dataSource. Tedy odstranit původní a vložit nové.
Př. mám v gridu vložený nějaký dataSource, pak přiřadím nový. Poté použiji seřazení podle libovolného sloupce a data s překreslí z původního dataSource.

**Comment by paveljanda** [comment]
Když znovu zavoláš `DataGrid::setDataSource()`, tak se nastaví nový datasource.. To potřebuješ?

**Comment by JanPosolda** [comment]
Nový dataSource se mi nastaví (znovu zavolám `DataGrid::setDataSource()`), grid se překreslí. Ale pak když dám seřadit podle nějakého sloupce, tak se zobrazí výsledek, ale nad původním dataSource.

**Comment by paveljanda** [comment]
A ty chceš kombinovat dva datasourcy neustále? Nebo chceš ze začátku jeden a pak druhý? Tak si to řiď v továrně komponenty třeba podle session dat.

**Comment by JanPosolda** [comment]
No dataSource se mi mění dle zadání nějaké vstupní podmínky.
Ale tahle myšlenka mi pomohla:
>Tak si to řiď v továrně komponenty třeba podle session dat.

Díky za pomoc.
