### ISSUE TITLE
bower install ublaboo-datagrid nefunguje

### ISSUE THREAD

**Issue by steinbauer** [ublaboo/datagrid#211]
Ve zcela prázdné instalaci píše příkaz ```bower install ublaboo-datagrid``` toto:
```
bower ublaboo-datagrid#*        cached https://github.com/ublaboo/datagrid.git#4.0.1
***
bower nette-forms#~2.2, ~2.3     ENORESTARGET Tag/branch ~2.2, ~2.3 does not exist

Additional error details:
Available tags: netteForms-wip, v2.2.0, v2.2.1, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.3.0, v2.3.1, v2.3.2, v2.3.3, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.4.0-RC1
Available branches: master, v2.2, v2.3
```

Popravdě, netuším, předpokládám že `~2.3 != v2.3.8` ale nevím, jsem newbie.   
Každopádně na čistém stroji smůla.

**Comment by paveljanda** [comment]
Uff ten bower mě jednou zabije. Mrknu na to.

**Comment by steinbauer** [comment]
JJ, je to boj, dnes si náhodou druhý projekt kde s tím bojuji. :)

Jinak se připrav: s čerstvým nette 2,4 taky ublaboo nefunguje (asi jen závislosti)

**Comment by paveljanda** [comment]
Jj, už jsem testoval. Viz https://forum.nette.org/cs/26250-pojdte-otestovat-nette-2-4-rc

Pár věcí se tam musí fixnout.. Něco u mě, něco u latte a nette..

**Comment by paveljanda** [comment]
Můžeš to zkusit teď pls? Dal jsem to v4.0.2.

**Comment by steinbauer** [comment]
Bower install prošel, bohužel čistá instalace stále zlobí: https://github.com/ublaboo/datagrid/issues/213
