### ISSUE TITLE
Nepovinný bootstrap-select

### ISSUE THREAD

**Issue by harmim** [ublaboo/datagrid#213]
Udělat bootstrap-select nepovinným.

_Tady jsem na to narazil._

![screenshot 2016-05-05 18 26 41](https://cloud.githubusercontent.com/assets/13155661/15052433/f8400b3c-12fd-11e6-954c-568aaa028b6b.png)

**Comment by steinbauer** [comment]
Potvrzuji stejný problém - čistá instalace přes bower znemožní celý JS

**Comment by steinbauer** [comment]
Podle všeho stačí toto - jako hotfix:
```
datagridFitlerMultiSelect = function() {
  var select;
  select = $('.selectpicker').first();
  if($.fn.selectpicker) {
    return $.fn.selectpicker.defaults = {
      countSelectedText: select.data('i18n-selected'),
      iconBase: '',
      tickIcon: select.data('selected-icon-check')
    };
  }
};
```
