### ISSUE TITLE
Big inline editing - on save redraw a data grid

### ISSUE THREAD

**Issue by dkocian** [ublaboo/datagrid#214]
Hi,
is possible to redraw the whole data grid on save in big inline edit? I tried to wrap data grid to the snippet and to redraw it but was displayed only edited row.

Thx for help :-)

**Comment by paveljanda** [comment]
Zatím v masteru. Bude v příští verzi (4.2). Použítí:

```php
$grid->getInlineEdit()->onCustomRedraw[] = function() use ($grid) {
	$grid->redrawControl();
};
```

Tedy pokud nebude event `InlineEdit::onCustomRedraw` obsahovat žádné listenery, překreslí se normálně ta row. Jinak se nic samo nepřekresluje a je na userovi, co si překreslí.
