### ISSUE TITLE
Do not hide settings menu when clicking on "Show all columns" or some of the other options.

### ISSUE THREAD

**Issue by jelen07** [ublaboo/datagrid#215]
When user un/hiding columns, 
the columns list will always disappears. It would be nice, if the columns list perists after xhr request.

![abjnxo20pq](https://cloud.githubusercontent.com/assets/2346295/15111234/07d56a34-15e6-11e6-8cb5-6000db8e8f58.gif)

**Comment by paveljanda** [comment]
It would indeed. You can send a PR. :)

**Comment by jelen07** [comment]
First I have to improve my *contributions* skill... 👼

**Comment by misaon** [comment]
:+1:

**Comment by paveljanda** [comment]
@jelen07 Closing for now. I won't implemented it. If you will, you can create a PR anytime.
