### ISSUE TITLE
responzivita datagridu

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#217]
Zdarec,

v latte šabloně mám použitý následující kód, kterým bych chtěl (dle Bootstrapu) zrespnzivnit tabulku
```
    <div class="table-responsive">
        {control orderGrid}
    </div>
```
Funguje, problém nastane tehdy, když začneš v responzivní tabulce scrollovat (dolů), např. tlačítko pro skrývání sloupců zajede směrem nahoru, což by podle mě nemuselo, co myslíš?

Napadá mě možnost přidat metodu setResponsive na grid (ty by si u sebe ve vykreslování tbody nastavil "něco jako" classu table-responsive (z bootstrapu)

**Comment by paveljanda** [comment]
To by se asi musely překopat styly. Věc se má takto: Už na začátku jsem psal, že chci dělat šablonu co nejvíc upravitelnou (Aby se jí nebáli frontenďáci jako například u o5/grido). Takže pokud chci něco, co se bude pěkně zobrazovat na mobilu, bude lepší podědit šablonu a přepsat patřičné bloky.

Bohužel nemíním upravovat šablonu ani styly datagridu pro responzivní web (zatím). Co je ale v plánu, je více témat (více CSS). Z nich by určitě některé mohly být jednodušší a responzivní.

Doufám, že jsem odpověděl na otázku.

**Comment by misaon** [comment]
Ačkoliv tvému postoji k tomuto tématu moc nerozumím, respektuji že to tam implementovat nehodláš. Je to škoda

**Comment by paveljanda** [comment]
@JakubKontra Co si to tom myslíš?
