### ISSUE TITLE
datasource - table join ambiguous id

### ISSUE THREAD

**Issue by EchoZulu** [ublaboo/datagrid#238]
mám tabulky vendor a user(vazba n:m)

> CREATE TABLE `vendor` (
> 	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
> 	`name` VARCHAR(255) NOT NULL COLLATE 'utf8_bin',
> 	PRIMARY KEY (`id`)
> );

> CREATE TABLE `vendor_contact_persons` (
> 	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
> 	`vendor_id` INT(10) UNSIGNED NOT NULL,
> 	`user_id` INT(10) UNSIGNED NOT NULL,
> 	PRIMARY KEY (`id`),
> 	INDEX `vendor_contact_persons_user_id_foreign` (`user_id`),
> 	INDEX `vendor_contact_persons_vendor_id_foreign` (`vendor_id`),
> 	CONSTRAINT `vendor_contact_persons_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE,
> 	CONSTRAINT `vendor_contact_persons_vendor_id_foreign` FOREIGN KEY (`vendor_id`) REFERENCES `vendor` (`id`) ON DELETE CASCADE
> );

> CREATE TABLE `user` (
> 	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
> 	`name` VARCHAR(255) NOT NULL COLLATE 'utf8_bin',
> 	PRIMARY KEY (`id`)
> );

Jako datasource používám Nette\Database\Table 

> $vendors = $this->databaseContext->table('vendor')
    ->where(':vendor_contact_persons.user_id = ?', $this->presenter->user->id);
> $this->grid->setDataSource($vendors);

Pokud si nechám vygenerovat form v detailu řádku (klik na ikonku v actions),
datagrid se pokusí znovu načíst data pro konkrétní řádek a vygeneruje query 
> SELECT `vendor`.* 
> FROM `vendor` 
> LEFT JOIN `vendor_contact_persons` ON `vendor`.`id` = `vendor_contact_persons`.`vendor_id` 
> WHERE (`vendor_contact_persons`.`user_id` = 2) AND (`id` = '1') 
> LIMIT 1

které končí chybou "Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous"

**Comment by dakorpar** [comment]
I don't understand much, but this is SQL error, and not related to datagrid.
This query is wrong
```
SELECT vendor.* 
FROM vendor 
LEFT JOIN vendor_contact_persons ON vendor.id = vendor_contact_persons.vendor_id 
WHERE (vendor_contact_persons.user_id = 2) AND (id = '1') 
LIMIT 1
```
should probably be
```
SELECT vendor.* 
FROM vendor 
LEFT JOIN vendor_contact_persons ON vendor.id = vendor_contact_persons.vendor_id 
WHERE (vendor_contact_persons.user_id = 2) AND ( vendor.id = '1') 
LIMIT 1
```

**Comment by paveljanda** [comment]
@EchoZulu You can define primary_where_column for item detail via the second argument of `DataGrid::setItemsDetail()`.
