### ISSUE TITLE
Empty $column_count

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#24]
Upozornenie s prázdnym výsledkom sa zobrazuje iba do jedného stĺpca.

[Example](http://ublaboo.paveljanda.com/datagrid/?examplesGrid-sort%5Bname%5D=ASC&examplesGrid-filter%5Binserted%5D%5Bfrom%5D=14.%201.%202016&examplesGrid-filter%5Binserted%5D%5Bto%5D=29.%201.%202016&)

**Comment by paveljanda** [comment]
Díky, fixnuto.
