### ISSUE TITLE
TreeView - Flex not working in older Safari

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#240]
TreeView has a problem displaying Flex as a table in Safari, check the screenshot.

![datagrid-treeview-issue](https://cloud.githubusercontent.com/assets/451918/15504894/6241a528-21c1-11e6-8ee5-553d590d43c0.png)

**Comment by paveljanda** [comment]
@juniwalk Prosímtě na jakém OS to safari běží? Windows? Už si to nepamatuji. A Nemůžu najít Safari 9 pro Windle..

**Comment by juniwalk** [comment]
@paveljanda Beží na Windows, ale dělá to i na OS X. Safari si stáhni na [Filehippo](http://filehippo.com/download_safari/)

**Comment by paveljanda** [comment]
Mně to běží na Macu úplně OK.
A to je přesně ono - na Win lze stáhnout pouze Safari 5. To ještě flexbox neumí. A bohužel všechno překopávat kvůli lidem, kteří jsou na Win a používají Safari.. To procento bude zanedbatelné. Vlastně mmnt, kouknu se do GA, kolik lidí to je.

**Comment by paveljanda** [comment]
Návštěvníci ublaboo.paveljanda.com s Windows:

- Chrome (73,58%)
- Firefox (25,10%)
- Opera (1.09%)
- Internet Explorer (0.16%)
- Edge (0.08%)

Safari na Win nikde.

**Comment by JakubKontra** [comment]
Safari 5 na Windows je jako IE6. Můj názor. Neznám nikoho kdo by to používal natož měl nainstalované.

**Comment by juniwalk** [comment]
Nejde o Safari na Windows, jde o to že zákošovi to dělá na Macu a my mac nepoužíváme tak jsme to zkoušeli zpreprodukovat tak, že jsme nainstalovali Safari pro Win.

**Comment by JakubKontra** [comment]
@juniwalk aha, tak se na to podíváme. :)

**Comment by juniwalk** [comment]
@JakubKontra Já to teď zkoušel u kolegy co má nově Mac Book a jemu to funguje jak má :)

**Comment by paveljanda** [comment]
Takže cajk?

**Comment by juniwalk** [comment]
@paveljanda Na posledním Safari ano, nevím ale co má ten zákazník za verzi.

**Comment by paveljanda** [comment]
@juniwalk Zkus to zjistit. Pokud tu 9, tak jsi v cajku. Jinak jsi v háji a zkus to, co jsem psal do gitteru..

**Comment by juniwalk** [comment]
Ahoj, jen update, ten problem byl prý v Safari na iPhone (asi verze 5), na MacBooku to jede ok.

**Comment by paveljanda** [comment]
Můžu to zavřít? Responzivní "theme" bude, ale neplánuji to pro aktuální verzi.

**Comment by juniwalk** [comment]
Já už ho neřeším (toho zákoše), jsem z něj na prášky...

**Comment by JakubKontra** [comment]
@juniwalk  +1 za "zakoš"e. :D
