### ISSUE TITLE
Hide colums not working

### ISSUE THREAD

**Issue by neo82nd** [ublaboo/datagrid#241]
It's broken in v4.1.3, even in your demo http://ublaboo.paveljanda.com/datagrid/ - ajax request returns code 500

**Comment by paveljanda** [comment]
Nette/Latte behaves unreasonably in that case. Hmmm. Thanks for report.

**Comment by paveljanda** [comment]
That is apparently bug in latte snippets implementation.

**Comment by neo82nd** [comment]
Thx for quick fix. But still it's not working for me. Request is not failing anymore, but columns are not hiding - in response are snippets with all columns. Any advice what can I check if it's not problem in my grid usage? I have set only $grid->setColumnsHideable();
