### ISSUE TITLE
Pri zmene filtru se ignoruje nastaveni per page

### ISSUE THREAD

**Issue by SiViN** [ublaboo/datagrid#246]
Nastavim ALL nebo 20, 50 apod. a pokud zmenim jakykoliv filtr (textovy, select ...) zustane nastaveno v selectu ALL ale datagrid funguje jako kdyby byl default
![2016-05-26_14-02-16](https://cloud.githubusercontent.com/assets/17454320/15573916/a3fffde0-234a-11e6-946e-3d8dfe692205.jpg)

**Comment by paveljanda** [comment]
Can you please try master branch?

**Comment by SiViN** [comment]
yes, now is master branch ok, thx for your fix
