### ISSUE TITLE
Inline edit v gride zobrazenom v snippete

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#247]
Grid načítavam v snippete.

Obslužný JS sa inicializuje iba pri načítaní webu. Po načítaní gridu v snippete sa príslušné metódy neinicializujú.

```javascript
$(document).on('click', '[data-datagrid-toggle-inline-add]', function(e) {
	# ...
});

$(document).on('mousedown', '[data-datagrid-cancel-inline-add]', function(e) {
	# ...
});
```

**Comment by paveljanda** [comment]
A načítáš ty scripty určitě? Odchytávání eventů pomocí jQuery přes`$(document).on('nejaky-event', ...)` by nemělo dělat problém. jQuery si tuším samo deleguje eventy.
Stejně jako neinicializuji tyto eventy při stránkování/filtrování/sortění dataridu..

**Comment by romanmatyus** [comment]
Skúsim spraviť nejaké jednoduché demo. Možno som spravil chybu inde.

Faktom je, že mám v aplikácií už asi 10 gridov a jediný ktorý trochu blbne (iba JS) je ten ktorý načítavam v snippete.

**Comment by paveljanda** [comment]
Ano, zkus to prosím hodit do nějakého sandboxu (kde bude to načítání snippetem), já se na to kouknu.

**Comment by paveljanda** [comment]
Povedlo se udělat nějaké demo?
