### ISSUE TITLE
text-right etc. [deprecated in Bootstrap v4]

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#248]
Zdarec,

chci jen upozornit, že classa text-right, která je v aktuální verzi Bootstrapu již ve verzi 4 není. Nahradila ji **text-xs-right**. Problém jsem zaregistroval v patičce datagridu, konkrétně u per-page selectboxu.

**Comment by paveljanda** [comment]
@misaon Už je Bootstrap 4 oficiálně releasnutý? Pokud ne, tak počkám, až bude.

Díky za notice.

**Comment by misaon** [comment]
Final verze ne, ale venku je pre-release.
