### ISSUE TITLE
add setRenderer method to setColumnsSummary

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#249]
Tuším že to momentálně z hlediska koncepce nejde, ale bylo by fajn, kdyby šlo před/za sumu přidat nějaký text, ikonu atd.

Dík ;)

**Comment by paveljanda** [comment]
Dobrý nápad.

**Comment by paveljanda** [comment]
No, nejlepší bude, když si podědíš template a přepíšeš `{block columnsSummary}`. Přijde mi to jako nevhodnější varianta.
