### ISSUE TITLE
When exporting with encoding different then utf8 some rows are skipped

### ISSUE THREAD

**Issue by dakorpar** [ublaboo/datagrid#253]
I have a grid, and when I export it with UTF8 all rows are exported but since it's UTF8 without BOM excel is not recognizing utf8 so I set up local encoding, but then I receive many empty rows...

**Comment by dakorpar** [comment]
It's an iconv thing, but maybe there should be some check in CSVResponse.php that would at least throw warning or something...

**Comment by paveljanda** [comment]
Could you send a PR, where the BOM would be optional (disabled by default)?

**Comment by dakorpar** [comment]
Will do as soon as I catch some time...

**Comment by paveljanda** [comment]
Will be in next minor version
