### ISSUE TITLE
Špatně vytvořená url

### ISSUE THREAD

**Issue by daihousl** [ublaboo/datagrid#256]
Když použiji ``addAction(`` a do $href dám 'delete!', tak to správně odkazuje na grid.
Když použiji v templatě n:href nebo {link}, tak to hodí error ``Invalid link: Unknown signal 'delete', missing handler Ublaboo\DataGrid\DataGrid::handledelete()``

Tak jse msi řekl, že handle přenesu do presenteru.
V templatě s použitím {plink} je to vše v pořádku.
Jenže do ``addAction(`` odkaz na handle v presenteru nedostanu .....

Templatu nasatavuji v ``addColumnCallback`` protože si do ní potřebuji předat proměnnou, která má hodnotu dle řádku.

**Comment by daihousl** [comment]
@paveljanda Problém je v tom, že když si v šabloně dumpnu definované proměnné, tak v ``$control``, potažmo ``$_control``, není má komponenta, ale Ublaboo\DataGrid\DataGrid.

Takže odkazy ve vlastních templatách nejdou tvořit přes ``n:href`` nebo ``{link}``, ale musím použít toto:
``href="{$control->getParent()->link('myHandle!')}"``

**Comment by paveljanda** [comment]
Jaké používáš Nette? 2.4 je stále jen jako RC (už je RC6?) a dokud nebude stable, nebudu to řešit. RC1, RC2 a RC3 datagrid rozbily.

Ten link v action by ale měl fungovat.. Třída `Action` zkouší udělat link na grid a pak na presenter: https://github.com/ublaboo/datagrid/blob/master/src/Column/Column.php#L662-677

**Comment by daihousl** [comment]
@paveljanda Jedu na poslední Nette 2.3 a tvůj grid také poslední verze.

**Comment by paveljanda** [comment]
Během pár minut pushnu novou verzi. Dal jsem si do action link na presenter (`something!`) a v presenteru jsem měl metodu `handleSomething()` a vše funguje..

Můžeš poslat ukázkovou factory datagridu?

**Comment by paveljanda** [comment]
@daihousl Stále ti to nefunguje?

**Comment by ikeblaster** [comment]
@paveljanda Narazil jsem na tento problém v aktuální verzi 6.2.5 (nette 3.0.2) ve spojení s Multiplier. Ale v podstatě mi přijde, že to musí být obecnější problém.

`->addAction('toggleLeagueWebVisible!')`

`Invalid link: Unknown signal 'toggleLeagueWebVisible', missing handler Nette\Application\UI\Multiplier::handletoggleLeagueWebVisible()`

**Workaround do vyřešení** - dejte před to dvojtečku, tj. `:toggleLeagueWebVisible!`. Bohužel jsem si podědil Action, vytáhl href a chtěl použít jinde, kde se s tímhle formátem nepočítalo.

---

Problém je, že `$targetComponent->link` (volá se ve fci `\Ublaboo\DataGrid\Traits\TLink::createLink`) může probublat do `\Nette\Application\UI\Presenter::handleInvalidLink`, který pak zavolá `trigger_error` a to už se nepovede nijak odchytit. Nette ale umožňuje toto chování ovlivnit přes public property `$invalidLinkMode`.

Jaká je vůbec logika za tímhle hledáním do hloubky? Každá komponenta má v sobě odkaz na presenter, ne? Může být zanořeno více presenterů do sebe? Nějak mě nenapadá use case, ale pokud fakt existuje, tak by dávalo smysl toto (tj. nastavit chování presenteru a pak vrátit zpět uvnitř toho `createLink`):

```
$originalInvalidLinkMode = $targetComponent->getPresenter()->invalidLinkMode;
$targetComponent->getPresenter()->invalidLinkMode = Presenter::INVALID_LINK_EXCEPTION;

try {
	$link = $targetComponent->link($href, $params);

} catch (InvalidLinkException $e) {
	$link = false;
} catch (Nette\InvalidArgumentException $e) {
	$link = false;
}

$targetComponent->getPresenter()->invalidLinkMode = $originalInvalidLinkMode;
```

Můžu poslat PR, pokud to dává smysl.

**Comment by matronator** [comment]
@paveljanda Hlásím úplně stejný problém v 6.7.1. Chci vytvořit odkaz v šabloně, kterou nahrávám přes `addColumn(...)->useTemplate('template.latte')`. Metodu `handletoggle` (další problém, že se automaticky nezmění case: `toggle` =\= `handleToggle` ale `handletoggle`) mám definovanou přímo v komponentě DataGridu. Zkoušel jsem všechny možný způsoby vytvoření odkazu, ale všechny hlásí:

```
Invalid link: Unknown signal 'toggle', missing handler Ublaboo\DataGrid\DataGrid::handletoggle()
```

Zajímavé ale je, že odkazy dělané v komponentě přes `addAction` se vytvoří správně...
