### ISSUE TITLE
FilterText - Hledání dle celého stringu

### ISSUE THREAD

**Issue by daihousl** [ublaboo/datagrid#262]
Šlo by přidat to ``setTextFilter()``, který by určil zda se má hledané slovo dělit dle mezer (aktuální chování) a nebo hledat celý string v kuse?
Případně nějaký super přemínač přímo v hlavní třídě..
Bylo by to super. :)
@paveljanda

**Comment by paveljanda** [comment]
Dobrej nápad. Přidám.

**Comment by FilipNovy** [comment]
@paveljanda Ahoj. Šlo by to prosím dostat do nejbližší možné verze? Tohle mi hrozně schází a nemůžem tuto změnu nasadit. Díky moc.

**Comment by FilipNovy** [comment]
@paveljanda Díky už je to v kodu. Nahodíš prosím nový tag, release. :)

**Comment by paveljanda** [comment]
V4.4.4
