### ISSUE TITLE
Notifikace po události

### ISSUE THREAD

**Issue by luke82** [ublaboo/datagrid#263]
Otázka trochu mimo mísu... Jak jsou dělané na stránce s examplem datagridu ty notifikace, které vyjedou z vrchní části stránky po dokončení nějaké události v gridu?

$presenter->flashMessage('Custom callback triggered, id: ' . $item_id);
$presenter->redrawControl('flashes');

Co je obsahem snipperu flashes?
Díky

**Comment by paveljanda** [comment]
Example handler:

```php
public function handleDelete($id)
{
	$this->flashMessage("Item deleted [$id] (actually, it wasn't)", 'info');

	if ($this->isAjax()) {
		$this->redrawControl('flashes');
	} else {
		$this->redirect('this');
	}
}
```

**Comment by paveljanda** [comment]
Obsah flashmessage si lze prohlédnout v ajax response.

**Comment by luke82** [comment]
Díky, už funguje.
