### ISSUE TITLE
Action confirm needed but without ajax request

### ISSUE THREAD

**Issue by zemnet** [ublaboo/datagrid#264]
Hi,
all work well with class ajax, but I need confirm without ajax request,
how can I do it?

thank you.

**Comment by paveljanda** [comment]
```php
$grid->addAction('delete', '', 'delete!')
	->setClass('btn btn-xs btn-danger ajax')
	->setConfirm('Do you really want to delete %s?', 'name');
```

**Comment by zemnet** [comment]
Thank you,
but I need to send request not over ajax,
but confirm dont work without ajax class.
And ajax class is in nette for ajax request, or not?

**Comment by paveljanda** [comment]
Sorry, i forgot to remove the ajax class:

```php
$grid->addAction('delete', '', 'delete!')
    ->setClass('btn btn-xs btn-danger')
    ->setConfirm('Do you really want to delete %s?', 'name');
```

The confirmation dialog should work also with non-ajax rq: https://github.com/ublaboo/datagrid/blob/master/assets/dist/datagrid.js#L3-8

What version do you use?

**Comment by zemnet** [comment]
in composer I have ^2.2

**Comment by paveljanda** [comment]
:) Can you please try 4.2.x?

**Comment by paveljanda** [comment]
There are release notes:

2.3: https://forum.nette.org/cs/25444-ublaboo-datagrid-mocny-rychly-rozsiritelny-hezky-anglicky-dokumentovany-datagrid?p=3#p171227

3.0: https://forum.nette.org/cs/25444-ublaboo-datagrid-mocny-rychly-rozsiritelny-hezky-anglicky-dokumentovany-datagrid?p=4#p171796

3.2: https://forum.nette.org/cs/25444-ublaboo-datagrid-mocny-rychly-rozsiritelny-hezky-anglicky-dokumentovany-datagrid?p=5#p173234

3.3: https://forum.nette.org/cs/25444-ublaboo-datagrid-mocny-rychly-rozsiritelny-hezky-anglicky-dokumentovany-datagrid?p=5#p173250

4.0: https://forum.nette.org/cs/25444-ublaboo-datagrid-mocny-rychly-rozsiritelny-hezky-anglicky-dokumentovany-datagrid?p=6#p173917

4.1: https://forum.nette.org/cs/25444-ublaboo-datagrid-mocny-rychly-rozsiritelny-hezky-anglicky-dokumentovany-datagrid?p=6#p174556

4.2: https://forum.nette.org/cs/25444-ublaboo-datagrid-mocny-rychly-rozsiritelny-hezky-anglicky-dokumentovany-datagrid?p=7#p174951

**Comment by zemnet** [comment]
Thank you, all work well, 
sorry , I am new in nette...

**Comment by paveljanda** [comment]
👍
