### ISSUE TITLE
treeview (v4.2) - Undefined variable: item

### ISSUE THREAD

**Issue by luke82** [ublaboo/datagrid#265]
Aktualizoval jsem přes composer na verzi 4.2 (z verze ^2.3) a přestaly v tree-view fungovat "addAction" v kombinaci s template (bez template vše funguje jak má).

Následující chyba se objeví vždy, když vložím tlačítko s template např.:
$grid->addAction('icon_delete', 'Smazat')->setTemplate(dirname(__DIR__).'/templates/kategorie/icon_delete.latte', ['']);

![image](https://cloud.githubusercontent.com/assets/213957/15987473/db99ba52-3029-11e6-994d-47fcf8ca87a6.png)

Nenapadá Vás, kde může být chyba?
Díky.

**Comment by paveljanda** [comment]
Díky za report, vyjde v další verzi.
