### ISSUE TITLE
Inline edit - refresh celého gridu

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#268]
Je možné znovunačítať celý grid po inline úprave jednej položky?

Ak dám invalidovať ```tbody```, načíta mi to iba upravený riadok - nie všetky.

**Comment by JakubKontra** [comment]
Jaký je use-case? :)

**Comment by romanmatyus** [comment]
Mám grid so zoznamom pobočiek. Jedna z nich je hlavná. Ak prestavím novú na *hlavnú*, pôvodná *hlavná* je v modeli degradovaná na obyčajnú pobočku. Nedarí sa mi refreshnúť riadok s *degradovanou* pobočkou.

**Comment by paveljanda** [comment]
http://ublaboo.org/datagrid/edit#on_custom_redraw

**Comment by romanmatyus** [comment]
@paveljanda Veľmi pekne ďakujem ;) Toto som prehliadol.
