### ISSUE TITLE
Výchozí řazení není možné nastavit na sloupec, který v gridu není

### ISSUE THREAD

**Issue by daihousl** [ublaboo/datagrid#269]
Z jakého důvodu tato možnost dostupná v 4.2.5 byla odstraněna v 4.3.1?
@paveljanda

**Comment by paveljanda** [comment]
Úplně nechápu, co teď je a co má být. :D

**Comment by daihousl** [comment]
V 4.2.5 šlo použít ``$grid->setDefaultSort(['id' => 'DESC']);`` ikdyž sloupec id vůbec v gridu nebyl.
Ve 4.3.1 už to nejde. Dostaneš error https://github.com/ublaboo/datagrid/blob/master/src/DataGrid.php#L691

**Comment by paveljanda** [comment]
A tobě se to zná jako špatný krok? Nedává přeci smysl, aby byl default sort na sloupci, které neexistuje.

**Comment by daihousl** [comment]
Smysl to dává, ale občas se výchozí nastavení hodí mít na sloupec, který v gridu není.
Např při registracích mě nezajímá id, ale rád bych měl nejnovější nahoře a zároven měl možnost vyhledávat.

**Comment by paveljanda** [comment]
Hmmmm. To mě vůbec nenapadlo.

Přesto však musím trvat na stávající verzi.

Pro tvůj případ stačí když nastavíš `order by` data sourcu, je to tak?

**Comment by daihousl** [comment]
Ok, to by šlo :)
Jen mě to zarazilo, tak jsem to raději hlásil. Snad to nevadí.
