### ISSUE TITLE
Group action column dissapers when all rows are disabled

### ISSUE THREAD

**Issue by kravcik** [ublaboo/datagrid#270]
![image](https://cloud.githubusercontent.com/assets/10499130/16116548/e90031d8-33cd-11e6-8382-76f8d58ddb66.png)

Cell should stay "empty" and generate this even when row arent avaible for group action:
`<td class="col-checkbox"></td>`

**Comment by dakorpar** [comment]
I believe it's only wrong that in header row there's still checkbox, group action checkbox shouldn't be displayed if there's no group actions available on rows.

**Comment by kravcik** [comment]
@dakorpar: You are right. Maybe some redraw on filter change should be enough.

**Comment by paveljanda** [comment]
Well, that is a situation. I don't want to redraw the header snippet when filtering (filter input could lost it's focus). What should i do with that?

**Comment by kravcik** [comment]
When testing if group action exist - grid should know if group action was set and its empty or its empty and not was set.

`<th n:if="$hasGroupActionOnRows" rowspan="2" class="col-checkbox">`

silly suggest that in addGroupAction() function add some class var groupActionSet:

`<th n:if="$hasGroupActionOnRows && $groupActionSet" rowspan="2" class="col-checkbox">`

**Comment by dakorpar** [comment]
@kravcik Could you describe how to reproduce the problem?

**Comment by kravcik** [comment]
@dakorpar: Add group action. Set select filter on other column, options A & B. A has allowed group action, B hasn't. If you pick only B in filter - no record has checkbox column.

Btw: Refresh page fix the problem.

**Comment by dakorpar** [comment]
@paveljanda What do you think about adding snippet to header row only
`<tr n:snippet="header-row" n:block="header">`
in datagrid.latte instead of 
`<tr n:block="header">`
and redraw only header row there instead of whole header?

**Comment by paveljanda** [comment]
@dakorpar That would still redraw filter inputs and lose input focus. Right?

**Comment by dakorpar** [comment]
@paveljanda true, I'm using outer filters so I don't have this issue :/
but it shouldn't be hard to put this into two rows, so filters are in seperate row, and then it would be possible to refresh only row with column titles.

**Comment by paveljanda** [comment]
@dakorpar You can not redraw column titles. There are also links for sorting data in table below. And you have to redraw these links..

**Comment by paveljanda** [comment]
The main subject of this issue does not appear anymore, closing ti.
