### ISSUE TITLE
FilterResetButton - add it to filters when outer rendering is on

### ISSUE THREAD

**Issue by george-oakling** [ublaboo/datagrid#274]
When we have more filters and use them with outer rendering, the original position of reset filters is down the grid and not optimal. It would be great to have an option to add FilterReset button directly to the list of filters. And maybe make a possibility to hide/show/toggle outer filters by clicking a special button.

**Comment by paveljanda** [comment]
You can send a PR. :)

**Comment by george-oakling** [comment]
I'll try, the problem I see right now, is that the outerFilters snippet is not updated on AJAX request...

**Comment by paveljanda** [comment]
On which ajax rq? It should not be redrawn when filtering.

**Comment by george-oakling** [comment]
I am trying to add the reset button to the toolbar, but...when the filters are reset, the button still hangs at the toolbar till the next manual refresh, because the toolbar is not updated after initiation of AJAX filters.

**Comment by paveljanda** [comment]
Right. Well, maybe the best solution would be creating your own template in your app.
