### ISSUE TITLE
Multi action column

### ISSUE THREAD

**Issue by fvozar** [ublaboo/datagrid#276]
Is there a way to define column with multiple action - like status dropdown, but with actions? It could be useful when there is too many actions in grid and some can be "hidden" in that dropdown.

Thanks.

**Comment by paveljanda** [comment]
There is not. But you can send a PR. :)

**Comment by fvozar** [comment]
Sure, but first I have to look more into datagrid code. Thanks for reply

**Comment by paveljanda** [comment]
I won't implement that. If you want to by yourself, you can send a PR anytime.

Closing this issue.
