### ISSUE TITLE
Unchecked checkbox after redraw Datagrid

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#277]
Ahoj Pavle, mám takový problém a rád bych na to znal tvůj názor.
Mám datagrid, kde každých 30 sekund provádím překreslení snippetu tbody. 
Problém je, že na tabulce používám group action. Jednoduše se mi po uběhnutí 30 sekund vlivem redrawcontrol odškrtnou vybrané rows. Existuje nějaký způsob jak tohle eliminovat? Případně navrhnout nějaké řešení, třeba ukládat stav checkboxů do session?

Díky moc

**Comment by paveljanda** [comment]
No, to je trošku neřešitelná situace, z principu..

Z jakého důvodu to každých sekund překresluješ? Opravdu se to každých 30 sekund mění, nebo to je ve skutenčnosti potřeba jen občas?

**Comment by misaon** [comment]
Jedná se o tiketovací systém, který si každých 30 sekund z IMAP serveru vyžádá novou poštu a na základě toho nastaví datagridu datasource a překreslí jej.

**Comment by paveljanda** [comment]
Hm, nativní řešení zde asi nebude.

Být tebou, implementuji nějakou funkcionalitu, která bude v zásadě hlavně v JS a bude "prepend"-ovat nově načtené tickety na začátek datagridu. Nic se však nebude překreslovat kompletně. Proč takto:
1, Pokud zaškrtneš poslední záznam na stránce, stejně by se ti ztratil, kvůli stránkování. Takto ti tam zůstane.
2, Nebudeš muset řešit nic přes session, prostě zůstane staré html, jen přibude nové.

**Comment by misaon** [comment]
Počítám tedy že se to nemůže stát unikátní vlastností Ublaboo? :smile: 
Né, chápu že to asi nepůjde do Datagridu implementovat, ale díky za tipy a tvůj čas.

**Comment by misaon** [comment]
Tak jsme to zatím "vyřešili" tak, že když je alespoň jeden checkbox zaškrtlý, překreslovat se nebude.
Je to takové provizorní do té doby než na něco přijdem.

Kdyby tě v průběhu něco napadlo, byl bych rád, zatím díky :+1:
