### ISSUE TITLE
Tree-view: Chyba zoraďovania

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#28]
Nie je možné presunúť položku na prvú/poslednú pozíciu vo vnorenom zozname.

![snimka obrazovky z 2016-01-28 00 14 13](https://cloud.githubusercontent.com/assets/1110294/12631911/8a1968e8-c554-11e5-825d-999e3257568e.png)

**Comment by romanmatyus** [comment]
Beriem späť. Je to možné, iba je veľmi ťažké sa trafiť.

**Comment by paveljanda** [comment]
Tohle z nějakého důvodu hodně blbne, vím o tom - je to na pořadu dne.
Možná nahradím jQuery sortable něčím jiným.

**Comment by romanmatyus** [comment]
*Budem strašne happy keď ten treeview nejak vymyslíte. Idem robiť komponentu na ACL s dedičnosťou a veľmi rád by som na to použil tento datagrid. Vyzerá to super ;)*

**Comment by paveljanda** [comment]
Solved.
