### ISSUE TITLE
Fit column width method

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#282]
Ahoj,
poslední dobou v Datagridu často využívám metodu addAttributes pro přidání CSS classy ke sloupci.
V podstatě se jedná o to, aby se šířka sloupce zmenšila na minimální možnou v závislosti na obsahu buňky. Ve výsledku potom sloupec pro datum nemá 500px ale třeba jen 80px. Napadlo mě, že by i ostatní ocenili, kdyby v datagridu tato možnost byla. Byla by classa **col-fit** a jejím obsahem bylo:

```
.col-fit {
   width: 1%;
   white-space: nowrap;
}
```

Podobně jako addAttributes by existovala metoda **setFitContent** (true/false) a na základě toho by se ke sloupci přihodila ona classa **col-fit**.

Díky

**Comment by misaon** [comment]
#321

**Comment by paveljanda** [comment]
Thanks for the PR, closing this issue.
