### ISSUE TITLE
removeColumn not work, when I use setColumnsSummary

### ISSUE THREAD

**Issue by zemnet** [ublaboo/datagrid#284]
Hi,
I cannot remove column, what I use in columnSummary.

Thank

**Comment by paveljanda** [comment]
I do not understand that. It does work in docu website...
![summary](https://cloud.githubusercontent.com/assets/1488874/16715479/0906e096-46e1-11e6-9cbe-0e4546e1b2d3.gif)

**Comment by zemnet** [comment]
Sorry, not hide, but column removing in php code... $grid->removeColumn('col')

**Comment by paveljanda** [comment]
How can be there a columns summary for NO column?

**Comment by zemnet** [comment]
Yes, this is good question :) In grid factory I create main grid, width default columns and default summarys. On other place, presenter, where I use this factory, I must remove some columns for user roles or other reasons....In other presenter I use it with defaults.
I have replaced logic in creation of this grid, no problem, when you will not change, what have bigger priority....

**Comment by paveljanda** [comment]
I am sorry, but the summary has to sit on some columns. And datagrid has to notice user that there is no column, where user wants to have the summary.

Na i close that issue if you are fine with some other solution?

**Comment by zemnet** [comment]
ok, you can close it.
thanks...

**Comment by zemnet** [comment]
Only for information, I have declared column X, after that I create summary for X, and for the last I will remove column X, I dont need summary for X :+1:

**Comment by paveljanda** [comment]
Yes, i tried exactly that:

```php
$grid->addColumnText('id', 'Id');

$grid->setColumnsSummary(['id']);

$grid->removeColumn('id');
```

But that would be exactly that same as this simple snippet of code:

```php
$grid->setColumnsSummary(['id']);
```

And that would be wrong.. Do you agree with me?

**Comment by zemnet** [comment]
`class Factory {
$grid->addColumnNumber('suma', 'Suma');
$grid->setColumnsSummary(['suma']);
return $grid;
}
`

`class Presenter {
 $grid = inject fatory;
 if(!user->isAllowed(doverne))
  $grid->removeColumn('suma');
}
`

But no problem, I have changed the logic, thank you...
PS: grid is No.1, very good work...
