### ISSUE TITLE
$grid->addAction() nerenderuje popisek tlacitka

### ISSUE THREAD

**Issue by hurycz** [ublaboo/datagrid#289]
tlacitko se vygeneruje bez textu:
`$grid->addAction('id', 'Edit', 'edit');`

vygeneruje:
`<a href="..." text="Edit" class="btn btn-xs btn-primary"></a>`

**Comment by paveljanda** [comment]
Změnil jsem composer.json - nyní je třeba `nette/utils` ve verzi 2.3.10 a větší.
