### ISSUE TITLE
Tree-view: Informácie o poradí sú nedostatočné

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#29]
Jedno úrovňový zoznam
--------------------------------
Odosielané informácie sú zbytočne príliš rozsiahle.

Metódou *drag&drop* sa vždy presúva presne jedna položka. Z toho dôvodu stačí odoslať primárny kľúč presúvanej položky a primárny kľúč položky pred ňou, nie je nutné odosielať poradie celého zoznamu.

Tree-view
-------------
V prípade tree-view sú informácie o presune položiek nedostatočné. Nezohľadňujú zanorenie.

Ako z toho von
-------------------

Ideálne si predstavujem odosielať ako parametere:

- `sort-id`: Primárny kľúč presúvanej položky. Odosiela sa vždy.
- `sort-parent`: Primárny kľúč rodiča. Odosiela sa ak je položka zanorená v strome na inej ako prvej úrovni.
- `sort-before`: Primárny kľúč predchádzajúcej položky. Odosiela sa vždy ak nie je položka prvou v danej vetve.

Takto by bolo možné na strane servera upraviť poradie podla potreby s minimálnym množstvom prenášaných informácií, ale s dostatočnými informáciami pre určenie presnej polohy.

**Comment by paveljanda** [comment]
Ad 1, Souhlasím. Na druhou stranu spousta lidí je již zvyklá na tento způsob. A ty informace se mohou hodit. Navíc je to jenom pár bajtů, které se odesílají navíc. Zrovna toto bych tak ponechal. Ještě nad tím zapřemýšlím.

Ad 2, Naprostý souhlas. Zatím jsem neřešil kompletní ajax payload pro tree view, protože ještě není dořešený sorting, co se týče UI. Dávám prioritu.

**Comment by romanmatyus** [comment]
1.) Je to možno bežné, otázne je, či je to správne. Nenapadá mi use-case, kedy sa môžu tie informácie hodiť.
**Argumenty za:**

- Zhodné správanie sa v prípade tree-view aj jedno úrovňového zoznamu.
- Bolo by možné spracúvať zoznamy  maximálne 192 položiek, aj to za ideálnych podmienok najkratších možných numerických kľúčov.

```php
$s = '?do=sort';
$i = 1;
do {
	$s .= '&sort[]=' . $i++;
} while (strlen($s)<2000);
var_dump($i);
```

URL vraj môžu mať maximálne 2000 znakov. [zdroj](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers)

**Comment by paveljanda** [comment]
Asi  neobhájím aktuální řešení. Dávám ti za pravdu.

**Comment by romanmatyus** [comment]
*Klobúk dolu, vzácne!*

**Comment by paveljanda** [comment]
Done. Všechny tree view věci vyjdou v přístí verzi. Počítám do sobotní noci. :)
