### ISSUE TITLE
FilterSelect: 0 is not set into url

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#293]
```php
$grid->addFilterSelect('isOwned', 'client.stock.isOwned', [
	NULL => '',
	0 => 'No',
	1 => 'Yes'
]);
```

This code will work as expected, but when you select second option with key 0, it wont be added to Url and on refresh it does not apply this filter.

Zero should be accepted as valid value.

**Comment by juniwalk** [comment]
You're the best! Thanks!

**Comment by juniwalk** [comment]
@paveljanda Looks like the value is still not added into Url when the value is selected in filter. It does add it when going through pages though.

**Comment by paveljanda** [comment]
@juniwalk Do you have the latest version of assets? It work for me..

**Comment by juniwalk** [comment]
@paveljanda I am on version 4.4.7 which should have the fix, right?

**Comment by paveljanda** [comment]
Right. Can you create a little sandbox-like project with same functionality and send it to me?

**Comment by juniwalk** [comment]
@paveljanda Sorry too lazy to do new web with dumb down version, I tried to do it in my other project and that did not work either.

I went on and checked your commit and there is something odd. You've modified *.coffie script but there is no change in dist directory. I am using files from dist.

**Comment by paveljanda** [comment]
Argh! A didn't compile JS! Sorry, will do that.

**Comment by paveljanda** [comment]
4.4.9

**Comment by juniwalk** [comment]
@paveljanda Great! Thanks! :)
