### ISSUE TITLE
[BUG|ERROR] Select filter after update 4.3 => 4.4.6

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#294]
Zdarec, po update na verzi 4.4.6 mi přestaly fungovat select filtry (viz. screen).

![bug](https://cloud.githubusercontent.com/assets/15806356/17055757/2f686aa2-500f-11e6-9d2b-0bbc104531fa.png)

**Comment by misaon** [comment]
Na verzi 4.3 (kam jsme se proteď vrátili) filtry fungují tak jak mají.

**Comment by mafikes** [comment]
Stejný problém :( 4.4.3 funguje.

**Comment by paveljanda** [comment]
VIz  #297
