### ISSUE TITLE
FilterMultiSelect: Invalid condition building for Doctrine?

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#295]
Hi,
I just wanted to ask, shouldn't the condition for MultiSelect in Doctrine data source be build something like this?

```php
$qb->andWhere($qb->expr()->in('o.status', ':status'))
	->setParameter('status', $values);
```

Current implementation is problematic for string values.
```
[Semantical Error] line 0, col 115 near 'active OR o.status': Error: 'active' is not defined.
```

**Comment by juniwalk** [comment]
If you want I can send PR. :)

**Comment by paveljanda** [comment]
Ah.

That would be great!
