### ISSUE TITLE
Bug: změna hodnot ve filtru selectlist

### ISSUE THREAD

**Issue by xnukes** [ublaboo/datagrid#297]
Pokud má datagrid zapnuté pamatování hodnot ve filtru - setRememberState a ve filtru selectlistu se změní hodnoty, tak pak je vyhodnocena chyba že nelze najít záznam s předchozím klíčem. Chtělo by to testovat zdali se nezměnily položky v selectlistu.

**Comment by misaon** [comment]
#294

**Comment by xnukes** [comment]
To je jiná chyba, viz screen.
![image](https://cloud.githubusercontent.com/assets/20656316/17128042/4c608678-530a-11e6-9ccb-975ed13a2e41.png)
