### ISSUE TITLE
inlineEdit, inlineAdd addSelect set class to selectpicker

### ISSUE THREAD

**Issue by pitr82** [ublaboo/datagrid#299]
Ahoj, 
při inlineAdd resp. inlineEdit  používám select a neumím mu přes setAttribute nastavit class na selectpicker

**Edit: ještě jeden posttřeh. 
Když použiji multiselect v ItemsDetail, tak se mi nezobrazí zaškrtávací fajfky. 
Ale když jej použiji ve filtru, tak se již správně vykreslí i v itemsDetail.**

**Comment by misaon** [comment]
Hoď sem nějaký příklad tvého kódu.
Pokud se ti nezobrazují ikony, je dost možné, že v hlavičce stylů nemáš načtenou knihovnu FontAwesome.

**Comment by paveljanda** [comment]
1) Do verze 4.4.8 jsem dal fix těch tříd. Nyní se nenastavují v šabloně (kde přebily jakékoliv předchozí nastavení), ale v eventu třídy `InlineEdit`. Stačí tedy klasicky tekto:

```php
$grid->addInlineAdd()
	->onControlAdd[] = function($container) {
		$container->addSelect('name', '', ['foo', 'bar'])
			->setAttribute('class', 'foo');
	};
```

**Comment by pitr82** [comment]
@misaon 
Samozřejmě Font awasome mám nalinkovaný v layoutu. Jinak by se mi nezobrazovaly ikony
<link rel="stylesheet" type="text/css" href="{$basePath}/bower_components/font-awesome/css/font-awesome.min.css">
Když použiju select ve filtrech - načte se se stránkou tak se zobrazi i fajky v selectu detailu, který se posílá ajaxově. jako by se načetl css z filtru. Pokud nemám select ve filtrech, tudíž jako první se inicializuje v detailu (javascriptem) nezobrazí se mi fajfky. Když si projedu prvek css, opravdu na něm není použit font awasome....

**Comment by pitr82** [comment]
@misaon @paveljanda,
**V detailu se mi nezobrazí fajfky, a taky mi nejde nastavit class pro inline ADD, EDIT.** -Co mám špatně ?
komponenty aktuální přes bower
ublaboo/controls - v1.0.2
ublaboo/datagrid -  dev-master c205bc5 
ublaboo/responses  -  v1.0.4
  
Componenta:
`
public function createComponentDataGrid($name)
	{
	    $grid = new DataGrid($this, $name);
	    $grid->setDataSource([['id' => 1, 'name' => 'John'], ['id' => 2, 'name' => 'Joe']]);
	    $grid->addColumnText('id', 'Id');
	    $grid->addColumnText('name', 'Name');
	    $grid->addInlineEdit()
		->onControlAdd[] = function($container) {
		$container->addText('id', '');
		$container->addSelect('name', '',['foo', 'bar'])
			->setAttribute('class', 'form-control input-sm selectpicker');
	    };

	    $grid->getInlineEdit()->onSetDefaults[] = function($container, $item) {
		$container->setDefaults([
		'id' => $item['id']]);
	    };
	    $grid->addInlineAdd()
		->onControlAdd[] = function($container) {
		$container->addText('id', '')->setAttribute('readonly');
		$container->addSelect('name', '',['foo', 'bar'])
			->setAttribute('class', 'form-control input-sm selectpicker');
	    };
	    $grid->getInlineAdd()->onSubmit[] = function($values) {};
	    $grid->setItemsDetail();
	    $grid->setTemplateFile(__DIR__ . '/itemsDetail.latte');
	    $grid->setItemsDetailForm(function(Nette\Forms\Container $container) {
		    $container->addText('id');
		    $container->addMultiSelect('name', '', ['foo', 'bar']);
		    $container->addSubmit('save', 'Save')
			    ->onClick[] = function($button) {};
	    });
	    return $grid;
	    }
`

Detail latte:
`
{extends $original_template}

{block detail}
	
	{formContainer items_detail_form-$item[id]}
		<div class="form-group">
			    <div class="col-sm-4 ">
				 <input n:name="id" class="form-control input-sm" value="{$item['id']}"/>
			    </div>
			    <div class="col-sm-2 ">
				 <select n:name="name" class="form-control input-sm selectpicker" />
			    </div>
		</div>
		<div class="form-actions pull-right">
			    <button n:name=save type="submit" class="btn btn-primary btn-sm">Upravit </button>
		</div>
	{/formContainer}
   
{/block}
`

**Comment by paveljanda** [comment]
@pitr82 Úplně to nechápu. Místo třídy `glyphicon glyphicon-ok` máš z nějakého důvodu na té ikoně třídu ` glyphicon-ok check-mark`. Úplně nevím, kde měníš ten prefix.

A třídu si přepisuješ v šabloně itemDetail.late.

**Comment by pitr82** [comment]
@paveljanda 

ItemDetail: selectpicker si přepíšu v šabloně, ale taky nevím, kde se přepisuje prefix, mám jen standartní styly pro grid.

ItemEdit: selectpicker se nenastaví, přepisuje se v šabloně [datagridu](https://github.com/ublaboo/datagrid/blob/master/src/templates/datagrid.latte#L226)

**Comment by paveljanda** [comment]
@pitr82 Aha, upravil jsem tu šablonu..

Ale s tím prefixem je to vážně podivné. By default datagrid používá `fa fa-`. Kde se tam bere glyphicon je mi záhadou.

**Comment by pitr82** [comment]
@paveljanda  
U inlineAdd se multiSelect zobrazí správně,
U UnlineEdit a ItemsDetails jsem zjistil, že se nenačte :

bootstrap.css
 /* Řádka 269 */
.glyphicon
{
  position: relative;
  top: 1px;
  display: inline-block;
  font-family: "Glyphicons Halflings";
  font-style: normal;
  font-weight: normal;
  line-height: 1;
}

**Comment by pitr82** [comment]
Už vím, kde se to maže:
[iconBase](https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L323) se naplni.
Viz. generování [tady](https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L542)

A [tady](https://github.com/ublaboo/datagrid/blob/master/assets/dist/datagrid.js#L539) se smaže iconBase.

Jak to mám tedy použít, aby se to generovalo správně?

**Comment by paveljanda** [comment]
VIz http://ublaboo.org/datagrid/ :

`DataGrid::$icon_prefix = 'fa fa-';`
