### ISSUE TITLE
Tree-view: Rozbalovanie prázdnych položiek

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#30]
Mám položku, ktorá má v sebe zanorené ďalšie položky.

Ak z nej vyhádžem všetky podpoložky, stále zostane rodič s rozbalovacím tlačidlom.
![snimka obrazovky z 2016-01-28 00 40 13](https://cloud.githubusercontent.com/assets/1110294/12632369/b87511e4-c557-11e5-83da-3cac30084b8e.png)

**Comment by paveljanda** [comment]
Interní poznámka: je to možné udělat dvěma způsoby:

1, Buď si v sortícím handleru v presenteru programátor vyselektí z databáze 2 změněné položky (předchozí rodič, aktuální rodič), nastaví tuto selekci jako datasource gridu a překreslí dynamické snippety jménem item-X ($grid->redrawControl('items');) - tím se překreslí tedy předchozí rodič a aktuální rodič

2, a nebo to přidám do JS, aby to prostě fungovalo (což stejně nakonec udělám).

**Comment by paveljanda** [comment]
Done. Vtipnější bude to přidávání. Ale to je v jiném issue.

**Comment by romanmatyus** [comment]
V deme to zatiaľ nie je.

**Comment by romanmatyus** [comment]
OT: Kde sa vlastne nastavuje *sortable*? Asi som slepý, ale v zdrojáku [dema](http://ublaboo.paveljanda.com/datagrid/tree-view) to nevidím.

**Comment by paveljanda** [comment]
Refresh.

$grid->setSortable()

**Comment by romanmatyus** [comment]
Už by to tam malo byť?

**Comment by paveljanda** [comment]
Ono je to v dokumentaci předtím, tuším u akcí. Vlastně bych to mohl dát i sem. Vůbec u tree view bych měl přidat do docu ještě nějaké info. uvidíme, kdo bude co potřebovat. Ale něco tam něště dopíšu.

**Comment by paveljanda** [comment]
Jojo, už mi to jede i venku.
