### ISSUE TITLE
[QUESTION] Inline edit is with HTML tags

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#302]
Ahoj,

jde nějak řešit problém s inline editací v případě když si do metody **setRender** hodíš nějaké vlastní HTML značky? Příklad:

```
        $grid->addColumnLink('subject', 'Název')
            ->setRenderer(function ($item) {
                $linkToTicket = $this->link('Ticket:show', ['id' => $item->id]);
                return Nette\Utils\Html::el('a')->addAttributes(['class'=>'bold')->href($linkToTicket)->setText($item->subject);
            })
            ->setEditableInputType('text')
            ->setEditableCallback([$this, 'changeTicketSubject'])
            ->setFilterText();
```

Při inline editaci ti tento příklad vyhodí text input s hodnotou `<a href="...">...</a>` .
Potřeboval bych ale, aby se zobrazil **jen obsah** HTML "a" tagu. To samé když řeším bold, underline apod., jasně, můžete to řešit na straně stylů, ale např. u "a tagů" to přes styly řešit nelze.

Jde to řešit?

**Comment by juniwalk** [comment]
Nevím jak to řešit tady s tím inline editem, osobně mám raději velký inline edit, kde si sám složím form a mám jistotu že při editaci uvidím jen input a hodnotu co mu pošlu.

**Comment by paveljanda** [comment]
RFC: Hm, toť otázka. Rozumím dotazu a přemýšlím, jak to udělat. Aspekty situace:

Mohu poskytnout buňce tabulky nějaký data-atribut, kde bude něco jako `data-inline-edit-value`. Jako inline edit value se bude ukládat skutečná hodnota sloupce, která se zobrazí v inputu malé editace.

Musel by se však vymyslet mechanismus, který by tam tu hodnotu nastavoval, protože custom renderer tam si uživatel vymyslí pravděpodobně proto, že má vykreslovat něco **jiného**, než surová hodnota sloupce. Tedy nelze tuto surovou hodnotu mydlit do data-atributu rovnou.

Dělat další callback pro tuto hodnotu? Není lepší použít právě větší inline editaci?

-------------

Takže jsem na vážkách, zda aktuální implementaci vylepšovat něčím velkým, nebo odseknout pár (?) s tím, že mají použít velkou inline editaci.

**Comment by misaon** [comment]
Toť otázkou.. když jsme měnili ve sloupci např. cenu, kde byla custom renderem nastavena cena obalená boldem, small editaci vyskočilo <b>2150 Kč</b>. Podle mě je škoda kvůli změně ceny dělat celou velkou inline editaci.

**Comment by paveljanda** [comment]
Ano já jsem to pochopil. Teď si to musím nechat projít hlavou.

**Comment by paveljanda** [comment]
Prosím použít v takovém příapdě velký inline edit. Je robustnější a do budoucna bude ještě lepší. Malý inline edit je jednoduchý a rád bych, aby to tak zůstalo.
