### ISSUE TITLE
Multiselect not set filters when call via handle

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#306]
Když přes handle nastavíš `setFilter(['state' => ['OPEN', 'WAITING']])`. Datagrid se překreslí, ale v dropdown multiselectu nejsou fajfky u filtrovaných hodnot.

**Comment by misaon** [comment]
![a](https://cloud.githubusercontent.com/assets/15806356/17246886/3ceb6668-558f-11e6-8994-4706232bd3cd.png)

**Comment by misaon** [comment]
Také jsem si všiml, že při zapnutém setRemamber a zavoálním setFilter (přes handle) se hodnoty filtrů neuloží.

**Comment by paveljanda** [comment]
Mně to funguje bez problému, chybka bude pravděpodobně jinde.
```
public function handleFoo()
{
	$this['examplesGrid']->setFilter(['status' => [1]]);
	$this['examplesGrid']->redrawControl();
}
```

Postup: Přes handle jsem si nastavil filtr multiselect, vše ok, potom jsem filtroval přes další filtr. Vše bylo v session uloženo.

**Comment by misaon** [comment]
V tvém případě by ale nefungovala metoda reload() místo redrawControl(). 
Otázka, jestli by měla fungovat.
