### ISSUE TITLE
Filter select with NULL in index is ignored

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#307]
Via your filtrs i cant filter rows, where column value is NULL.
Can you fix it? Thanks.

**Comment by juniwalk** [comment]
@misaon I think `NULL` is used for clearing the filter. This could be a problem.

**Comment by misaon** [comment]
@juniwalk hm, generally when I need to select only rows without values, there is the problem ..

**Comment by juniwalk** [comment]
@misaon Well you could use empty string and write your own condition which would differentiate the two.

**Comment by misaon** [comment]
@juniwalk i know, but if you use method setFilter in handle, you cant set method setCondition..

**Comment by juniwalk** [comment]
@misaon I see, I don't use `setFilter`, I always use `$grid->addFilterSelect` :)

**Comment by misaon** [comment]
@juniwalk I talking about handles...

```
    public function handleChangeFilter()
    {
            /** @var Ublaboo\DataGrid\DataGrid $grid */
            $grid = $this['grid'];
            $grid->setFilter(['owner_name' => null]);
            $grid->reload();
    }
```

**Comment by paveljanda** [comment]
@juniwalk That method sets directly filter value.

@misaon Do not start issue label with these `[BUG]` notes, please. I will decide whether particular issue is bug or not.

NULL is a bit questionable. It could mean a string `"NULL"` in url.

**Comment by misaon** [comment]
@paveljanda ok

**Comment by juniwalk** [comment]
@misaon @paveljanda Oh I misunderstood, I haven't used this yet :D

**Comment by paveljanda** [comment]
Please use custom callback
