### ISSUE TITLE
Tree-view: Zanorenie do predvolene prázdnej položky

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#31]
Položku nie je možné zaradiť do inej položky, ktorá pri prvotnom renderi neobsahovala potomkov.

**Comment by paveljanda** [comment]
Done.

**Comment by romanmatyus** [comment]
Neviem otestovať, [demo](http://ublaboo.paveljanda.com/datagrid/tree-view) vracia 500.

**Comment by paveljanda** [comment]
Díky, fixed.
