### ISSUE TITLE
After upgrade jquery 2.2.4 to 3.1.0 don't show callendar 

### ISSUE THREAD

**Issue by pitr82** [ublaboo/datagrid#314]
![callendar](https://cloud.githubusercontent.com/assets/7237077/17320328/4eaf696a-5893-11e6-9cf9-8e63049f7f8e.png)

**Comment by juniwalk** [comment]
Thats because `bootstrap-datepicker` does not support jQuery 3. See its [bower.json](https://github.com/eternicode/bootstrap-datepicker/blob/master/bower.json)
