### ISSUE TITLE
Update nette 2.4 - ItemsDetail - FormContainer - Eror

### ISSUE THREAD

**Issue by pitr82** [ublaboo/datagrid#327]
Po upgradu na nette 2.4 mi vyhazuje chybu při vykreslení formuláře v ItemsDetail :
 

> end() expects parameter 1 to be array, null given

$this->global->formsStack[] = $formContainer = $_form = end($this->global->formsStack)["items_detail_form-$item[id]"];

**Comment by paveljanda** [comment]
@pitr82 Můžeš to prosím směrovat na forum/issues nette, potažmo latte? Tohle není kód datagridu, ale latte.

**Comment by dg** [comment]
In 2.4 it is needed to redraw snippet `gridSnippets`, ie. add `$this->redrawControl('gridSnippets');` here https://github.com/ublaboo/datagrid/blob/e6e446ddb5aba33cc8d6aba28db580bc7f180b53/src/DataGrid.php#L2074

**Comment by dg** [comment]
…or use workaround `$this->getTemplate()->getLatte()->addProvider('formsStack', [$this['filter']])` here https://github.com/ublaboo/datagrid/blob/e6e446ddb5aba33cc8d6aba28db580bc7f180b53/src/DataGrid.php#L495
