### ISSUE TITLE
Shortcut - remove filter

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#329]
I extend DataDrid for this feature. If I will send PR, it will be merged?

![snimka obrazovky z 2016-08-15 14 11 02](https://cloud.githubusercontent.com/assets/1110294/17664196/b1172818-62f2-11e6-850f-c9ab496dea03.png)

**Comment by misaon** [comment]
Iam for cross inside inputs :)

**Comment by romanmatyus** [comment]
@misaon I Agree, but it's UI problem with multiselect.

**Comment by misaon** [comment]
![abba](https://cloud.githubusercontent.com/assets/15806356/17664692/350d7084-62f6-11e6-9458-97d2f8432db2.gif)

Something like this?

**Comment by romanmatyus** [comment]
This it's possible too in currently used addon.
![image](https://cloud.githubusercontent.com/assets/1110294/17664764/a0826432-62f6-11e6-869a-802e43718b9c.png)

BUT, this it's not same as "remove filter"! I can set any option's as default.

And, this not solve UI inconsistency in input and (multi)select.
My suggested UI solves inconsistency and default options.

**Comment by paveljanda** [comment]
I like the idea, but i don't like the graphic concept. Have you any idea, where it can be displayed and not mess with the layout?

It can by hidden by default and shown on column hover, but still - some better concept would be better.

**Comment by romanmatyus** [comment]
What this?
![image](https://cloud.githubusercontent.com/assets/1110294/17682120/e3939cca-6349-11e6-9fcb-e6b520ebc3d7.png)

Of course, it be showed only after set by `->showResetFilter()`.

On hover it's bad for touch displays.

**Comment by paveljanda** [comment]
@romanmatyus What about `DataGrid::showPartialResetFilter()` instead of `::showResetFilter()`?

Yes, that looks better. I think it might look even better without the text. Just the crosses. And you know - pull them to the right side of the cell.

**Comment by romanmatyus** [comment]
@paveljanda Ok?
![image](https://cloud.githubusercontent.com/assets/1110294/17757178/3609d1d0-64e5-11e6-900e-632cce20ef3b.png)

**Comment by juniwalk** [comment]
Implemented in 79716f7.
