### ISSUE TITLE
Change row order cross pages?

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#330]
Myslíš že může existovat řešení jak přetáhnout řádek (změna orderu) v tabulce o více stránkách?
Dejme tomu, že na stránce 3 mám row, který chci přetáhnout DragNDrop na první stránku. Momentálně to jde jen v rámci jedné stránky.

**Comment by paveljanda** [comment]
Buď si zobraz víc položek na stránce, nebo přidej inline editaci (klidně i tu malou), kde budeš editovat jen políčko pořadí. A tím pádem můžeš klidně na X-té stránce napsat, že má být prvek na 1. místě. Po uložení překreslit celý grid a je to. :)

**Comment by misaon** [comment]
Jasně, to chápu. Díval jsem se spíš právě po "zajímavější" JS alternativě, např s chyceným řádkem najet na číslo stránky (proběhlo by překreslení) a následně pustit tam kde je potřeba, ale máš pravdu že i zde by byl problém, protože paginator se při více stránkách zmenší a stránkování se nahradí za tečky.. 

Přeci jen mít "navíc" sloupec order může v už tak rozsáhlé tabulce zabírat místo a když bych volil variantu zobrazit všechny produkty, zde můžu narazit na problém např. enormního počtu produktů, které by se následně vykreslily.

**Comment by paveljanda** [comment]
Ano, je to jak to říkáš - řešit to přes JS by byl asi docela vopruz a k takové implementaci se nechystám.

A nebo udělej velkou inline editaci a tam můžeš mít klidně políčko navíc oproti zobrazeným sloupcům. A nebo si dej formulář do item-detailu a tam...

**Comment by misaon** [comment]
Ok, díky za inspiraci :)
