### ISSUE TITLE
Daterange filter problem

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#332]
Mám následující kód:

```
	protected function createComponentGridToggle($name)
	{
		$query = $this->database->table(...);
		
		$grid = new DataGrid($this, $name);
		$grid->setDataSource($query);

		$grid->addColumnDateTime("date", "Datum");
		$grid->addFilterDateRange('date', 'Datum:');

		return $grid;
	}
```
Sloupec **date** je v databázi jako typ "DATE". Když podle něho filtruju, filtr neakceptuje den, který je v hodnotě od, ale až jeho následující den. Nemůže být problém v datovém **typu DATE a půlnocí**?

Když zadám třeba od: 15.1.2016 do 15.6.2016, vyfiltrují se jen záznamy od data 16.1.2016 .
Díval jsem se i na demo a tam ti to funguje správně, nevím kde dělám chybu. 

Ublaboo verze: 4.3.0 i 4.4.9

**Comment by paveljanda** [comment]
Taky nevím, kde může být zakopaný pes. Zkus udělat sandbox demo s sqlite databází a nějakými ukázkovými daty a pošli.

**Comment by misaon** [comment]
Hledal jsem, zdali není problém v URL či nějakém JS pluginu, ale parametry v URL vypadají dobře:
.../toggle/?gridToggle-per_page=20&gridToggle-filter[date][from]=3. 8. 2016

I přes to se data vykreslují až od 4.8.2016.

**Comment by misaon** [comment]
S @JanPosolda jsme tento problém zřejmě rozlouskli.

Chyba je zřejmě ve třídě **ArrayDataSource** (ArrayDataSource.php) na řádku **228**. 
Metoda **applyFilterDateRange**, zde je problém v tom, že **createfromformat** vytvoří DateTime s aktuálním časem místo půlnoci (00:00:00). Proto DateRange filter nefunguje přesně. Domníváme se, že tento problém se může objevit i v jiných částech kódu, kde se pracuje s filtrací datumů.

Navrhujeme to fixnout pomocí metody setTime(0,0,0).

**Comment by paveljanda** [comment]
@misaon Mohli byste sem vložit kus kódu, který bude reflektovat tebou popisované chování? Abych si měl s čím hrát.

Jinde by chyba být neměla, pokud to jinde funguje..

**Comment by JanPosolda** [comment]
Posílám ukázkový kód i s daty, kde to nefunguje. 
Problém je s položkou date, ta je instancí DateTime, kde čas není nastaven (tedy je 00:00:00.000000). Pokud chci filtrovat podle dnešního data, tak se z filtru vezme string '8. 9. 2016', ten se převede na DateTime funkcí **createfromformat**. Tento DateTime má však nastaven aktuální čas. Vyhodnocení filtru se pak provádí porovnáním **getTimeStamp** a tím pádem se pak vyhodnotí jako false.

```
protected function createComponentGridUsers()
{
	$source = [
		[
			'id' => 1,
			'name' => 'Honza',
			'date' => new Nette\Utils\DateTime('2016-09-08')
		],
		[
			'id' => 2,
			'name' => 'Ondra',
			'date' => new Nette\Utils\DateTime('2016-09-08')
		],
	];

	$grid = new DataGrid();
	$grid->setDataSource($source);

	$grid->addColumnText('id', 'Id');
	$grid->addColumnText('name', 'Name');
	$grid->addColumnDateTime('date', 'Date');

	$grid->addFilterDateRange('date', 'Last login:');

	return $grid;
}
```

**Comment by paveljanda** [comment]
Hmm, no jo. Díky kluci!
