### ISSUE TITLE
Projet kód nějakým codecheckerem a linterem

### ISSUE THREAD

**Issue by paveljanda** [ublaboo/datagrid#34]

**Comment by romanmatyus** [comment]
Odporúčam [Scrutinizer](https://scrutinizer-ci.com). [návod](http://romiix.org/blog/test-coverage-s-nette-testerom)

**Comment by paveljanda** [comment]
Taky bych rád Scrutinizer, bohužel je to momentálně nad naše finanční možnosti.

**Comment by romanmatyus** [comment]
Scrutinizer je zadara pre open source. Sám ho bezplatne používam.

**Comment by paveljanda** [comment]
Fakt? Kruci, to jsem přehlédl!

**Comment by paveljanda** [comment]
Projeto. Většina bugů souvisí s magií nette. :D
