### ISSUE TITLE
InlineEdit->setButtonPositionTop()->setButtonPositionBottom()

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#342]
Aktuálne je z pohľadu UI nie úplne správne použiteľné inline pridávanie elementov.

https://www.youtube.com/watch?v=zHYVszJp8K8&feature=youtu.be

Je úplne v poriadku, že sa `inlineAdd` formulár zobrazí na konci gridu, ale button na pridanie záznamu sa nachádza v hlavičke.

Hlavne v prípade väčšieho množstva záznamov je nepohodlné rolovať k hlavičke kvôli kliknutiu na button pridania záznamu - ktorý nás zasa prehodí na koniec gridu.

Navrhujem aby pre `InlineEdit` pribudli metódy `setButtonPositionTop()` a `setButtonPositionBottom()` pri čom predvolene sa to bude správať tak ako teraz, ale po zavolaní `setButtonPositionBottom()` sa zobrazí button AJ dolu. Ak ho hore nechcem zobrazovať, nastavím zároveň aj `setButtonPositionTop(FALSE)`.

![Demo](https://cloud.githubusercontent.com/assets/1110294/18085979/f1f97a7c-6ead-11e6-9b3b-46966324af07.png)

Do dolného riadku by sa taktiež voliteľne mohli presunúť aj toolbar buttony, checkbox pre označenie všetkých riadkov a skupinové akcie. Presúvať tam nastavenie skrytých/zobrazených stĺpcov asi nemá logický význam.

Ešte by bolo možné zlúčiť dva spodné riadky do jedného:

![image](https://cloud.githubusercontent.com/assets/1110294/18086269/60fb61dc-6eaf-11e6-9c10-31f5114d0299.png)

Čo na to vravíte?

**Comment by paveljanda** [comment]
InlineAdd could be placed on the top, so there will be no scrolling (`InlineAdd::setPositionTop()`). If you want to alter the template, please use your template, that will inherit from parent template.

I won't implement that, sorry. Maybe next time. :) But thanks for feedback!
