### ISSUE TITLE
English or Czech?

### ISSUE THREAD

**Issue by dakorpar** [ublaboo/datagrid#345]
I'm just wondering since I don't know Czech langauage this really makes hard to use this grid sometimes. I'm basically tracking everything here and since grid is still in preety early stage where a lot of new features comes in, and things can change I have to be up to date, but since half of issues are on Czech I really can't, so can you just decide is for Czech only market or it's international so I know I can't use it and go somewhere else... I'm sorry if this in any way insults anyone it's not my intention, but some serious projects I'm working on relies on this and I can't allow myself to relly on something I can't use....
- Learning Czech language is not an option :)

**Comment by paveljanda** [comment]
I am starting new issues in EN, also official docu is in EN. I can force people to use only EN in issue, but sometimes they have difficulties using it.
