### ISSUE TITLE
datagrid/tree-view sorting bug

### ISSUE THREAD

**Issue by hurycz** [ublaboo/datagrid#348]
pokud udelam tree view datagrid jako **componentu**, nefunguje sortovani 

handleSort() se generuje na presenter, z ktereho je volana componenta, nikoli na signal pro konkretni componentu

**Comment by lukascellar** [comment]
rovnaky problem, handleSort je linkovany na presenter

**Comment by paveljanda** [comment]
It si crucial to change the handler string a bit: `$grid->setSortableHandler('myComponent:sort!');`.

I will add thins to documentation. Please write issues in EN thanks a lot!

**Comment by lukascellar** [comment]
Still not working with sortable handler, parameters are not prefixed with component name, so handleSort method is called with null arguments

`?do=someGrid-sort&item_id=2&next_id=1&parent_id=`

**Comment by paveljanda** [comment]
Hmmm, is that right?

**Comment by lukascellar** [comment]
Temporary fix in your component:

```
public function handleSort($item_id, $prev_id, $next_id, $parent_id)
{
        $item_id = $this->getPresenter()->getParameter('item_id');
        $prev_id = $this->getPresenter()->getParameter('prev_id');
        $next_id = $this->getPresenter()->getParameter('next_id');
        $parent_id = $this->getPresenter()->getParameter('parent_id');
}
```
