### ISSUE TITLE
nette-forms

### ISSUE THREAD

**Issue by attreid** [ublaboo/datagrid#350]
Is there any reason for using nette-form: 2.2 || 2.3 in bower, when composer using version ^2.3|^2.4 ?

**Comment by paveljanda** [comment]
Well i haven't test it yet. But if you say it's all right, i will merge your PR with updated nete-forms version.. :)

**Comment by attreid** [comment]
Well I'll do it after the weekend

**Comment by attreid** [comment]
I sent PR #351
