### ISSUE TITLE
Permanent AJAX request

### ISSUE THREAD

**Issue by repli2dev** [ublaboo/datagrid#352]
While trying to find bug in our application I have run into these lines: [https://github.com/ublaboo/datagrid/blob/master/assets/dist/datagrid.js#L576-L581](https://github.com/ublaboo/datagrid/blob/master/assets/dist/datagrid.js#L576-L581) which were in fact the root cause!

Our problem was that there is ajax call on every page (we have included the @datagrid.js@ in our JS assets) reloading page after it is loaded even if there is no datagrid on the page... That causes flickering of the page, loosing progress of user etc.

Is there any reason why this is done this way?

**Comment by paveljanda** [comment]
When you filter in datagrid, the url is changed alongside with every request using history API. Then you can go to another page, but when you come to datagrid page again, there is not persistent parameters in URL even though there are grabbed from session and placed in filter inputs. User can then copy the URL, but there are no filters in URL as long as user triggers firt xhr on site (then the url is refreshed using history API again).

I understand your situation. There is not a right way how to solve this. Argh..

I will probably place an `if` statement within the script, which will trigger the mentioned xhr only on sites with datagrid. I will also put this script in separate file, so users can decide whether to use it or not.

Do you have any further comments?

**Comment by repli2dev** [comment]
The described solutions seems good enough for our case.

Though thinking about the issues... shouldn't be reloading just the URL be enough (i.e. do the request everytime, but not to end up with reloading content of whole page?)

**Comment by paveljanda** [comment]
The JS snippet you mentioned above is not reloading the content of whole page. It just triggers a datagrid handler, that will redraw non existing snippet.

It is not enough. When there is a non ajax request to datagrid site, there are persistent url parameters missing.

**Comment by repli2dev** [comment]
I feel a bit puzzled because "reloading the content of whole page" is exactly what I see (especially when I open network console and display the content of the response of such AJAX handler). That's weird.

**Comment by paveljanda** [comment]
`v4.4.18` - There is a `datagrid-instant-url-refresh.js` and `...min.js`, where i put the instant url refresh updated functionality.

**Comment by juniwalk** [comment]
@paveljanda Isn't that BC break?

**Comment by paveljanda** [comment]
@juniwalk Well it was when i added the url refresh couple days ago. Then a realized it is a BC break and moved it to separate file.. so I made a BC break again, but it should fix the previously created BC break. :D

The previous BC break was making ajax callas on every non-ajax page load. That was stupid. Now it creates ajax call on every non-ajax page load only if there is at least one datagrid on page (Yes, you have to include the `datagrid-instant-url-refresh.js` script into your project).

What is your opinion on that?

**Comment by juniwalk** [comment]
@paveljanda So if I understand this correctly, that AJAX request is getting information about rendered datagrid? Current page, filtering, sorting etc? If so, then this fix is alright. :)

**Comment by paveljanda** [comment]
@juniwalk That's right.

**Comment by repli2dev** [comment]
@paveljanda Thank you :-)
