### ISSUE TITLE
Wrong macro in .../templates/datagrid.latte:440

### ISSUE THREAD

**Issue by xpackal5** [ublaboo/datagrid#353]
If I used translation Datagrid caused this error.
File: .../ublaboo/datagrid/src/templates/datagrid.latte:440

```
437:            {if $column instanceof \Nette\Utils\Html}
438:                {$column->getName()|noescape}
439:            {else}
440:                {_$column->getName()}
441:            {/if}
```

**Comment by juniwalk** [comment]
@xpackal5 Could you be more specific? What error?

**Comment by xpackal5** [comment]
Wrong latte macro. {_$column->getName()} may be not allowed.

**Comment by paveljanda** [comment]
@xpackal5 Can you send a PR please? (`|translate`)

**Comment by xpackal5** [comment]
Sorry, dont understand (ale můžem psát česky) :-)

**Comment by paveljanda** [comment]
Mohl bys poslat PR, prosím? (`|translate`)

**Comment by xpackal5** [comment]
Zajímavé je, že když vygeneruju z latte makra cache pomocí latte compilleru tak to normálně přeloží a funguje bez chyb

**Comment by xpackal5** [comment]
Tak jsem to zkoušel zopakovat a nepřeloží :-( Přeloží to jenom když z konstrukce {_$ vyhodím

**Comment by paveljanda** [comment]
Moment, jakou používáš verzi datagridu?

**Comment by xpackal5** [comment]
4.4.12 ale teď koukám,že na webu je 4.4.16, instaloval jsem to přes composer tuším, že někdy před 2 týdny

**Comment by xpackal5** [comment]
Tak dnes aktualizace na PHP5.6, nette 2.4 datagrid  4.4.20 a chybu to vyhazuje stále

**Comment by juniwalk** [comment]
@xpackal5 Co používáš za translator?

**Comment by xpackal5** [comment]
https://github.com/h4kuna/gettext-latte

2016-10-10 14:42 GMT+02:00 Martin Procházka <notifications@github.com>:

**Comment by juniwalk** [comment]
@xpackal5 Jakou verzi nette jsi měl před aktualizaci? Též 2.4?

**Comment by xpackal5** [comment]
2.3

2016-10-10 15:58 GMT+02:00 Martin Procházka <notifications@github.com>:

**Comment by paveljanda** [comment]
@xpackal5 Zkus to prosím bez toho translatoru, případně datagridu nastavit jiný translator (zkus ten datagrid-nativní, SimpleTranslator). Pokud to bude tím, tak ti nějak ten h4kuna ničí Latte macro.

**Comment by paveljanda** [comment]
@xpackal5 Any progress?

**Comment by xpackal5** [comment]
omlouvám se, zaoměl jsem na to zkusím to a dám vědět. Milan

**Comment by paveljanda** [comment]
@xpackal5 Povidlo se? :)

**Comment by xpackal5** [comment]
Simple translator funguje. Milan
