### ISSUE TITLE
$grid->setItemsPerPageList([10,50, 100, 9999]); not work

### ISSUE THREAD

**Issue by xpackal5** [ublaboo/datagrid#354]
Selectbox is normally visible, but no AJAX event triggered if changed

**Comment by paveljanda** [comment]
Did you have all JS-s icluded?

**Comment by xpackal5** [comment]
Yes

**Comment by paveljanda** [comment]
Does work for you the demo in official documentation? If yes, the problem has to be in you code..

**Comment by juniwalk** [comment]
@paveljanda I've tried to set this perPage list on one of my projects and it really does not work. Ajax is not auto-submitted so I click submit manually and it still loads only 10 items (checked by SQL).

**Comment by paveljanda** [comment]
@xpackal5 It does work for me. Can you sand here a ZIP with sandbox-like app, where it is broken? Thanks!

**Comment by xpackal5** [comment]
Podařilo se najít příčinu? Nebo je problém někde u mě?

2016-10-11 22:44 GMT+02:00 Pavel Janda <notifications@github.com>:

**Comment by paveljanda** [comment]
@xpackal5 Aha, tys mi poslal zip do mailu. Mrknu. Já jsem myslel, že už jsi to pustil z hlavy..

**Comment by xpackal5** [comment]
Je to kompletní projekt, nejvíc gridů je třeba na ConfigModulu.

**Comment by paveljanda** [comment]
CHYBA: místní DICOM server neběží....

**Comment by paveljanda** [comment]
Prosím zkus udělat příklad na sandboxu třeba s nějakou sqlite databází..

**Comment by xpackal5** [comment]
To je jenom varování, že něběží síťový démon. Je to aplikace na ovládání
DICOM serveru (medicínská obrazová data). Zkus nahoře menu "Nastavení" a
pak "Správa SOP tříd". Funguje to i bez toho démona

2016-10-11 23:05 GMT+02:00 Pavel Janda <notifications@github.com>:

**Comment by xpackal5** [comment]
jinak díky za ->addAttributes() u toolbar buttonu :-)

2016-10-11 23:05 GMT+02:00 Pavel Janda <notifications@github.com>:

**Comment by xpackal5** [comment]
jj udělám, ale dneska to už nestihnu. tak to kdyžtak pošlu během zítřka..

2016-10-11 23:05 GMT+02:00 Pavel Janda <notifications@github.com>:

**Comment by xpackal5** [comment]
Udělal jsem úplně jednoduchý grid na jedné tabulce a ten funguje -
implementoval jsem víceméně vše co bylo v gridech, kteér mi nefungovali
(kromě translatoru) a běží to. Každopádně všimnul jsem si, že nejde navěsit
na dynamicky generovaný prvek žádný event (ani pomocí
$(document).on("click",".prvek",function(e){ .... }); takže budu hledat
chybu u sebe v DOM. Dám vědět jak to dopadlo.
PS: odkaz na funkční grid v sandboxu je http://leteckaposta.cz/539871711

2016-10-11 23:05 GMT+02:00 Pavel Janda <notifications@github.com>:

**Comment by xpackal5** [comment]
Tak po dlouhé době jsem se dostal k hledání příčiny, protože mi to stále nefunguje. Hledal jsem rozdíly mezi aplikací, kde to funguje a kde ne, konflikty mezi knihovnama a prostě nic. V jedné to funguje a v jedné ne. Co jsem ale zjistil, že pokud vyberu jednu z těch optionů, tak se event change pro select[data-autosubmit-per-page] vyvolá, co se ale nestane je ten autosubmit přes $(this).parent().find('input[type=submit]').click(); zkusil jsem ho tedy udělat přes  
var $this;$this = $(this);  return $this.closest('form').submit();
a ejhle, vše funguje. Tak nevím, ale příčinu jsem neobjevil. Milan
