### ISSUE TITLE
Sort - third state is zero, causing an error

### ISSUE THREAD

**Issue by Danoha** [ublaboo/datagrid#359]
Code:

```php
$this->addColumnDateTime('date', 'Datum')
	->setSortable();
```

First click on col header applies ASC sort. Second click applies DESC sort. Thirt click generates link with `grid-sort-date=0`. This value is not expected and generates (using nette/database) following query:

```SQL
SELECT * 
FROM `transaction` 
ORDER BY `date` 0 
LIMIT 10
```

The same behaviour can be seen [here](http://ublaboo.org/datagrid/column). Server even starts to throw 500`s.

**Comment by Mark53CZ** [comment]
Same problem, any hotfix?
