### ISSUE TITLE
Each column render cycle adds already existing classes

### ISSUE THREAD

**Issue by Danoha** [ublaboo/datagrid#360]
Each rendered cell contains classes from previous row.

Eg.

header (first render):

``` html
<th class="text-left">Odesílatel</th>
```

first row:

``` html
<td class="text-left text-left col-sender">...</td>
```

second row:

``` html
<td class="text-left text-left col-sender text-left col-sender">...</td>
```

This is caused by multiple usage of Html instance stored in `\Ublaboo\DataGrid\Column\Column::$el_cache`.

**Comment by juniwalk** [comment]
@Danoha Hello, do you have inline edit enabled?
