### ISSUE TITLE
Row detail not working since 4.4.10

### ISSUE THREAD

**Issue by lukascellar** [ublaboo/datagrid#363]
@pitr82 After this change in 4.4.10 version

https://github.com/ublaboo/datagrid/pull/334/commits/44aa1a2eb6ca04d4dc6b79f08550a947af316cf2

row detail is not working with Nette 2.3. Line removal solves this problem.

**Comment by paveljanda** [comment]
@pitr82 Does work the online demo for you? There is already the newest version. And it seems ok.

**Comment by pitr82** [comment]
This PR solved problem with nette 2.4 and forms in row detail. 
@lukascellar can you update to nette 2.4?

**Comment by lukascellar** [comment]
At this moment I can't update to 2.4, temporarily solved with overloading handleGetItemDetail method.

**Comment by neo82nd** [comment]
I can confirm that in v4.4.18 it works again
