### ISSUE TITLE
Add external parameters to ToolbarButton

### ISSUE THREAD

**Issue by xpackal5** [ublaboo/datagrid#366]
Hello.
Sometimes may be usable something like method ->addAttributes(array $attributes) from Action to ToolbarButton :-)
Thanks Pavel to nice datagrid !!

**Comment by attreid** [comment]
I think it is there. You can use
```php
$grid->addToolbarButton('add', 'Add', ['variable' => 'value']);
```

**Comment by xpackal5** [comment]
Sure. But this add parameters to URL link. I need add attributes to <a> element.

**Comment by attreid** [comment]
Oh, title confused me
