### ISSUE TITLE
setIcon -> Illegal offset type

### ISSUE THREAD

**Issue by tomkralik** [ublaboo/datagrid#368]
Hello,
I tested the new version and I ran into error messages.
I have a classic grid follows.
`...
$grid->addAction('delete', '', 'opravnenisekDel!')
                ->setIcon('trash-o')
                ->setTitle('Smazat')
                ->setConfirm('Opravdu smazat oprávnění pro uživatele %s?', 'uzivatel');
...
`
I get an error: **„Illegal offset type“ v nette\utils\src\Utils\Html.php:203**

Below is a grid without any problems.
`...
$grid->addAction('delete', '', 'opravnenisekDel!')
                ->setTitle('Smazat')
                ->setConfirm('Opravdu smazat oprávnění pro uživatele %s?', 'uzivatel');
...`

Thanks

**Comment by juniwalk** [comment]
Hello, sorry for the delay,
I reviewed your issue and it seems everything is working properly. It has been problably fixed before I got to check it out.

I am closing this. Let me know if your issue is still there.

**Comment by tomkralik** [comment]
Hello, 
My problem persists **„Illegal offset type“ v nette\utils\src\Utils\Html.php:203** 
I do not know creches can be a problem in version nette. 
I have: Nette 2.3.10, PHP 5.6.25 and DataGrid Ublaboo is current. 

Causing the problem  ->setIcon('trash-o')

Thank you

**Comment by tomkralik** [comment]
Hello,
I performed some tests and found that the problem is really in version nette.
I used Nette 2.3.11 and the problem is gone.

Thank you for your time.

**Comment by juniwalk** [comment]
Great! :)
