### ISSUE TITLE
How to implement Ublaboo datagrid  - for total beginners

### ISSUE THREAD

**Issue by vyndalin** [ublaboo/datagrid#373]
Hello Pavel (or other volunteers),
I'm new to nette framework and I want to place this great datagrid on my page but, I just can't find out how to do that. I'm confused by official tutorial. So if someone could send me really simple project sample with datagrid (3-4 columns with some filter - select menu with unique values from its column if possible -  and action buttons like inline editing, deleting, adding new row would be good enough - nothing special, but for me it's top of the peak right now). I'm able to read documentation and play with settings to adjust it to my needs, but I need to display datagrid first - and I'm lost at this point. Confused with all those classes and what to write to which file exactly.
Thank you very much in advance.
Aleš

**Comment by paveljanda** [comment]
All datagrids on org/datagrid have also example code in PHP. Just click on the "Show me the code" link. :)


On September 27, 2016 at 10:40:17, vyndalin (notifications@github.com) wrote:

Hello Pavel (or other volunteers),
I'm new to nette framework and I want to place this great datagrid on my page but, I just can't find out how to do that. I'm confused by official tutorial. So if someone could send me really simple project sample with datagrid (3-4 columns with some filter - select menu with unique values from its column if possible - and action buttons like inline editing, deleting, adding new row would be good enough - nothing special, but for me it's top of the peak right now). I'm able to read documentation and play with settings to adjust it to my needs, but I need to display datagrid first - and I'm lost at this point. Confused with all those classes and what to write to which file exactly.
Thank you very much in advance.
Aleš

**Comment by juniwalk** [comment]
@vyndalin What @paveljanda said is exactly right. Here is also small example I just created for you https://gist.github.com/juniwalk/49b27c438417855131063be87d3c7c6b

I recommend creating reusable components with datagrids inside so you don't clutter your presenters.

**Comment by vyndalin** [comment]
@juniwalk thanks for your reaction. but there's this error **syntax error, unexpected ':', expecting ';' or '{'
 43: protected function createComponentUserGrid(string $name) : DataGrid**
@paveljanda I gave a try to that samples, but I had problems as well. It seems datagrid isn't installed as component correctly into project... I'm suspecting, that's my problem and I have to chceck if I'm using composer correctly.
Thank you both gentlemen

**Comment by juniwalk** [comment]
@vyndalin That's because this is PHP 7 code.
