### ISSUE TITLE
Weird filtering [forum repost]

### ISSUE THREAD

**Issue by CZechBoY** [ublaboo/datagrid#381]
https://forum.nette.org/cs/25444-ublaboo-datagrid-mocny-rychly-rozsiritelny-hezky-anglicky-dokumentovany-datagrid?p=11#p179586

Code:
https://github.com/CZechBoY/ublaboo-datagrid-bug-filtering

1) try to filter "produkt2"
2) try to filter ""
3) bug: still filtering by "produkt2" ????

**Comment by paveljanda** [comment]
`$form->getValues()` apparently does not behave as `$form->getHttpData()`. `$form->getValues()` gives bigger priority to url query parameters (although the form is only of type POST), which is pretty weird. I will put that on nette forum.

**Comment by paveljanda** [comment]
Fix is in master. WIll be in next release. Thanks for reporting this issue!
