### ISSUE TITLE
Ublaboo\DataGrid\Row -> getValue($key)

### ISSUE THREAD

**Issue by m3v** [ublaboo/datagrid#385]
upravit

```javascript
} else if ($this->item instanceof DibiRow) {
            return $this->item->{$key};
}
```

return tak, aby key rozdelilo napr. z t.id na id – takto bude fungovat $grid->setPrimaryKey(‚t.id‘); pri joint selectoch, dik

**Comment by paveljanda** [comment]
Thanks for reporting us!
