### ISSUE TITLE
Session filter: Filter  not found when modifying grid columns

### ISSUE THREAD

**Issue by dakorpar** [ublaboo/datagrid#389]
I know what's issue there, but I'm just wondering is it really neccessary to throw exception for this?
As live project always changes you have to modify your grids as well, and then you need to clear session data for all users, probably easiest solution would be to change grid name, but what I'm thinking is that maybe this should be silent error, maybe just ignore that field and continue on, like this is little bit annoying...
Thoughts?

**Comment by juniwalk** [comment]
I am 👍 for this, had multiple issues with this.

//cc: @paveljanda

**Comment by paveljanda** [comment]
Sure, the datagrid can silently drop the session value and continue executing script.

**Comment by juniwalk** [comment]
@dakorpar Could you post the exception here please? I jumped on the opportunity to fix this and now I don't know how to replicate the issue. :D

**Comment by dakorpar** [comment]
You can replicate this by just changing column name
