### ISSUE TITLE
Sorting by multiple columns

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#391]
Add option to sort by multiple columns using simple logic.
`No sort` -> `sort ASC` -> `sort DESC` -> `no sort`

On `DataGrid` class add method `DataGrid::setMultiSortable($multiSortable = TRUE);`.

**Comment by paveljanda** [comment]
Can you do that? :)

**Comment by juniwalk** [comment]
Well I can try? :)

**Comment by dakorpar** [comment]
When do you expect this will be done? Just bumped into few grids where I need that :)
