### ISSUE TITLE
Syntax error, unrecognized expression: .datagrid-tree-item[data-id=]

### ISSUE THREAD

**Issue by attreid** [ublaboo/datagrid#395]
When datagrid uses string as id and id contains character '.', JS throwing
```
Syntax error, unrecognized expression: .datagrid-tree-item[data-id=]
```

For fix change line https://github.com/ublaboo/datagrid/blob/master/assets/src/datagrid.coffee#L376
to 

```javascript
children_block = $('.datagrid-tree-item[data-id="' + id + '"]').find('.datagrid-tree-item-children').first()
```

**Comment by juniwalk** [comment]
Could you send pull request?

**Comment by attreid** [comment]
Should I fix just coffee script or coffee and compile js and min.js?

**Comment by juniwalk** [comment]
@attreid Please compile JS too. Thanks!

**Comment by attreid** [comment]
I sent PR

**Comment by juniwalk** [comment]
Fixed in #396 by a89ca8b.

**Comment by attreid** [comment]
Can you release stable version?

**Comment by juniwalk** [comment]
@attreid We are making changes to release ne major version. As we currently do not branch major versions we can't.

//cc: @paveljanda

**Comment by paveljanda** [comment]
@attreid You can use your own fork for now and when new version (`v5.0.0.`) is released, you can switch back to the original repo.

**Comment by attreid** [comment]
ok, no problem, thanks
