### ISSUE TITLE
Action icons

### ISSUE THREAD

**Issue by sikulam** [ublaboo/datagrid#397]
Hi,
please it´s any options how to set icon as `<i class=fa fa-arrows-v>`  instead of `<span class=fa fa-arrows-v>`

Icons for setSortable is in tag <i> and other action button is in <span>

**Comment by juniwalk** [comment]
@sikulam Hi, what is wrong with span?

**Comment by sikulam** [comment]
@juniwalk Hi, wrong is nothing, but i use css framework witch works diferent with span and i tag. It´s some option how to change span to i in actions?

**Comment by juniwalk** [comment]
@sikulam To my knowledge, there is not, but I think we could switch to using `<i>`, I use it everywhere too. @paveljanda what do you think?

**Comment by paveljanda** [comment]
@sikulam I have to disappoint you - you have to use your own template.. Isn't there really any chance to use `<span>`? I think that most css frameworks are written really modularly..

**Comment by paveljanda** [comment]
But we are using `i` tag, don't we?

**Comment by paveljanda** [comment]
Oh, I see. `ColumnStatus` uses `span`. Also `FilterDate` and `FilterDateRange`. I will fix that.

**Comment by paveljanda** [comment]
@sikulam Is it all righ now?

**Comment by sikulam** [comment]
@paveljanda Perfect thanx for help
