### ISSUE TITLE
Inline editation does not work when using tree-view

### ISSUE THREAD

**Issue by vkDesign** [ublaboo/datagrid#398]
Is it possible to enable the inline-edit function in the tree-view?
Thanks for the answer,
Vili Koprivec

**Comment by juniwalk** [comment]
@vkDesign Hello, I wanted @paveljanda to give you a response but he is bussy.

I think it was not intended so. Tree view is special case in which many more features of DataGrid do not work.

**Comment by juniwalk** [comment]
Hello, as I said before, tree view is a special case in which many of the features are not supported. I think we should separate tree view into completely new class, maybe even repository.

For now I am closing this.
