### ISSUE TITLE
Automatically expand specified rows on tree-view

### ISSUE THREAD

**Issue by SiViN** [ublaboo/datagrid#399]
Zdravim, neslo by pridat neco co by otevrelo pri pouziti tree-view automaticky nejakou vetev, popr. vice vetvi? Uzivatel se slozite proklika pres nekolik urovni, kde pak klikne na detail. V detailu pak klikne zpet a cely strom je zase zavreny a musi zacit s proklikavanim znovu :( Ja mu tlacitko zpet nabizim a vim i jakou vetev otevrit,takze bych si v odkazu predal co zpet otevrit, bohuzel jsem ale nenasel jak nejakou vetev expandovat,

**Comment by juniwalk** [comment]
@SiViN To nebude tak lehké, strom se nenačítá najednou ale ajaxove větev po větvi. To znamená že bys musel nějak uložit cestu té větve a pak to postupně načítat.

**Comment by juniwalk** [comment]
Similar issue: #234

**Comment by paveljanda** [comment]
@SiViN jak psal @juniwalk, větve se načítají ajaxově, právě aby se při každém requestu nemusely všechny tahat.

Máš několik možností:
1, Udělat detail v modalu
2, Odkazovat detail do jiného okna a při uložení překreslit konkrétní větev

Bohužel neplánuji implementovat takovou funkcionalitu.
