### ISSUE TITLE
How to add custom component in ItemDetail

### ISSUE THREAD

**Issue by zemnet** [ublaboo/datagrid#401]
Hi,
Can I add custom component created in presenter into ItemDetail?

In template maybe with call the control macro:
`{block detail}
  {control test}
{/block}`

Thank you.

**Comment by juniwalk** [comment]
@zemnet Well, try to do it like this: `{control $control->getPresenter()->getComponent('myCoolComponent')}`

**Comment by zemnet** [comment]
done, works good.
thank you...
