### ISSUE TITLE
DataGrid::setDefaultFilter() can not operate with \DateTime

### ISSUE THREAD

**Issue by zemnet** [ublaboo/datagrid#410]
Hi,
I found a little bug.
If I want to add Default values for Filter DateRange,
app ends with error:
`Fatal error: Call to a member function setTime() on a non-object in /home/testisp/nette/vendor/ublaboo
/datagrid/src/DataSource/DoctrineDataSource.php on line 178`

`        $from  = new DateTime();
        $to  = new DateTime();
        $grid->setDefaultFilter(['datumVystavenia'=>['from'=>$from,'to'=>$to]]);
`
Thanx

**Comment by juniwalk** [comment]
Well, I looked into it and it seems that DataGrid is not ready for `DateTime` instance for default values. This is little bigger issue, @paveljanda what do you think?

**Comment by paveljanda** [comment]
@juniwalk It is really not. Adding issue into milestone `v5.0`.

**Comment by juniwalk** [comment]
@paveljanda You don't need to prefix the title with "bug", there is a label for that. :)
