### ISSUE TITLE
Ability to use filtered data in another component

### ISSUE THREAD

**Issue by michallohnisky** [ublaboo/datagrid#415]
Hi,

I want to render a grid and a chart on one page. How can I get the filtered, ordered, not paginated datasource from the grid?

I tried to create custom export which only saves the items into variable for later use and then I called
```
$grid->handleExport(1);
```
The problem is, that the filtering and ordering is then applied on the datasource twice: (1) `handleExport` and (2) `render`. MsSQL (btw: I would like to use MySQL instead, but I can't) then gives me an error: `A column has been specified more than once in the order by list. Columns in the order by list must be unique. `

Can you show me the best practice?

**Comment by paveljanda** [comment]
@michallohnisky You should probably use your own template for datarid.

Or you can extend DataGrid class, take the datamodel from parent and somehow alter it, so the parent datagrid will have the paginated data and your won't.

No better options comes to my head.
