### ISSUE TITLE
DoctrineDataSource: Loading entities as array

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#42]
So I found the problem we were talking about in #40,
you are getting doctrine data as an array which is wrong, entities aren't just packages of data, there are methods that supplement the data and those methods are needed.

I think DoctrineDataSource should be changed to return list of entities (objects) and for reading data, you should consider [symfony/property-access](https://github.com/symfony/property-access).

**Comment by paveljanda** [comment]
@juniwalk 
Datagrid is now recursively accessing entity properties via symfony/property-access package. Almost same behaviour (just without using PropertyAccessor) is used when using LeanQuery (LeanMapper\Entity) (LeanMapper/LeanQueryDataSource is not implemented though).

Now it is in master, so you can already use it.
In the evening i will write some tests and release version 1.2.0.

**Comment by DavidZadrazil** [comment]
@paveljanda 
Nice work! Just testing and seems OK.

**Comment by juniwalk** [comment]
@paveljanda Guys you are amazing! Thanks!
