### ISSUE TITLE
Filter by ID in datasource with JOINS

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#421]
Hello, i have some problem with filtering by ID. We have datasource builded from JOINS more tables.
When you try fitler by ID, you will get Exception (Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous) in 

```
SELECT COUNT(`ticket`.`id`) 
FROM `ticket` 
LEFT JOIN `user` ON `ticket`.`user_id` = `user`.`id` 
WHERE (`user`.`id`) AND ((`id` LIKE '%6008%'))
```

Solution:
```
SELECT COUNT(`ticket`.`id`) 
FROM `ticket` 
LEFT JOIN `user` ON `ticket`.`user_id` = `user`.`id` 
WHERE (`user`.`id`) AND ((`ticket`.`id` LIKE '%6008%'))
```

Exist any way how to filter by ID in Datasource with JOINS?

**Comment by dakorpar** [comment]
when adding filter you shoud write full column name
so instead of ->setFilterText(); 
you can call >setFilterText('table.id');

**Comment by misaon** [comment]
Thanks a lot 👍
