### ISSUE TITLE
Github Releases

### ISSUE THREAD

**Issue by f3l1x** [ublaboo/datagrid#422]
Hi, good job btw. I've noticed that you are not follow standard github release process. 

@componette fetch these releases and display them. It looks great.But at your case it does not.

![selection_003](https://cloud.githubusercontent.com/assets/538058/20746116/bde02a7c-b6e4-11e6-8d11-f0ffc3a75187.png)

What do you think?

**Comment by paveljanda** [comment]
If you look at the releases page (https://github.com/ublaboo/datagrid/releases), you would see that @juniwalk started already that convention for this repo.

**Comment by juniwalk** [comment]
@paveljanda It is not visible to others yet :)

**Comment by paveljanda** [comment]
Really? Sorry, my fault.

Anyway, we already started these description-y releases.

**Comment by f3l1x** [comment]
@paveljanda @juniwalk Good job. Keep going. :+1:

**Comment by juniwalk** [comment]
@f3l1x Is this better? :) https://componette.com/ublaboo/datagrid/

**Comment by f3l1x** [comment]
Fabulous. 👍
