### ISSUE TITLE
DoctrineDataSource   joining table and count

### ISSUE THREAD

**Issue by jarda256** [ublaboo/datagrid#431]
Hi, I have more like question than functional issue. I would like to get informations about entity Site and join to it count of entities group, which are connected to Site. For example. i have Site A and Groups a1,a2,a3,a4. So i wanna see informations about Site and Count of groups 4 in datagrid. My query for DoctrineDataSource looks like this. Thaks for any help.

P.S.: I hope, I made myself clear.

`$query = $this->em->createQueryBuilder()
            ->addSelect('partial s.{id,event,visible,name,maxmembers,carlimit,regcopymail},COUNT(g) as groupCount')
            ->from(Site::class, 's')
            ->where('s.event = ?1 AND s.memberLimitReached = 0')->setParameter(1, $id)
            ->orderBy('s.name', 'ASC')
            ->leftJoin(Group::class, 'g');`

**Comment by juniwalk** [comment]
@jarda256 Hello,
you cannot join like this, you can either use `->leftJoin('s.groups', 'g')` or you will have to add ON clause like in normal SQL.

If you have association `groups` on you Site entity, then just use `COUNT(s.groups) groupCount` and don't join it. Also I think you will need groupBy for this to work properly.

And lastly, I don't know if `DoctrineDataSource` can handle selecting partial entities.

**Comment by jarda256** [comment]
@juniwalk Hi,
at first, thaks for quick reply and good advice. I am begginer in this so thats why i made that mistake, but now i get it :) 
And yes DoctrineDataSource can hadle partial.

**Comment by juniwalk** [comment]
@jarda256 Ah, I see, I am glad it worked for you!

**Comment by jarda256** [comment]
@juniwalk Well...it seemed working till I tried add count column to grid. Maybe if I show some code (from another entity but same problem) someone can see where is bug. Maybe DoctrineDataSource just can't hadle count :/ Then I have a question. Can I add custom column (make fucntion for that count and add it..or something like that)? 

/-----------------------------------------------------------/

$query = $this->em->createQueryBuilder()
->addSelect(‘r,COUNT(c.id) as checksCount’)
->from(Registration::class, ‘r’)
->join(‘r.checks’,‘c’)
->groupBy('r.id');
 $this->registrations = $query; 

/-----------------------------------------------------------/

$grid->setPrimaryKey(‘id’); 
$source = new DoctrineDataSource($this->registrations,‘id’);

/-----------------------------------------------------------/

/**
* @ORM\OneToMany(targetEntity=“Check”,mappedBy=“registration”)
* @var ArrayCollection | Check[]
*/ private $checks;

function addCheck(Check $checks) {
$this->checks[] = $checks; } function getCheck() {
return $this->checks; } 

/-----------------------------------------------------------/

/**
* @ORM\ManyToOne(targetEntity=“Registration”,inversedBy=“checks”)
* @ORM\JoinColumn(name=“registration_id”, referencedColumnName=“id”)
*/ protected $registration;

**Comment by juniwalk** [comment]
@jarda256 Problem is, `SELECT r, COUNT(c.id)` will NOT return just entity, but also that count, so it will not be list of entities but list of lists in which is entity and that count. That is something that DataGrid does not expect, it wants just list of entities.

You could add method `getCountChecks()` to that entity and just do the count in the PHP. You will have to join those checks in select so you don't send thousands SQL to make the count.

**Comment by jarda256** [comment]
@juniwalk So leave that query with join but `SELECT r,c` but I have now clue for that method and using it with grid. Can you give me a hint please

**Comment by juniwalk** [comment]
@jarda256 DataGrid does not care about the properties you have in the entity, it uses Symfony/PropertyAccessor, so if you create method `getCountChecks` that would return the number and then add column named countChecks then it will get the value from that method, it does not have to be column in database.

**Comment by jarda256** [comment]
@juniwalk Well I took your advice and make this. But it not seemed to be correct. Grid column is empty, but when i uncomment that ` dump($count);` I have there correct nuber twice (both from tracy-dump). Any idea why?


$grid->addColumnNumber('countChecks', 'countChecks', 'countChecks');
/----------------------------------------------------------------/
$query = $this->em->createQueryBuilder()
            ->addSelect('r')
            ->from(Registration::class, 'r');
/--------------------------------------------------------------/
 /**
     * @ORM\OneToMany(targetEntity="Check",mappedBy="registration", cascade={"persist", "remove"})
     * @var ArrayCollection | Check[]
     */
    private $checks;

    function addCheck(Check $checks)
    {
        $this->checks[] = $checks;
    }
    function getChecks()
    {
        return $this->checks;
    }

    private $countChecks;

    function getCountChecks(){
        $count = $this->getChecks()->count();
//        dump($count);
        $this->countChecks = $count;
    }

**Comment by juniwalk** [comment]
@jarda256 Don't assign it to `$countChecks`, you don't even need that property, just return that count from that method.

**Comment by jarda256** [comment]
@juniwalk Well, that works... You are awesome. I am so thankful. Thank you so much for your help.

**Comment by juniwalk** [comment]
@jarda256 I am glad it worked for you. :)
