### ISSUE TITLE
add spinner to columnStatus with onChange

### ISSUE THREAD

**Issue by jarda256** [ublaboo/datagrid#440]
Hi, I would like to ask, if there is any possibility to add datagrid-spinner to columnStatus with onChange. Thanks

**Comment by paveljanda** [comment]
@jarda256 Maybe you can add a extra JS extension to your code. Something like [here](https://github.com/ublaboo/datagrid/blob/master/assets/dist/datagrid-spinners.js#L19).

A won't add that at the moment. I think the spinner should be triggered after these not-data-related action like pagination, resetting filter, etc
