### ISSUE TITLE
HideColumn not woring in one grid but works in another

### ISSUE THREAD

**Issue by jarda256** [ublaboo/datagrid#441]
Hi, I got a problem. I have two grids (not on same site). For one hiding columns works but for another doesn't. setDefaultHide also doesn't work. What can be wrong? Both same grid settings. This is not working grid.

$grid = new DataGrid($this, $name);
        $grid->setPrimaryKey('id');
        $source = new DoctrineDataSource($this->registrations, 'id');
        $grid->setDataSource($source);
        $grid->setItemsPerPageList([8, 50, 100], false);
        $grid->setColumnsHideable();
        $grid->setRememberState(FALSE);
        $grid->setDefaultSort(['id' => 'DESC']);
        $grid->addExportCsvFiltered('Csv export (filtered)', 'registration.csv')
            ->setTitle('Csv export (filtered)');

        /** Filters */
        $grid->addFilterText('id', 'Search', 'id');
        $grid->addFilterSelect('status', 'Status:', [
            '' => 'All',
            'zadáno' => 'Zadáno',
            'schváleno' => 'Schváleno',
            'zamítnuto' => 'Zamítnuto',
            'částečně zaplaceno' => 'Část. Zapl.',
            'zaplaceno' => 'Zaplaceno',
        ]);
        $grid->addFilterText('event', 'Search', 'event.name');
        $grid->addFilterText('site', 'Search', 'site.name');
        $grid->addFilterText('leader', 'Search', 'leader.nickname');
        $grid->addFilterText('leaderEmail', 'Search', 'leader.email');
        $grid->addFilterText('leaderT', 'Search', 'team.teamname');
        $grid->addFilterDateRange('registrationDate', 'Search');
        /** Filters ^^^^^^^^^^^^^ */

        $grid->addColumnNumber('id', 'Id', 'id')->setSortable('id');
//        $grid->addColumnText('status', 'Status', 'status')->setSortable('status');

        $grid->addColumnStatus('status', 'Status')->setSortable('status')
            ->addOption('zadáno', 'Zadano')->endOption()
            ->addOption('schváleno', 'Schvaleno')->endOption()
            ->addOption('zamítnuto', 'Zamítnuto')->endOption()
//            ->addOption('stornovano', 'Stornovano')->endOption()
            ->addOption('částečně zaplaceno', 'Část. Zapl.')->endOption()
            ->addOption('zaplaceno', 'Zaplaceno')->endOption()
            ->onChange[] = [$this, 'handleChangeStatus'];

        $grid->addColumnText('event', 'Event', 'event.name');
        $grid->addColumnText('site', 'Site', 'site.name');
        $grid->addColumnText('leader', 'Leader', 'leader.nickname');
        $grid->addColumnText('leaderEmail', 'Email', 'leader.email');
        $grid->addColumnText('leaderT', 'Team', 'leader.team.teamname');
        $grid->addColumnNumber('countChecks', 'Registrováno', 'countChecks');
        $grid->addColumnNumber('countPaidChecks', 'Zaplaceno', 'countPaidChecks');
        $grid->addColumnDateTime('registrationDate', 'Registrováno', 'registrationDate')
            ->setFormat('d.m.Y H:i');

        $grid->addAction('detail', '', ':Admin:Registration:detail')
            ->setIcon('eye')
            ->setTitle('Detail')
            ->setClass('btn btn-xs btn-primary');
        $grid->addAction('accept', '', 'AcceptRegistration!')
            ->setIcon('check')
            ->setTitle('Accept')
            ->setClass('btn btn-xs btn-success ajax');
        $grid->addAction('decline', '', 'DeclineRegistration!')
            ->setIcon('times')
            ->setTitle('Decline')
            ->setClass('btn btn-xs btn-danger ajax');

        $grid->allowRowsAction('accept', function ($item) {
            return $item->event->approve && in_array($item->status, ["zadáno", "zamítnuto"]);
        });
        $grid->allowRowsAction('decline', function ($item) {
            return $item->event->approve && in_array($item->status, ["zadáno", "schváleno"]);
        });

        $grid->addGroupAction('Schválit')->onSelect[] = [$this, 'acceptMany'];
        $grid->addGroupAction('Zamítnout')->onSelect[] = [$this, 'declineMany'];
        $grid->addGroupAction('Zaplaceno')->onSelect[] = [$this, 'paidManyRegistrations'];

        return $grid;

**Comment by paveljanda** [comment]
@jarda256 `setRememberState(FALSE)` makes datagrid not use session, so it can not remember which columns are hidden a which are not.
