### ISSUE TITLE
DoctrineDataSource filter by method from entity 

### ISSUE THREAD

**Issue by jarda256** [ublaboo/datagrid#442]
Hi, i got function `getCountChecks()` in my entity and i have it displayed in grid by `$grid->addColumnNumber('countChecks', 'Registrováno', 'countChecks');` but what if i want to add filter to this (like filterRange)? I can't because it needs to be in database. Or can it be done somehow?

function getCountChecks()
    {
        $count = $this->getChecks()->count();
        return $count;
    }

**Comment by juniwalk** [comment]
@jarda256 Hello, sadly no, you need to use SQL to filter this. It should not be problem as you are able to create custom callback for creating WHERE clause.

**Comment by jarda256** [comment]
So i need to add that count to database or? I just don't know what do you meen by custom callback. If it's not in database I can't it to SQL.

**Comment by juniwalk** [comment]
@jarda256 Well if I remember correctly, those checks are entries in database aren't they? Then you can do simple COUNT(x) can't you?

**Comment by jarda256** [comment]
@juniwalk Correct checks are entities joined with registration entity. So maybe I can do something like WHERE COUNT(r.checks) or WHERE COUNT(c). But how to get it to dql?

$query = $this->em->createQueryBuilder()
            ->addSelect('r,c,leader,site,team,event')
            ->from(Registration::class, 'r')
            ->join('r.checks', 'c')
        return $query;
    }

**Comment by juniwalk** [comment]
```php
$filter->setCondition(function($qb, $value) {
    $qb->andHaving('COUNT(r.checks) > :checks')
        ->setparameter('checks', $value);
});
```

Nějak takto by to mělo vypadat asi. Není to otestované.

**Comment by jarda256** [comment]
@juniwalk I tried it, but realised one problem and one showed tracy. In filterRange you need to pass 2 params once with < and than with >. A second thing. setParameter() doesnt work. http://awesomescreenshot.com/02d67s01ec

**Comment by juniwalk** [comment]
@jarda256 Then just modified that custom condition to accommodate two values.

**Comment by jarda256** [comment]
@juniwalk yea thats not a problem you just use $value['from'] and $value['to']...but you cant use  COUNT(r.checks) like that....at least I think that this is, what that error means

**Comment by juniwalk** [comment]
@jarda256 No, invalidPathException is probably problem with `r.checks` in the COUNT, try `COUNT(c)` instead.

**Comment by jarda256** [comment]
I tried few things, but none of them wok... I have 2 rows. 1. count is 5 and second 23...but when i write from 6 i got that 23 row but instead of count 23 there is 1.


$qb->andHaving('COUNT(c.id) > '.$value['from']);
$qb->andHaving('COUNT(c.id) > '.$value['from'])->groupBy('c.registration');
$qb->andHaving('COUNT(c.id) > '.$value['from'])->groupBy('r.id');

**Comment by juniwalk** [comment]
@jarda256 I think that is because the query breaks selected rows, you need to use postFetch to select associations.

**Comment by juniwalk** [comment]
@jarda256 In this PR you can find more information. https://github.com/ublaboo/datagrid/pull/315

**Comment by jarda256** [comment]
@juniwalk I haven't found solution yet. But i'll keep trying and when I find it, i'll notice you. It can be useful

**Comment by juniwalk** [comment]
@jarda256 Check that PR, you need to separate loading of main entity and the association entities using that `onDataLoaded` callback.

**Comment by jarda256** [comment]
@juniwalk I made it works.
//source
 public function getAllRegistrationsQuery()
    {
        $query = $this->em->createQueryBuilder()
            ->select('r')
            ->from(Registration::class, 'r')
        ;
        return $query;

$grid->getDataSource()->onDataLoaded[] = function () {
            $this->entityManager->getRepository(Model\Entities\Registration::class)
                ->createQueryBuilder('r')
                ->select('r,c,leader,site,team,event')
                ->leftJoin('r.checks', 'c')
                ->leftJoin('r.leader', 'leader')
                ->leftJoin('r.site', 'site')
                ->leftJoin('leader.team', 'team')
                ->leftJoin('r.event', 'event')
                ->getQuery()->getResult();
        };
$grid->addFilterRange('countChecks', 'Search', 'countChecks')
            ->setCondition(function ($qb, $value) {

                if (!isset($value['from'])) {
                    $value['from'] = "";
                }
                if (!isset($value['to'])) {
                    $value['to'] = "";
                }

                $qb->addSelect('count(c.id) AS HIDDEN cx')
                    ->leftJoin('r.checks', 'c')
                    ->groupBy('r.id');

                if ($value['from'] != null && $value['to'] == null) {
                    $qb->andHaving('cx >= ' . $value['from']);
                } elseif ($value['from'] == null && $value['to'] != null) {
                    $qb->andHaving('cx <= ' . $value['to']);
                } elseif ($value['to'] != null && $value != null) {
                    $qb->andHaving('cx >= ' . $value['from'] . ' AND cx <= ' . $value['to']);
                }
            });

**Comment by juniwalk** [comment]
@jarda256 Great! You are learning fast! Now learn how to register repositories into DI so you don't use EntityManager like that. :) It's cleaner that way.

**Comment by jarda256** [comment]
@juniwalk getAllRegistrationsQuery() is located in registrationFacade. I'll move onDataLoaded to facade and just call it like $this->registrationFacade->registrationOnLoadQuery(); that's right way, isn't it?

**Comment by juniwalk** [comment]
I was refering to this: `$this->entityManager->getRepository(Model\Entities\Registration::class)`, you should register RegistrationRepository in DI and let DI autowire it into your code.

Oh and by the way, your onDataLoaded callback receievs loaded entities so you can use list of IDs to load just associations you want. This is not optimized. Check the PR I was refering to before.

**Comment by jarda256** [comment]
I don't use access like this. I have entity and facade for it. Like Registration.php and RegistrationFacade.php. 

**Registration presenter**
`/** @var Model\Facades\RegistrationFacade @inject */
public $registrationFacade;

$grid->getDataSource()->onDataLoaded[] = function (array $registrations) {
            $this->registrationFacade->onLoadedRegistrationsAssociations($registrations);
        };
$grid->addFilterRange('countChecks', 'Search', 'countChecks')
            ->setCondition(function ($qb, $value) {

                if (!isset($value['from'])) {
                    $value['from'] = "";
                }
                if (!isset($value['to'])) {
                    $value['to'] = "";
                }

                $qb->addSelect('count(c.id) AS HIDDEN cx')
                    ->leftJoin('r.checks', 'c')
                    ->groupBy('r.id');

                if ($value['from'] != null && $value['to'] == null) {
                    $qb->andHaving('cx >= ' . $value['from']);
                } elseif ($value['from'] == null && $value['to'] != null) {
                    $qb->andHaving('cx <= ' . $value['to']);
                } elseif ($value['to'] != null && $value != null) {
                    $qb->andHaving('cx >= ' . $value['from'] . ' AND cx <= ' . $value['to']);
                }
            });
        $grid->addFilterRange('countPaidChecks', 'Search', 'countPaidChecks')
            ->setCondition(function ($qb, $value) {

                if (!isset($value['from'])) {
                    $value['from'] = "";
                }
                if (!isset($value['to'])) {
                    $value['to'] = "";
                }

                $qb->addSelect('count(x.id) AS HIDDEN cxp')
                    ->leftJoin('r.checks', 'x')
                    ->groupBy('r.id')->andWhere('x.status = ?1')->setParameter(1,'zaplaceno');

                if ($value['from'] != null && $value['to'] == null) {
                    $qb->andHaving('cxp >= ' . $value['from']);
                } elseif ($value['from'] == null && $value['to'] != null) {
                    $qb->andHaving('cxp <= ' . $value['to']);
                } elseif ($value['to'] != null && $value != null) {
                    $qb->andHaving('cxp >= ' . $value['from'] . ' AND cxp <= ' . $value['to']);
                }
            });

**RegistrationFacade**

  public function getAllRegistrationsQuery()
    {
        $query = $this->em->createQueryBuilder()
            ->select('r')
            ->from(Registration::class, 'r')
        ;
        return $query;
    }
    public function onLoadedRegistrationsAssociations($ids){
        return $this->em->createQueryBuilder()
            ->select('r,c,leader,site,team,event')
            ->from(Registration::class, 'r')
            ->where('r IN (:regs)')
            ->setParameter('regs', $ids)
            ->leftJoin('r.checks', 'c')
            ->leftJoin('r.leader', 'leader')
            ->leftJoin('r.site', 'site')
            ->leftJoin('leader.team', 'team')
            ->leftJoin('r.event', 'event')
            ->getQuery()->getResult();

    }

**Comment by juniwalk** [comment]
@jarda256 Alright, that should not be a problem. However, in `onLoadedRegistrationsAssociations`, there is `select`, you should select `partial r.{id}`, not the whole `r`.

**Comment by jarda256** [comment]
I know, that I should, but when i use partial select and than select "full" entity somewhere else I got only partial, because it's saved in identity map

**Comment by juniwalk** [comment]
@jarda256 But... you just selected full entity in first query `getAllRegistrationsQuery`, didn't you? OnDataLoaded is called after the first query is executed and finished.

**Comment by jarda256** [comment]
I did and I also know that ist after first query. But I am not sure if this can cause that "mapping problem" or not

**Comment by juniwalk** [comment]
I am not sure but I don't think so. I use ti like that without problem. This is my onDataLoaded method:
```php
/**
 * @param  Order[]  $orders
 * @return Order[]
 * @internal
 */
public function findAssociationsOf(array $orders) : array
{
	$builder = $this->createQueryBuilder('o', 'o.id')
		->select('partial o.{id}, v, c')
		->leftJoin('o.vehicles', 'v')
		->leftJoin('o.comments', 'c')
		->where('o IN (:orders)');

	try {
		$builder->getQuery()
			->setParameter('orders', $orders)
			->getResult();

	} catch (NoResultException $e) {
	}

	return $orders;
}
```

**Comment by jarda256** [comment]
I found problem...big one...when i use it like this and use sort on leader.email for example...i'll get error, because sorting takes first load not on data load

**Comment by jarda256** [comment]
@juniwalk and one more thing if i can

**Comment by juniwalk** [comment]
@jarda256 Sorting does not load data, what sort of error do you get? Your other problem seems to be nette related, you should take that to the forums or gitter.

**Comment by jarda256** [comment]
@juniwalk I got that error near 'leader.email' in select r,c from Registration join r.checks c...when leader, event,site is onDataLoaded I can't sort by it

**Comment by juniwalk** [comment]
@jarda256 How about some more information? Tracy output would be best.

**Comment by juniwalk** [comment]
@jarda256 Hello, this issue has been sitting here for a while without response. Have you resolved it?

**Comment by jarda256** [comment]
@juniwalk Hi, i am using this code. It seems to be only right solution if you want to filter by any column


        $grid->getDataSource()->onDataLoaded[] = function (array $registrations) {
            $this->registrationFacade->onLoadedRegistrationsAssociations($registrations);
        };


    public function getAllRegistrationsQuery()
    {
        $query = $this->em->createQueryBuilder()
            ->select('r,leader,site,team,event')
            ->from(Registration::class, 'r')
            ->leftJoin('r.leader', 'leader')
            ->leftJoin('r.site', 'site')
            ->leftJoin('leader.team', 'team')
            ->leftJoin('r.event', 'event')
        ;
        return $query;
    }
    public function onLoadedRegistrationsAssociations($ids){
        return $this->em->createQueryBuilder()
            ->select('r,c')
            ->from(Registration::class, 'r')
            ->leftJoin('r.checks', 'c')
            ->getQuery()->getResult();
    }

$grid->addFilterRange('countChecks', 'Search', 'countChecks')
            ->setCondition(function ($qb, $value) {

                if (!isset($value['from'])) {
                    $value['from'] = "";
                }
                if (!isset($value['to'])) {
                    $value['to'] = "";
                }

                $qb->addSelect('count(c.id) AS HIDDEN cx')
                    ->leftJoin('r.checks', 'c')
                    ->groupBy('r.id');

                if ($value['from'] != null && $value['to'] == null) {
                    $qb->andHaving('cx >= ' . $value['from']);
                } elseif ($value['from'] == null && $value['to'] != null) {
                    $qb->andHaving('cx <= ' . $value['to']);
                } elseif ($value['to'] != null && $value != null) {
                    $qb->andHaving('cx >= ' . $value['from'] . ' AND cx <= ' . $value['to']);
                }
            });
        $grid->addFilterRange('countPaidChecks', 'Search', 'countPaidChecks')
            ->setCondition(function ($qb, $value) {

                if (!isset($value['from'])) {
                    $value['from'] = "";
                }
                if (!isset($value['to'])) {
                    $value['to'] = "";
                }

                $qb->addSelect('count(x.id) AS HIDDEN cxp')
                    ->leftJoin('r.checks', 'x')
                    ->groupBy('r.id')->andWhere('x.status = ?1')->setParameter(1,'zaplaceno');

                if ($value['from'] != null && $value['to'] == null) {
                    $qb->andHaving('cxp >= ' . $value['from']);
                } elseif ($value['from'] == null && $value['to'] != null) {
                    $qb->andHaving('cxp <= ' . $value['to']);
                } elseif ($value['to'] != null && $value != null) {
                    $qb->andHaving('cxp >= ' . $value['from'] . ' AND cxp <= ' . $value['to']);
                }
            });

**Comment by juniwalk** [comment]
Yeah, this is how it should look. It is not pretty but filtering by entity method is really impossible. I am glad you sorted this out.
