### ISSUE TITLE
Sortable: Dotykové zariadenia

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#45]
Sortable neviem použiť na mobile.

**Comment by JakubKontra** [comment]
Zatím, nemá - až tak velkou prioritu. Musíme se soustředit hlavně na desktop.

**Comment by romanmatyus** [comment]
Nemalo by to zostať aspoň otvorené s nízkou prioritou?

**Comment by paveljanda** [comment]
Já neplánuji pracovat na implementaci. Pokud chceš poslat PR, budu rád.
