### ISSUE TITLE
URL refresh - with params

### ISSUE THREAD

**Issue by aleszatloukal** [ublaboo/datagrid#450]
Pristupuji k datagridu se 2 ma parametry v url, z kterych si v action udelam promenne, url vypada nazorne:

`/deliveryitemlist?delivery_id=1&commission_id=23`

Vse funguje skvele, az do doby zmeny poctu polozek na stranku, nebo jine zmeny filtru. Pak se parametry z URL smazou. A z url zustane jen tohle, scim bohuzel bez parametru nemohu pracovat
`/deliveryitemlist?deliveryitemListGrid-per_page=20`

**Comment by paveljanda** [comment]
@aleszatloukal Nepomohly by persistentní parametry?

**Comment by aleszatloukal** [comment]
Ano, nastavuji si je takto:
```
    public function actionDeliveryitemlist($delivery_id, $commission_id){
        $this->delivery_id = $delivery_id;
        $this->commission_id = $commission_id;
    }
```

a dale nasledne v datasource si taham data pro urcene delivery_id
`$grid->setDataSource($this->delivery->getDeliveryItemsListByDeliveryId($this->delivery_id));`

**Comment by paveljanda** [comment]
@aleszatloukal A používáš tyto dva parametry jako persistentní, nebo ne?

**Comment by paveljanda** [comment]
@aleszatloukal Pokud je nastavíš jako persistentní, zůstanou ti napříč requesty a nebudeš se o to muset starat.

**Comment by aleszatloukal** [comment]
@paveljanda Oba parametry mam v Presenteru jako $private 
Jak docilim pripadne toho, aby byli 'persistentni' ?

**Comment by aleszatloukal** [comment]
Supr, parametru jsem dal jako @persistent a hodil je na public a uz to bezi, diky za pomoc 👍 ✋

**Comment by aleszatloukal** [comment]
Fungovalo to, jak jsem potreboval, bohuzel jsem narazil na problem, ze dane parametry pouzivam v dalsich X action v presenteru, takze mi ten parametr nasledne hazelo i do URL, kde jsem jej nechtel, je tedy moznost to vyresit jeste jinak, nez tim persistent parametrem ?

**Comment by juniwalk** [comment]
@aleszatloukal Zkus je `NULL`ovat tam kde je nechceš, tím je smažeš. Je to teda ale řešení naprd. Muset hlídat kde parametry budou a kde ne, namísto abys jen řekl kde budou.

**Comment by aleszatloukal** [comment]
@juniwalk to mi prijde celkem nepohodlne, jelikoz mam v danem presenteru ~30 actions, lepsi by bylo dane parametry predat primo componente datagridu, aby si je k sobe zaregistroval, dalsi moznost mne napadla, resit to pomoci cookie..

**Comment by JakubKontra** [comment]
Co to je za presenter když má 30 akcí? :)

**Comment by aleszatloukal** [comment]
@JakubKontra je to presenter, pro zakazky, obstaravam v nem kompletni zakazky a veci okolo zakazek.. proto nechci pro kazdou action ten parametr nastavovat jako NULL

**Comment by paveljanda** [comment]
@aleszatloukal Akce datagridu, formuláře datagridu, zkrátka všechny akce a signály kolem datagridu jsou separátní requesty. Pokud do nich chce člověk dostat nějaké další parametry automaticky, docílí kýženého efektu právě použitím persistentních parametrů, které se budou samy držet v url napříč requesty.

Bohužel nemám jednodušší řešení.. Jedině si podědit datagrid a úplně všude přidat nějaké dodatečné parametry při sestavování akcí/signálů..

**Comment by juniwalk** [comment]
@paveljanda Jako správný fajnšmekr by měl mít datagrid stejně obalený komponentou tak si persistentní parametry může dát tam :)

**Comment by paveljanda** [comment]
No to mi nedošlo, dobrý nápad!
