### ISSUE TITLE
assableFilters what does assable stand for?

### ISSUE THREAD

**Issue by dakorpar** [ublaboo/datagrid#462]
I never heard for that word, google translate also, I found only this
http://www.urbandictionary.com/define.php?term=Assable
and just can't find any reason why this method is called that way?
I believe you wanted to call it assembleFilters maybe?
If so I can deprecate this function and name it correctly, just wished to check with you all before...

**Comment by paveljanda** [comment]
@dakorpar Yes, thanks. :) Plase send a PR..
