### ISSUE TITLE
setSortable() + parameters

### ISSUE THREAD

**Issue by sikulam** [ublaboo/datagrid#465]
Hi,
It´s possible add parameter to $grid->setSortable(). I need add next parameter. Somethings like addParameters(['foo'=>'bar']) used in action column.

**Comment by paveljanda** [comment]
@sikulam Can you please rewrite your issue to english? Thank you. :)

**Comment by paveljanda** [comment]
@sikulam You want to pass your custom parameters to the handler which takes care of sorting items?

**Comment by sikulam** [comment]
@paveljanda Yes.
I try add fourth paramer with entity name. I´ve many grids in project and try to make only one function for sort.

**Comment by paveljanda** [comment]
@sikulam Well there should be maybe a better approach in creating that datagrid in different presenter/component and soring entity name in that component/presenter property. Don't you thing?

There isn't currently implemented adding parameters to sortable handler path.

**Comment by sikulam** [comment]
@paveljanda Ok i try it. Thanks for help and fast response.
