### ISSUE TITLE
Redrawing itemDetail

### ISSUE THREAD

**Issue by MichalSeidler** [ublaboo/datagrid#466]
Existuje nějaký snadný způsob jak překreslit detail itemu bez toho aniž vy se zavřel?

Příklad: mám v detailu tlačítka, která když zmáčknu aktualizují entitu a potřebuju aby se znovu načetl detail snovými hodnotami. Když použiju $this->redrawItem($id); tak se sice překreslí ale detail se zavře.

**Comment by paveljanda** [comment]
@MichalSeidler Can you write the issue in english please? :)

**Comment by paveljanda** [comment]
@MichalSeidler there is currently no way how to do it from outside the datagrid. You can send a PR though :)
