### ISSUE TITLE
Global neon config + setTemplate params missing

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#467]
Some way to autowire some service as Kdyby/translation, var,  etc. into (filter)->setTemplate() method/template??

And exist way how set filter template for all select/text/... filters globally?
I prefer idea, create NEON config fot ublaboo datagrid with this options + set own icon class globally.

This solution is so ugly because you must configure all components separately.

Thanks a lot for response guys.

**Comment by paveljanda** [comment]
@misaon DataGrid is a standalone component. It should not have a hardcoded dependency on nette/di.

There is more elegant solution, use your own datagrid component factory and set these templates and translators in the factory. Or extend ublaboo datagrid class.

No need to use DI..

**Comment by misaon** [comment]
And first question?

**Comment by paveljanda** [comment]
Use some factory class and set all stuff you want right there.

**Comment by misaon** [comment]
ok

**Comment by misaon** [comment]
@paveljanda  Pavle, jak si do šablony pro filtr dotáhnu nějaké parametry. :D O tohle mi šlo v první fázi, jinak to s těma továrničkama chápu, já jen že máme celé systémy postavené na tvém datagridu a nastavit si někde globální classy pro ikony by bylo fajn, ale chápu tě :)

**Comment by paveljanda** [comment]
@misaon Pokud si definuješ vlastní šablonu a té šabloně nastavíš proměnné, tak by měly být vidět i v includované šabloně, tuším. Je to tak?

Případně můžeš poslat PR s podobnou funkcionalitou, jako má `Action`:

```php
{include $action->getTemplate(), item => $item, (expand) $action->getTemplateVariables(), row => $row}
```

:)
