### ISSUE TITLE
TypeError: ref is undefined 

### ISSUE THREAD

**Issue by lesho** [ublaboo/datagrid#468]
Im getting error in the Firefox's firebug console: 

> TypeError: ref is undefined datagrid.js (line 75, col 7)

Using
`     <script type="text/javascript" src="{$basePath}/js/jquery-2.2.4.min.js"></script>`

Version
` ublaboo/datagrid (v5.0.8)`

**Comment by paveljanda** [comment]
@lesho As you can see - https://github.com/ublaboo/datagrid/blob/master/assets/dist/datagrid.js#L73-L75, the ref variable is defined. Haven't you modified the js file?

**Comment by lesho** [comment]
That's right, I got it there, but TypeError present anyway

**Comment by paveljanda** [comment]
@lesho A can not see on the docu web anything like that. What OS do you use? What browser? Can you show me the console after clering browser cache and refreshing page?

**Comment by lesho** [comment]
- Checked on Windows 7 and linux  Fedora 25 on Firefox 51.0.1
- Cookies and Cached cleared
- Navigate to  [https://ublaboo.org/datagrid/edit](https://ublaboo.org/datagrid/edit) in new private window
- Open Firebug console
- Click on the data row 
- Console output is same as in previous comments

**Comment by elring** [comment]
Hi. I get this error too. On my project and on demo pages https://ublaboo.org/datagrid/ it's visible too - just click anywhere (for example on header of the grid) - Firefox/IE. Error variable is different (on demo page it's m), because they use minified/compiled versions of datagrid.js, but it's the same error.

**Comment by BigOHenry** [comment]
Same here. You click anywhere and got that error.

**Comment by paveljanda** [comment]
Fixed
