### ISSUE TITLE
DataGrid::addGroupTextareaAction example

### ISSUE THREAD

**Issue by romanmatyus** [ublaboo/datagrid#471]
```DataGrid::addGroupTextareaAction``` is not in [example](https://ublaboo.org/datagrid/group-action).

**Comment by paveljanda** [comment]
@romanmatyus So?

**Comment by romanmatyus** [comment]
Can be added to a live demonstration?

**Comment by paveljanda** [comment]
@romanmatyus Sorry, there are no styles for it. But it is pretty simple to use....
