### ISSUE TITLE
Chybné zobrazení datagridu při groupAction

### ISSUE THREAD

**Issue by xpackal5** [ublaboo/datagrid#472]
Ahoj. Chybka při zobrazování tabulek, kde se používají groupAction

Pokud je tabulka bez nalezených dat (např. defaultně vyfiltrovaná) -> chybí sloupec s fajfkama ke groupActions, jakmile filtr změním a nějaká data se objeví, přidá se sloupec s fajfkama, ale v hlavičce zůstane původní rozložení, tj sloupec s fajfkama se přiřadí k hlavičce prvního sloupce atd. děje se to jenom při Ajaxu. Nakonec počet sloupců v hlavičce je menší než počet sloupců v tabulce
![2017-02-26-105420_1280x800_scrot](https://cloud.githubusercontent.com/assets/17193365/23338714/6ffa86a4-fc12-11e6-82c6-b8f58ac29f76.png)

**Comment by lesho** [comment]
Did you tried to use required columns only from the tables? I have had similar issue with `select * from XYZ join ...`

**Comment by paveljanda** [comment]
@xpackal5

1) Can you please write the issues in EN? Thanks.
2) What version of ublaboo/datagrid are you using? And version of assets?

**Comment by xpackal5** [comment]
Hi. Sorry for Czech, but it was faster for me :-)
I have fresh Ublaboo/Datagrid (5.0.8) and assets too. I am using model class that implements IDataSource a return Array.

**Comment by xpackal5** [comment]
You can view this bug on DEMO page too. Try [https://ublaboo.org/datagrid/?examplesGrid-filter%5Bname%5D=xxx] and then delete xxxx from filter. You can see that header of table is displaced Check collumns is on ID, ID is on NAME and NAME is on LINK
![2017-02-26-180131_1280x800_scrot](https://cloud.githubusercontent.com/assets/17193365/23341745/c5d3af5c-fc4d-11e6-8abc-f78ddf5872d5.png)

**Comment by paveljanda** [comment]
@xpackal5 Aah, I see. Thanks for the report. WIll fix it.

**Comment by xpackal5** [comment]
I try this hack.
`<tr n:block="header-column-row">
    {var $isGroupAction=$control->hasGroupActions()}
    <th n:if="$isGroupAction" rowspan="2" class="col-checkbox">
	<input n:class="$control->useHappyComponents() ? 'happy gray-border' , primary" name="{$control->getName()|lower}-toggle-all" type="checkbox" data-check="{$control->getName()}" data-check-all="{$control->getName()}">
    </th>`
And it seems to be ok.

**Comment by paveljanda** [comment]
@xpackal5 Is it still broken? Can not replicate it..
