### ISSUE TITLE
[IDEA] Context Menu

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#484]
Hello guys. 
What do you think about the idea on the context menu of the operation for the rows (delete, edit, move up/down, etc.). It can be a substitute for select/multiselect actions (better UI impletmetace). 
A similar solution uses tables in Redmine system and the solution I like.

![0](https://cloud.githubusercontent.com/assets/15806356/23542618/803509ec-ffee-11e6-9d9f-9ef40ee246d2.png)

What do you think about it @paveljanda ?

**Comment by juniwalk** [comment]
I don't like context menus on websites. Feels unnatural and also is not that great for mobiles.

**Comment by paveljanda** [comment]
I also don't think is netural. Otherwise all other UI components would use it.
