### ISSUE TITLE
Doctrine relations

### ISSUE THREAD

**Issue by misaon** [ublaboo/datagrid#487]
CZ:
Zdravím, řeším teď jeden problém. Začínám s Doctrine a mám problém s Ublaboo a vazbou ONE-TO-MANY. Konkrétně že jeden web může mít více "contents" (jazykových mutací). Inspiraci jsem čerpal zde:
https://ublaboo.org/datagrid/data-source#orm-relations
Toto skvěle funguje u vazby ONE-TO-ONE.

(Komponenta):
```
$grid->addColumnText('templateName', 'Šablona', 'template.name');
```

(Entita):
```
/**
   * @ORM\OneToOne(targetEntity="Template")
   * @ORM\JoinColumn(name="template_id", referencedColumnName="id")
   */
public $template;
```

**Chci ale nyní udělat něco v tomto slova smyslu:**
(Komponenta):
```
$grid->addColumnText('webSiteName', 'Název', 'webSiteContents.name');
```
(Entita from):
```
/**
   * @ORM\OneToMany(targetEntity="WebSiteContent", mappedBy="webSite")
   */
public $webSiteContents;
```

(Entita to):
```
/** @ORM\Column(type="string", length=100) */
public $name;

/**
   * @ORM\ManyToOne(targetEntity="WebSite", inversedBy="webSiteContents")
   * @ORM\JoinColumn(name="web_site_id", referencedColumnName="id")
    */
public $webSite;
```
Dostanu ale chybu:
Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "Doctrine\ORM\PersistentCollection".

Můžete mě prosím nasměrovat správným směrem? Díky moc 👍

**Comment by paveljanda** [comment]
@misaon I'm so sorry, but these issues and pull requests are strictly in english.

If you need help in czech, please visit official nette forum.

**Comment by juniwalk** [comment]
@misaon Musíš si buď napsat funkci, co ti vráti jen jednu entitu content nebo udělej:
```php
$grid->addColumnText('webSiteName', 'Název', 'webSiteContents[0].name');
```
Viz index 0, tím říkáš aby použil entitu na indexu 0.
