### ISSUE TITLE
TreeView: Chevron icon is misplaced

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#49]
Chevron icon is almost in the middle of the table with nothing to the left. Check the picture.

![gatagrid-treeview](https://cloud.githubusercontent.com/assets/451918/12812492/7bc15344-cb32-11e5-9846-7362a4850252.jpg)

**Comment by juniwalk** [comment]
My browser is `Firefox Developer Edition 46.0a2 (2016-01-31)`

**Comment by paveljanda** [comment]
There is a weird behaviour of css proprty `justify-content: space-between;`. I will take a look at it.

**Comment by juniwalk** [comment]
Great! Thanks. :)

**Comment by juniwalk** [comment]
@paveljanda Thank you so much for this fix!
