### ISSUE TITLE
Firefox: Event.path není definován

### ISSUE THREAD

**Issue by jasir** [ublaboo/datagrid#497]
Zdravím,

event.path není standartní property (jen v chrome) a proto ve firefoxu nefunguje (a hazí chyby).
Neumím coffeescript, takže si nedovolím skutečný pull request, ale zde je fix:

https://github.com/jasir/datagrid/commit/6c239f5f8096fa8ee2f2883b0d2267e67a8d865d

Díky za zvážení :)

**Comment by paveljanda** [comment]
@jasir 
Cool. Can you please check for e.path and if it exists, return that?

Thanks

**Comment by jasir** [comment]
Thanx!
