### ISSUE TITLE
Demo/Items per page: Error 500

### ISSUE THREAD

**Issue by wodCZ** [ublaboo/datagrid#50]
When I choose All results per page on [demo](http://ublaboo.paveljanda.com/datagrid/), server responds with error 500.

While I understand why this happens, it probably shouldn't on demo (It looks like it doesn't work, without any feedback to user).

Also, All is not translated, Vše is shown instead.

**Comment by paveljanda** [comment]
Good idea. I will simply cut the number of items in database down.

Thanks.
