### ISSUE TITLE
Support for column styling (<colgroup> or <col> elements)

### ISSUE THREAD

**Issue by matej116** [ublaboo/datagrid#503]
I would like to have table-layout: fixed width fixed column size, but I am not able to set width to the columns. In tables with table-layout:fixed is the width of the column determined by width of <td> or <th> in first row, but the first row in datagrid (mostly) is spanned accross all columns. Is there some solution to this I have overlooked? Thanks.

**Comment by paveljanda** [comment]
@matej116 You can always use your own template that will inherit from datagrid.latte :)
