### ISSUE TITLE
Group action loses grid state in URL

### ISSUE THREAD

**Issue by proki** [ublaboo/datagrid#509]
Try [https://ublaboo.org/datagrid/?examplesGrid-page=3&examplesGrid-per_page=10&examplesGrid-filter%5Bstatus%5D%5B0%5D=2], select any item and then execute any group action.

After executing group action and reload grid component in presenter, grid lost filtering and paging state.

**Comment by paveljanda** [comment]
@proki Once in a time there are sessions automatically cleared on docu web. It was probably that case. It forks fine normally. :)
