### ISSUE TITLE
Example of handleSort()

### ISSUE THREAD

**Issue by stinky23** [ublaboo/datagrid#51]
Does have somebody example of processing sorting? I can't get over it. I know it is not any issue, but I don't know how to right process it in database.

**Comment by martinknor** [comment]
you get three parameters at handleSort - $item_id, $prev_id, $next_id
for example if you have column priority or order (number in database), you can set priority for $item_id = $prev_id_priority + 1 and on all items > $next_id set priority = priority + 1
