### ISSUE TITLE
Bad rendering of all columns into the first

### ISSUE THREAD

**Issue by radekdostal** [ublaboo/datagrid#519]
In some grids (I don't know why only in some) during the first view of the grid, all columns are rendered into the first, see:
![grid](https://cloud.githubusercontent.com/assets/375717/25274078/cd585352-268e-11e7-9894-82c595a86e90.png)
After going to the next page and going back, or after sorting, the rendering is ok. It was fine in the version 5.1.2.

When I remove ```n:block="tbody"``` from https://github.com/ublaboo/datagrid/blob/v5.2.2/src/templates/datagrid.latte#L233 then rendering is ok.

**Comment by juniwalk** [comment]
Interesting, I will look into it.

**Comment by juniwalk** [comment]
I am unable to replicate this issue, can you check documentation site if you see the same issue?

**Comment by radekdostal** [comment]
The problem is occured on grid, where exists column defined as addColumnDateTime() and has defined filter with setFilterDate(). When I replace setFilterDate() with setFilterText(), then grid is rendered fine.

**Comment by radekdostal** [comment]
On bad rendered grid, URL doesn't contain grid-sort parameters. If grid is sorted or I'll go to the next page and back again, URL contains grid-sort parameters and grid is rendered fine.

**Comment by paveljanda** [comment]
@radekdostal Can you please make and sandbox-like project with for example sqlite database that would replicate your issues? Thanks!

**Comment by radekdostal** [comment]
@paveljanda I'm just working on the sandbox and it's interesting that I don't use netteForms.js, grid is rendered perfectly. I'm forced to use Nette 2.3.10. Nette 2.4 is ok. So I have to prepare that sandbox?

**Comment by radekdostal** [comment]
@paveljanda Here is the sandbox: [sandbox.zip](https://github.com/ublaboo/datagrid/files/949254/sandbox.zip)
