### ISSUE TITLE
What is correct way to aply datagrid and add sort on entity (doctrine)

### ISSUE THREAD

**Issue by jarda256** [ublaboo/datagrid#529]
Hi, I would like to ask. What is correct way to aply datagrid and add sort on entity list. My quess is this, but I think, that i missed something

Add this to entity.php
`
	/**
	 * @ORM\Column(name="`order`", type="integer")
	 */
	private $order = 0;

	public function setOrder($order)
	{
		$this->order = $order;
	}
	public function getOrder()
	{
		return $this->order;
	}
`

Create simple datagrid
`
	protected function createComponentAdminTreeGrid($name)
	{
		$qb = $this->em->createQueryBuilder();
		$qb->select('c')
			->from(Cat::class, 'c')
			->where('c.parent = 72')
			->orderBy('c.order');

		$grid = new DataGrid($this, $name);

		$source = new DoctrineDataSource($qb, 'id');
		$grid->setDataSource($source);
		$grid->setSortable();

		$grid->addColumnText('title', 'Title');
		$grid->addColumnText('id', 'Id');
		return $grid;
	}
`
And copy handleSort function from documentation

**Comment by paveljanda** [comment]
My solution is this (maybe not the best):

```php
public function handleSort(?string $item_id, ?string $prev_id, ?string $next_id): void
{
	$this->sortEntity(
		$this->em,
		ProductParameter::class,
		'sort',
		(int) $item_id,
		$prev_id ? (int) $prev_id : NULL,
		$next_id ? (int) $next_id : NULL
	);

	$this->flashMessage('Pořadí parametrů uloženo', 'success');
	$this->redrawControl('flashes');
}
```
trait TEntitySort
{

	public function sortEntity(
		EntityManager $em,
		string $entityClass,
		string $sortColumn,
		int $itemId,
		?int $previd,
		?int $nextId
	): void {
		$repository = $em->getRepository($entityClass);
		$item = $repository->find($itemId);
		$sortColumnGetter = 'get' . ucfirst($sortColumn);
		$sortColumnSetter = 'set' . ucfirst($sortColumn);

		/**
		 * 1, Find out order of item BEFORE current item
		 */
		if (!$previd) {
			$previousItem = NULL;
		} else {
			$previousItem = $repository->find($previd);
		}

		/**
		 * 2, Find out order of item AFTER current item
		 */
		if (!$nextId) {
			$nextItem = NULL;
		} else {
			$nextItem = $repository->find($nextId);
		}

		/**
		 * 3, Find all items that have to be moved one position up
		 */
		$itemsToMoveUp = $repository->createQueryBuilder('i')
			->where("i.{$sortColumn} <= :sortColumn1")
			->setParameter('sortColumn1', $previousItem ? $previousItem->{$sortColumnGetter}() : 0)
			->andWhere("i.{$sortColumn} > :sortColumn2")
			->setParameter('sortColumn2', $item->{$sortColumnGetter}())
			->getQuery()
			->getResult();

		foreach ($itemsToMoveUp as $t) {
			$t->{$sortColumnSetter}($t->{$sortColumnGetter}() - 1);
			$this->em->persist($t);
		}

		/**
		 * 3, Find all items that have to be moved one position down
		 */
		$itemsToMoveDown = $repository->createQueryBuilder('i')
			->where("i.{$sortColumn} >= :sortColumn1")
			->setParameter('sortColumn1', $nextItem ? $nextItem->{$sortColumnGetter}() : 0)
			->andWhere("i.{$sortColumn} < :sortColumn2")
			->setParameter('sortColumn2', $item->{$sortColumnGetter}())
			->getQuery()
			->getResult();

		foreach ($itemsToMoveDown as $t) {
			$t->{$sortColumnSetter}($t->{$sortColumnGetter}() + 1);
			$this->em->persist($t);
		}

		/**
		 * Update current item order
		 */
		if ($previousItem) {
			$item->{$sortColumnSetter}($previousItem->{$sortColumnGetter}() + 1);
		} else if ($nextItem) {
			$item->{$sortColumnSetter}($nextItem->{$sortColumnGetter}() - 1);
		} else {
			$item->{$sortColumnSetter}(1);
		}

		$this->em->persist($item)->flush();
	}

}
```php

```
