### ISSUE TITLE
allowRowsAction not work on multiAction

### ISSUE THREAD

**Issue by zemnet** [ublaboo/datagrid#530]
Hi
I have this problem.
How can I do allowRowsAction() on multiAction?

Thank you

**Comment by paveljanda** [comment]
allowRowsGroupAction

**Comment by paveljanda** [comment]
allowRowsAction

**Comment by paveljanda** [comment]
@zemnet Show me your code, I will add the allow method

**Comment by zemnet** [comment]
`$grid->addMultiAction('multi_action', '')->addAction('fakturaform','Upraviť','Faktury:fakturaform');`

`        $grid->allowRowsAction('fakturaform', function($item) {
        	 return !$item->pdf;
        });`

**Comment by paveljanda** [comment]
@zemnet Sure, do that also with the multi action column:

```php
$grid->allowRowsAction('multi_action', function($item) { return false; });
```

**Comment by zemnet** [comment]
But I need to allow second action 'fakturaform'...

**Comment by paveljanda** [comment]
@zemnet Oh I see. So set two `MultiAction`s with different actions. Then allow one or another. Hm? :)

**Comment by zemnet** [comment]
‎Yes, maybe can be.I occured to me also.But i have some actions that cannot be done.But i will test it,Thank you.                                                                                                                                                                                                                                                                                                                                        Viktor :)Odesláno z BlackBerry 10...Kto chce, hľadá spôsoby, kto nechce, hľadá dôvody!                                                                                                                                                                                                                Od: Pavel JandaOdesláno: streda, 10. mája 2017 17:47Komu: ublaboo/datagridOdpovědět: ublaboo/datagridKopie: Viktor Szőke; MentionPředmět: Re: [ublaboo/datagrid] allowRowsAction not work on multiAction (#530)@zemnet Oh I see. So set two MultiActions with different actions. Then allow one or another. Hm? :)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ublaboo/datagrid","title":"ublaboo/datagrid","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ublaboo/datagrid"}},"updates":{"snippets":[{"icon":"PERSON","message":"@paveljanda in #530: @zemnet Oh I see. So set two `MultiAction`s with different actions. Then allow one or another. Hm? :)"}],"action":{"name":"View Issue","url":"https://github.com/ublaboo/datagrid/issues/530#issuecomment-300525533"}}}

**Comment by FilipLukac** [comment]
If possible, I vote up, to add method like `allowRowsMultiAction('parent','key',callable)` or something like that.

**Comment by paveljanda** [comment]
Viz https://ublaboo.org/datagrid/row#allow_action_of_multi_action

I will release it in a couple hours
