### ISSUE TITLE
Strange item detail functions

### ISSUE THREAD

**Issue by xpackal5** [ublaboo/datagrid#531]
Hi. 
It is some strange function of item detail handler. Normally works ok, but i need ajaxify whole app and then if i close {block content} of page into snippet the item detail not work (detail is not redraw item detail, but whole datagrid, which will be empty).
I can describe problem detailly in Czech if needed.
Milan

**Comment by paveljanda** [comment]
Try encapsulating whole datagrid into some control. You won't lose ajaxification and it should be all fine. :)

I don't really know, where your problem lies, but it is not probably in datagrid. :)
