### ISSUE TITLE
Add $row to onClick[] callback of addActionCallback()

### ISSUE THREAD

**Issue by foxycode** [ublaboo/datagrid#534]
It would be nice to have `$row` parameter also when using `addActionCallback()`. Currently there is only id and programmers under me tend use solutions like this:

```php
$grid->addActionCallback('settings', 'Nastavení')
    ->setIcon('pencil')
    ->onClick[] = function ($mergerid) use ($grid) {
        $this->application->getPresenter()->redirectUrl($this->linkGenerator->link(
            'Advertiser:AdvertiserFeedMerger:',
            ['advertiserid' => $grid->getDataSource()->getData()[$mergerid]->advertiserid]
        ));
    };
```

**Comment by paveljanda** [comment]
1, You should start using PHP 5.6 and newer :P
2, That is not really the point of action callback, you can use normal action with custom values... Easy peasy

**Comment by foxycode** [comment]
1. We are using PHP 7.1 on this project
2. As you can see, `advertiserid` is used in link, not `mergerid` (primary key), so I can't use action, because action uses only primary key from data. Or am I missing something?

**Comment by paveljanda** [comment]
1, `function ($mergerid) use ($grid) {` - no need to use `use ($grid)` anymore since 5.6 :P
2, Yes you are. https://ublaboo.org/datagrid/column#column-link - you can pass any parameters you want (Same as in `Action`). Or you can use your own renderer and link. Or your own template.

You should read the doc more carefully man. :D

**Comment by paveljanda** [comment]
@foxycode :D Sorry, my bad. Little tired. I though you are using `$this->grid`.. Never mind.

Anyway, `Action`, `ColumnLink` will help you with these parameters.

**Comment by paveljanda** [comment]
@foxycode Maybe something like that?

```php
$grid->addAction('settings', 'Nastavení', 'Advertiser:AdvertiserFeedMerger:', ['advertiserid'])
	->setIcon('pencil');
```

**Comment by foxycode** [comment]
Great, thank you very much 👍
