### ISSUE TITLE
Big inline edit Date

### ISSUE THREAD

**Issue by jarda256** [ublaboo/datagrid#536]
Hi can I somehow inline edit Date object? If I use this i get "Object of class DateTime could not be converted to string
"
`
		/**
		 * Big inline editing
		 */
		$grid->addInlineEdit()
			->onControlAdd[] = function ($container) {
			$container->addText('name', '');
			$container->addText('surname', '');
			$container->addText('email', '');
			$container->addText('birthdate', '');
		};

		$grid->getInlineEdit()->onSetDefaults[] = function ($container, $item) {
			$container->setDefaults([
				'id' => $item->id,
				'name' => $item->name,
				'surname' => $item->surname,
				'email' => $item->email,
				'birthdate' => $item->birthdate->format('j. n. Y'),
			]);
		};

		$grid->getInlineEdit()->onSubmit[] = function ($id, $values) {
			/**
			 * Save new values
			 */
			$this['showDataGrid']->redrawItem($id);
			$this->flashMessage('Record was updated! (not really)', 'success');
			$this->redrawControl('flashes');
		};

		$grid->getInlineEdit()->setShowNonEditingColumns();
`

**Comment by paveljanda** [comment]
Well it is working in docu homepage. :)

**Comment by paveljanda** [comment]
@jarda256 If you came acroos wrong behaviour on docu homepage, please reopen this issue and tell me please where the problem is.
I can't really reproduce wrong behaviour in my code..

Or send me a sandbox-like project with your broken code. :)
