### ISSUE TITLE
Nastavení SetAjax for group actions

### ISSUE THREAD

**Issue by sinacek** [ublaboo/datagrid#540]
Ahoj,
chtěl bych se zeptat, jestli by bylo možné přidat možnost setAjax na formulář (https://github.com/ublaboo/datagrid/blob/v5.x/src/templates/datagrid.latte#L23). Potřebuju pomocí group actions vrátit soubor s jejich údajema a když to je v ajaxu, tak to nejde. Zároveň to potřebuju jen na vybrané položky, tedy nelze použít jen Export. 
Díky
PS: na tohle můžu i poslat PR, ale nevím jestli tě nenapadně jiné a lepší řešení jak to udělat.

**Comment by paveljanda** [comment]
Ten formulář je ajaxový. Přesně jak jsi ukázal v tom latte na githubu


On June 3, 2017 at 15:37:30, František Hána (notifications@github.com) wrote:

Ahoj,
chtěl bych se zeptat, jestli by bylo možné přidat možnost setAjax na formulář (https://github.com/ublaboo/datagrid/blob/v5.x/src/templates/datagrid.latte#L23). Potřebuju pomocí group actions vrátit soubor s jejich údajema a když to je v ajaxu, tak to nejde. Zároveň to potřebuju jen na vybrané položky, tedy nelze použít jen Export.
Díky
PS: na tohle můžu i poslat PR, ale nevím jestli tě nenapadně jiné a lepší řešení jak to udělat.

**Comment by sinacek** [comment]
Já právě potřebuju tu možnost vypnout, aby ajaxový nebyl a já mohl odeslat zpět soubor, vytvořený na základě vybraných položek.

**Comment by paveljanda** [comment]
To si budeš muset pravděpodobně podědit šablonu a upravit podle sebe


On June 5, 2017 at 09:09:15, František Hána (notifications@github.com) wrote:

Já právě potřebuju tu možnost vypnout, aby ajaxový nebyl a já mohl odeslat zpět soubor, vytvořený na základě vybraných položek.
