### ISSUE TITLE
New dibi

### ISSUE THREAD

**Issue by jannemec** [ublaboo/datagrid#547]
For new dibi version there is change \DibiFluent class becomes \Dibi\Fluent
in DibiFluentDatasource.php should be
----------------------------
	/**
	 * @var DibiFluent
	 */
	protected $data_source;
	/**
	 * @var array
	 */
	protected $data = [];
	/**
	 * @var string
	 */
	protected $primary_key;
	/**
	 * @param DibiFluent $data_source
	 * @param string $primary_key
	 */
	public function __construct(DibiFluent $data_source, $primary_key)
-----------------------------
replaced by
----------------------------
	/**
	 * @var \Dibi\Fluent
	 */
	protected $data_source;
	/**
	 * @var array
	 */
	protected $data = [];
	/**
	 * @var string
	 */
	protected $primary_key;
	/**
	 * @param \Dibi\Fluent $data_source
	 * @param string $primary_key
	 */
	public function __construct(\Dibi\Fluent $data_source, $primary_key)
-----------------------------

**Comment by paveljanda** [comment]
@jannemec But there are still aliases for old namespaces, right?

**Comment by jannemec** [comment]
You are right - I got one version of dibi, where this alias was missing.

**Comment by Tomas2D** [comment]
Just create alias for old Dibi Fluent class.

`class_alias('Dibi\Fluent', 'DibiFluent');`
