### ISSUE TITLE
AJAX: Send only datagrid snippets

### ISSUE THREAD

**Issue by wodCZ** [ublaboo/datagrid#55]
In my project, I have `$this->redrawControl()` in startup in BasePresenter. As I want to redraw all snippets by default (and change this in render methods if needed).

However this breaks datagrid filtering, because in response I also get parent snippet, which redraws whole content (with grid).

I propose adding `$this->getPresenter()->redrawControl(NULL, FALSE)` [here](https://github.com/ublaboo/datagrid/blob/master/src/DataGrid.php#L1196), which solves whole problem.

I'm not sure if this is BC break, but it could be avoided by adding `onlyRedrawGrid` option or something.

Also, `onReload` event would do the job (where I would call redrawControl(NULL, FALSE) myself).

I'm migrating from o5/grido, where on grid manipulation (filtering, paginating, ..) only grid snippets are returned no matter what I choose to redraw.

**Comment by paveljanda** [comment]
I think adding this line `$this->getPresenter()->redrawControl(NULL, FALSE)` wouldn't be right. It is a hack, not a solution. When you are redrawing all snippets in presenter, there of course have to be all snippets invalidated.

`onReload ` event is perfect solution. I will add that to the next version. Should i pass some arguments to the `onReload ` event? For example a list of snippets to reload, or something else?

**Comment by wodCZ** [comment]
As I look closely on the code, it looks like I'll have problem on more places (in signals you are redrawing controls aside of reload method - `redrawItem`, `handleGetItemDetail`, `handleGetChildren`).

So at this time, `onReload` event wouldn't solve this problem and would be wtf, as it is not really called on every grid interaction.

I'm not sure whether you can provide me any "grid changed" event or not.
I'll have a closer look if I can detect this without changes in datagrid, as you (and your code) is right that it's my problem.

PS: thanks for your fast reply! :)

**Comment by paveljanda** [comment]
Well, firing `onReload` event would make sense in each of methods you mentioned. At least if it won't be called `onReload`, but `onRedraw`.

The code is a little bit inconsistent, you're right. I will fix that later.

**Comment by wodCZ** [comment]
That'd be great!

I can't image what any would need in that event as parameter, probably list of snippets would be enough. 

Thank you.

**Comment by paveljanda** [comment]
A added onRedraw event. I will be availible in next version.
