### ISSUE TITLE
FilterableDataSource::filter getConditionCallback data_source reference

### ISSUE THREAD

**Issue by mrceperka** [ublaboo/datagrid#559]
Hi,
I have `data_source` which is an `array`. I've used `setCondition` at `filter` component for custom filtering.

----------

Now, because my `data_source` is  `array`, it will not be passed as `object` would. Hotfix is easy, just add `&` before `$this->data_source`.

```php
public function filter(array $filters)
{
	foreach ($filters as $filter) {
		if ($filter->isValueSet()) {
			if ($filter->hasConditionCallback()) {
				Callback::invokeArgs(
					$filter->getConditionCallback(),
				      // ↓ CHANGE HERE
					[& $this->data_source, $filter->getValue()]
				);
			} else {
               	              //	...
			}
		}
	}

	return $this;
}
```
 

----------

* What do you think of this? 
* Should I wrap my `array` `data_source` to `object` just because of this?
* Do you have any better solution?

----------

Or, you could stop mutating the dara source with callback and instead require it to return new `data_source`...

**Comment by mrceperka** [comment]
Got [pull request](https://github.com/mrceperka/datagrid/blob/v5.x/src/DataSource/FilterableDataSource.php) ready with this one line fix.

**Comment by mrceperka** [comment]
Bump. What do u think @paveljanda

**Comment by paveljanda** [comment]
@mrceperka Why don't you just return the filtered array in you condition callback?

**Comment by mrceperka** [comment]
How would that help? It is all based on modifying existing `data_source`.
I do not see any
 ```php 
$this->data_source = Callback::invokeArgs(...)
```

**Comment by paveljanda** [comment]
Right. Do this than:

```php
Filter::setCondition(function(& $data, $value) { ... });
```

**Comment by paveljanda** [comment]
I should mention that in docu. Hmmm

**Comment by mrceperka** [comment]
that will probably yell at me, that variable that i am expecting is not passed via refference...

**Comment by paveljanda** [comment]
```php
<?php

function fooMe(& $foo)
{
	$foo = 'foo';
}

$a = 'a';

fooMe($a);

echo $a;
```

**Comment by mrceperka** [comment]
Fine, I've propably did not try this little hack of yours. Thank you.

**Comment by paveljanda** [comment]
Well it's not a hack. :D

It's just that I am trying to make it work similar way as the fluent interface of Dibi\Fluent and other objects that change themselves with every method called above them.

**Comment by mrceperka** [comment]
Yes, I've seen those 'self mutating' collections. Better approach is returning new collection. But this is propably better (or easier?) solution for compatibility. Or you can CLONE them all :D
