### ISSUE TITLE
Filters - Submit button render location

### ISSUE THREAD

**Issue by BigOHenry** [ublaboo/datagrid#569]
Hello,
is any way to add the option to the filter submit button where it should render? I think the Action column its not the best place always. 

Right now, i need to set AutoSubmit to FALSE and at the same time i dont have any action for rows (so no action column). I edited the datagrid.latte and changed the possition of the button to the toolbar (before the gear button).

So please can you add some option, where it should be rendered? Somethink like setRenderToolbox(true).

Thank you very much

**Comment by paveljanda** [comment]
You can send a PR :)

**Comment by BigOHenry** [comment]
okey, i will try it tonight :)
