### ISSUE TITLE
How to add variable to template file?

### ISSUE THREAD

**Issue by devpcz** [ublaboo/datagrid#57]
Hi,
I want to add some variable to template file. It should be used here:

`{extends $original_template}
{define col-age}
	{$item} {$myOwnVariable}
{/define}`

Please, how to do it?
Maybe, it's beginners issue... sorry.

Thnx
Pavel

**Comment by paveljanda** [comment]
Well that particular case could be done like this:

```php
$grid->addColumnText('name', 'Name')
    ->setTemplate('blah.latte', ['myOwnVariable' => 'foo']);
```

Second argument to function `setTemplate` is a list of variables that will be passed to template file (expanded). See docu: http://ublaboo.paveljanda.com/datagrid/column -> Templates.

**Comment by paveljanda** [comment]
Aaaa, sorry, i am answering something else. Wait a bit :D

**Comment by paveljanda** [comment]
Class `Nette\Application\UI\Control` has method `getTemplate`, co you can set a global variable:

```php
$grid->getTemplate()->myOwnVariable = 'foo';
```

I will probably add a method `Column::setTemplateVariables` and argument of that method will be expanded to the defined block same way as using column template.

**Comment by devpcz** [comment]
Thank you.

Only one solution which funcions is to add variable in any presenter method (e.g. render*() method):
`$this['myGrid']->getTemplate()->myOwnVariable = 'content';`

Your solution (you wrote it not for me) `$grid->addColumnText('name', 'Name')->setTemplate('blah.latte', ['myOwnVariable' => 'foo']);` is also possible.

If I add variable in createComponentMyGrid() method

`$grid->getTemplate()->myOwnVariable` = 'content';`

then Tracy says that

`Component '' is not attached to 'Nette\Application\UI\Presenter'`.

So I tried to set parent to grid

`$grid->setParent($this);`

Tracy: `Component '' already has a parent`

Thank you for your work!

**Comment by paveljanda** [comment]
Try that:

$grid = new DataGrid($this, 'myGrid');

$gris->getTemplate()->myOwnVariable = 'content';

**Comment by paveljanda** [comment]
Did that help? Or are you having some other problems?

**Comment by devpcz** [comment]
I'm sorry that I did not reply.
Yes, your solution helped me.
I tried Ublaboo/DataGrid, I solved all my problems and now I don't have any questions.

Good job!
