### ISSUE TITLE
Not working template

### ISSUE THREAD

**Issue by MichalSzekeres** [ublaboo/datagrid#585]
Hi, I am new to nette and ublaboo DataGrid .. and I have this problem :  I see the data from database ( and they are correct ) but I just dont see that great template in it ...  I have to be doing something wrong ... 

![ssss](https://user-images.githubusercontent.com/22456043/31813834-fe0a04b8-b587-11e7-9609-7130e8857692.png)

**Comment by paveljanda** [comment]
@MichalSzekeres Did u use all necessary assets?
