### ISSUE TITLE
datagrid in component - action link problem

### ISSUE THREAD

**Issue by zelina** [ublaboo/datagrid#592]
If datagrid is used in component, action link (for signal!) is not generated properly. Exception for invalid link is throwed.

Problem is probably here:
https://github.com/ublaboo/datagrid/blob/06f364e3fbf5db2d6eae96705af4973a66da7c8d/src/Traits/TLink.php#L29

in component have to be:
$parent = $grid->getParent()->getParent(); // code could say more than thousands words ;)

then it generates proper action link (for signal!).

**Comment by zelina** [comment]
Could this be as a solution?

protected function createLink(DataGrid $grid, $href, $params)
	{
		try {
			$parent = $grid->getParent();

			if (Strings::endsWith($href,'!')) {
				$parentClass = ClassType::from($parent);

				while (!$parentClass->hasMethod('handle' . Strings::capitalize(Strings::trim($href, '!')))) {
					$parent = $parent->getParent();
					$parentClass = ClassType::from($parent);
				}
			}

			return $parent->link($href, $params);
		} catch (DataGridHasToBeAttachedToPresenterComponentException $e) {
			$parent = $grid->getPresenter();

		} catch (\InvalidArgumentException $e) {
			$parent = $grid->getPresenter();
		}

		return $parent->link($href, $params);
	}

**Comment by radekdostal** [comment]
I think, this is an BC break. When I have this action (datagrid as component):

`$grid->addAction('movie', '', 'Movie:edit', ['id' => 'movie_id']);`

It ends with "Component with name 'Movie' does not exist."

**Comment by paveljanda** [comment]
@radekdostal Aj, that should not.. can you try `v5.5.1`?

**Comment by radekdostal** [comment]
@paveljanda Yes, v5.5.1 seems to be OK.
