### ISSUE TITLE
DataGrid with Instante Extended form macros conflict

### ISSUE THREAD

**Issue by j23bax** [ublaboo/datagrid#594]
Hi, there is a problem when I'm trying to use DataGrid beside Extended Form Macros from instante (i am extending his form renderer, so I need them for manual form rendering in some cases). 
When you click on 'next' button in paginator, `Undefined property: stdClass::$formsStack` Notice shows up. It's appearing in datagrid template files on lines with `input`, `label` and `form` macros.
It would be nice if You could fix this, so we can use DataGrid beside ExtendedFormMacros. Thanks in advance, LN.

**Comment by paveljanda** [comment]
I don't really understand what you want to achieve. Can you show me an example?

**Comment by j23bax** [comment]
When I'm trying to use DataGrid in project, where [ExtendedFormMacros from instante](https://github.com/instante/extended-form-macros) extension is wired, Exception `Undefined property: stdClass::$formsStack` appear when I click on paginator, i.e..  It's because of DataGrid template using `{input}` and `n:name` etc.. latte macros, which are being overriden by ExtendedFormMacros mentioned above. LN

**Comment by paveljanda** [comment]
@j23bax You can try extending datagrid and add formsStack to the template. I don't really know how `instante/extended-form-macros` works..
