### ISSUE TITLE
Doctrine hydration mode

### ISSUE THREAD

**Issue by jaroslavrehorka** [ublaboo/datagrid#595]
Hi,

if I need to set hydration mode for example to _HYDRATE_SCALAR_, is there any supported way to do so? I have managed to achieve this behaviour by extending _DoctrineDataSource_, but I'm not sure if I'm not reinventing wheel.

Thanks

**Comment by juniwalk** [comment]
Hello,
there is no option to set hydration mode.

Why do you need to hydrate to scalar in datagrid?

**Comment by jaroslavrehorka** [comment]
Ok, thanks.

Because I'm joining multiple tables via DQL which results in something similar to this https://stackoverflow.com/questions/38836366/doctrine-dql-returning-flat-array-from-join, so to flatten and normalize record I use scalar hydration (the join depends on dynamic variable). Otherwise for joining tables A and B I would get array that would look like [A,B,A,B,...] which is not optimal for futher processing and B can be missing sometimes...

**Comment by juniwalk** [comment]
I see,
you could either select the entities into DTO object if you need them grouped somehow or stick with the way you've done it.

**Comment by jaroslavrehorka** [comment]
ok, I was pretty easy to create modified DataSource so I will keep using it.

Thank you for your help
