### ISSUE TITLE
DateTime picker in inline edit

### ISSUE THREAD

**Issue by maraerben** [ublaboo/datagrid#603]
Dobrý den. Především: úžasný DataGrid pro Nette, lepšího není, jen kvůli němu uvažuji začínat všechny další projekty s Nette a ne se Symfony (kde mi právě v nových verzích podobná datová tabulka chybí)

Mám otázku - neplánujete přidat do **inline úprav** řádků tabulky input, ktreý by nabídl **DatePicker**? Momentálně je uživatel odkázán na to, vyplňovat datum a čas čistě ručně, v čemž může lehce udělat chybu.

Děkuji

![datagrid-inline-edit](https://user-images.githubusercontent.com/17090177/34650623-5a0df2e0-f3c4-11e7-93fb-acf61c2f7295.jpg)

**Comment by paveljanda** [comment]
@maraerben Díky za pochvalu.

Přidání datepickeru do inline editace je jednoduché. Přidal jsem to na web dokumentace (https://ublaboo.org/datagrid). Úprava:

```php
$grid->addInlineEdit()
	->onControlAdd[] = function($container) {
		$container->addText('name', '');
		$container->addText('created', '')
			->setAttribute('data-provide', 'datepicker')
			->setAttribute('data-date-format', 'd. m. yyyy');
	};
```

**Comment by maraerben** [comment]
Děkuji, to je skoro přesně to, co jsem hledal, je ale možné podobně vyvolat i **datetimepicker**? Tedy ten, kde bych si mohl zvolit kromě datumu i čas.

**Comment by paveljanda** [comment]
@maraerben Tuším, že žádný datetimepicker teď datagrid ani nepoužívá. Zkuste si tedy vybrat svou datetimepicker knihovnu a tu použít. Mělo by opět stačit pouze přidání nějakého data-atributu, jak to mají tyto knihovny ve zvyku. Je to přeci pouze formulářový prvek. :)

**Comment by milsorm** [comment]
No já se teda snažím o totéž - tzn. použít datepicker uvnitř inline edit, ale zásadní problém je, že datepicker (alespoň poslední 1.9.0) se renderuje mimo tu konkrétní td buňku, takže vybrání data v něm zajistí provedení akce "ukončit editaci" ve small inline editoru dřív, než vůbec může datepicker nastavit nějakou hodnotu do toho textfieldu :-( Takže pak to editování vlastně vůbec nefunguje :-( Dělám něco zcela špatně? (picker se otevře, má správnou hodnotu aktuálního pole, ale nikdy nedojde k vyvolání ani nette success js, ani onEditableCallback v php.
