### ISSUE TITLE
Bump package.json to 5.5.4

### ISSUE THREAD

**Issue by radekdostal** [ublaboo/datagrid#606]
Hello @paveljanda,
can you please bump package.json to version 5.5.4? Package installed with bower is not same as package installed with npm. Thank you.

**Comment by paveljanda** [comment]
@radekdostal Done in `v5.5.5`. You can simply send a PR next time. :)

**Comment by radekdostal** [comment]
Thank you, but when I type: npm search ublaboo, the available version is still 5.4.2.

**Comment by paveljanda** [comment]
@radekdostal Well is there something else I have to do to release a new version instead of releasing new tag?

**Comment by radekdostal** [comment]
I don't know, I'm a newbie in npm. There is a problem with dependencies - bower.json has defined dependencies, but package.json not.

**Comment by radekdostal** [comment]
`npm search ublaboo-datagrid` still returns version 5.4.2. Isn't `npm publish --tag` a solution? I don't know...

**Comment by paveljanda** [comment]
Done
