### ISSUE TITLE
Mizení flash-messages po přesměrování na stránku, kde je DataGrid

### ISSUE THREAD

**Issue by maraerben** [ublaboo/datagrid#611]
Zdravím,
mám problém, který se mi nedaří již delší dobu vyřešit. Migrujeme v jednom našem projektu z [o5/Grido](https://github.com/o5/grido) na váš DataGrid.

V presenteru mám `handleXYZ()` metodu, ve které přidávám pomocí `$this→flashMessage(...)` upozornění. Po tomto řádku máme typicky nějaký redirect na stránku, kde se neachází váš DataGrid.

Po načtení se však `flashMessage` objeví na stránce jen na zlomek vteřiny, protože ihned poté dojde k akci `refreshState!` (viz. příloha), kterou vyvolá DataGrid a tím se `flashMessages` "smažou".

Jedná se o chybu, nebo děláme něco strašně špatně  na naší straně?

Děkuji.

<img width="849" alt="snimek obrazovky 2018-02-17 v 23 44 16" src="https://user-images.githubusercontent.com/17090177/36346320-c365df94-143c-11e8-9202-8fd4046a90d7.png">

**Comment by paveljanda** [comment]
Dobrý den,

předpokládám, že animujete/skrýváte flashmessages JavaScriptem, je to tak? V takové JS funkci máte pravděpodobně navěšený handler na xhr oncomplete, ke kterému dojde při refreshstate.

**Comment by maraerben** [comment]
Obávám se, že ne, v presenterech vytváříme flash messages pomocí `$this->flashMessage(...)` a v samotných Latte šablonách všechny šablony vypisujeme v bloku najak takto:
`...
{snippet flashMessages}
    <div n:foreach="$flashes as $flash" class="alert alert-{$flash->type} alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        {_$flash->message}
    </div>
{/snippet}
...`

**Comment by paveljanda** [comment]
@maraerben Můžete udělat ukázkový sandbox-like projekt, kde bude toto chování jednoduše ukázáno a nahrát např někam na github?

**Comment by maraerben** [comment]
Určitě, pokusím se v dohledné chvíli.
