### ISSUE TITLE
DataGrid: Implement rendering via subcomponents

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#63]
It would be great if we had the ability to do partial rendering, for example:
```
{control grid}
```
vs
```
<div class="panel panel-default">
    <div class="panel-body">
         {control grid:table}
    </div>
    <div class="panel-footer">
        {control grid:paginator}
        {control grid:perpage}
    </div>
</div>
```

**Comment by juniwalk** [comment]
To make it simpler, you could reuse this partial rendering in master template:
```
{control $control:table}
{control $control:paginator}
{control $control:perpage}
```

**Comment by paveljanda** [comment]
@juniwalk Do you know how to "ajaxibly" redraw partial tempaltes of a control? A got no success trying it. Nete always redraws only one of the partial templates.

**Comment by juniwalk** [comment]
Are you using snippets?

**Comment by paveljanda** [comment]
Yes, everywhere.

**Comment by juniwalk** [comment]
Give me some time, I will create some test code to try how it behaves and how to solve it.

**Comment by juniwalk** [comment]
I am starting to think that this is limitation of nette. I can get it only to redraw thole component, not selected parts. I will check with nette comunity and get back to you later.

**Comment by paveljanda** [comment]
Problem is, when Nette is redrawing a `UI\Renderable` (`UI\Control`), it call directly control->render(): `Nette\Bridges\ApplicationLatte\UIRuntime::50`.

There is just one instance of control, so control::render() will be called only once per request.

**Comment by juniwalk** [comment]
Dammit! How will we proceed? Shall I post it as issue to nette/application? I'd live to have such feature for one of my projects anyway.

**Comment by paveljanda** [comment]
Yes, plase.

I stucked on more projects becouse of this.

**Comment by juniwalk** [comment]
@paveljanda How do you feel about those snippetAreas? If we used them, we would need to add a lot of high level stuff into documentation so users will use it properly.

**Comment by paveljanda** [comment]
I think it this case another nested components are better idea..

**Comment by juniwalk** [comment]
You mean a datagrid in a component that would handle this and then this componen in presenter?

**Comment by paveljanda** [comment]
No. I mean that datagrid would have for exmaple these components:

```php
{control $control-table}
{control $control-paginator}
{control $control-perpage}
```

Is this notation correct? Would it work?

**Comment by juniwalk** [comment]
Oh, I have no idea to be honest, I will check it out in that demo code I've posted earlier. (Once I get to it I am trying to fix webloader right now)

**Comment by juniwalk** [comment]
You were right,
I implemented it using subcomponents and it works like a charm!

Best thing is that is is even easier than partial rendering as you can create simple `grid.latte` where you would put code below (without the grid prefix) and it would work without too much effort and for all grid instances too!

Check the [prototype](https://github.com/juniwalk/ubergrid).

```smarty
<div class="panel panel-default">

	<div class="panel-heading">
		<h3 class="panel-title">Übergrid</h3>
	</div>

	<div class="panel-body">
		Possible place for filter
	</div>

	{control grid-table}

	<div class="panel-footer clearfix">
		{control grid-paginator}
		{control grid-perPage}
	</div>

</div>
```
*This is from presenter template.*

**Comment by paveljanda** [comment]
Problem is, i wanted frontend developers to simply extend the template and edit it. Dividing the base template into tempaltes of subcomponent makes it much more difficult to modify.

One reason for starting new datagrid was that o5/grido is so much uncustomizable. It is really painful to make some bigger changes in the template.

**Comment by juniwalk** [comment]
Yes, it is real pain to modify o5/grido template.

Question is, how much do we need to customize it in the first place? I for one need only to get it into proper wrapper so it fits in the app, to do that I need to render paginator and perPage selector in different places.

Using custom renderer for cells is sufficient for the rest.

I think others should rise their voices on how to go on from here.

**Comment by juniwalk** [comment]
This is [template](https://almsaeedstudio.com/themes/AdminLTE/pages/tables/simple.html) I currently use this datagrid in.

**Comment by paveljanda** [comment]
Sometimes, you need to implement responsive administration. There is nothing more easy than using Ublaboo\DataGrid - you simply extend the base template and rewrite the `{block data}`. It can look even like this:

```php
{extends $original_template}

{block data}
	{snippet tbody}
		{foreach $rows as $row}
			{var $item = $row->getItem()}

			<div class="well">
				<h2>{$item->name}</h2>
			</div>
		{/foreach}
	{/snippet}
{/block}
```

Actually, it's really fun to write it like that.

To your second point: Simply extend the template and rewrite the `{block #pagination}`. :)

**Comment by paveljanda** [comment]
Change your template to that:

```php
{block pagination}
    {control paginator}
{/block}
```

**Comment by paveljanda** [comment]
Sorry:

```php
{block pagination}
	{snippet pagination}
		{control paginator}
	{/snippet}
{/block}
```

**Comment by juniwalk** [comment]
Alright, I will check it out! :)

**Comment by juniwalk** [comment]
By the way you dont have to use snippet around controls, just invalidate whole control `$this['paginator']->redrawControl();`.

**Comment by paveljanda** [comment]
It is there to keep the compatibility with same block in parent tempalte.

**Comment by juniwalk** [comment]
Ah, alright :)

**Comment by paveljanda** [comment]
As templating with Ublaboo\DataGrid is pretty straightforward, I want it to remain so. Sorry if you spent much time with this ticket.

**Comment by juniwalk** [comment]
No worries, I gained some experience that is priceless to me so this was worth it. :)
