### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by JanGalek** [ublaboo/datagrid#631]
Nette\Component-model v2.4.0 update has construct params deprecated:
https://github.com/nette/component-model/blob/v2.4.0/src/ComponentModel/Component.php#L35-L46

actual:
```php
$grid = new DataGrid($this, $name);
```

now:
```php
$grid = new DataGrid();
$this->addComponent($grid, $name);
```

**Comment by f3l1x** [comment]
@JanGalek Don't hesitate to send PR ;-) It's always welcomed.

**Comment by JanGalek** [comment]
@f3l1x I would like, but I don't see where documentation is located :) (ublaboo.org/datagrid/)
