### ISSUE TITLE
Wrong link in documentation

### ISSUE THREAD

**Issue by vastlik** [ublaboo/datagrid#65]
Wrong link in [documentation](http://ublaboo.paveljanda.com/datagrid/) in DataGrind, Filtering. 
It points to [http://ublaboo.paveljanda.com/datagrid/filer](http://ublaboo.paveljanda.com/datagrid/filer) instead of [http://ublaboo.paveljanda.com/datagrid/filter](http://ublaboo.paveljanda.com/datagrid/filter)

**Comment by paveljanda** [comment]
Thanks
