### ISSUE TITLE
Missing quotation marks

### ISSUE THREAD

**Issue by vastlik** [ublaboo/datagrid#68]
in [filter](http://ublaboo.paveljanda.com/datagrid/filter) Filter select, missing quotation marks above Off.

Maybe upload documentation to github, co everyone can make pull request like [https://github.com/nextras/orm/tree/master/doc](https://github.com/nextras/orm/tree/master/doc), and you don't have to do it manually everytime, when someone find typo.

**Comment by paveljanda** [comment]
Thanks.

Good idea, but i started writing the docu into html in my parent site (paveljanda.com). It's messy, a don't want to share that with entire world. :D

**Comment by vastlik** [comment]
Ah... i see, but it would save you lot of time that you could invest into datagrid development. :D

**Comment by paveljanda** [comment]
That is true indeed

**Comment by JakubKontra** [comment]
I got it. Assignee.
