### ISSUE TITLE
TreeView: Missing column names above the table

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#71]
There are no column names above tree-view table, is there reason for it? I tried to add them myself in the latte and it seems to be ok (If I don't count the #49 issue).

**Comment by juniwalk** [comment]
@paveljanda [this](https://gist.github.com/juniwalk/a8209639f3fd5df897e0) is the implementation I was talking about, shall I send pull request with it? Maybe do some modifications?

**Comment by paveljanda** [comment]
That would work.

But! I will change a bit css of tree view and add "weight" to each column. Something like bootstrap columns (Now item columns have inconsistent width). Wait till the evening please. :)

**Comment by juniwalk** [comment]
Sure thing, I need to do something to work anyway, I was constantly sending you issues and PRs and stopped working. :D

**Comment by juniwalk** [comment]
@paveljanda Are we ready for headers? :)

**Comment by paveljanda** [comment]
Working on that. :D
I want to add same width to same columns in each row...

**Comment by juniwalk** [comment]
Oh I see you're not done yet :D Alright, it is not that important. :)

**Comment by paveljanda** [comment]
A have to modify a bit these column headers, so i copied your code and updated it. Is it ok?

**Comment by juniwalk** [comment]
Of course :)
