### ISSUE TITLE
Reset filter request was canceled

### ISSUE THREAD

**Issue by jelen07** [ublaboo/datagrid#74]
Hi, in some cases when the **Reset filter** button has been clicked, the request is canceled by following request. When you click once again, the filter will be reset.

![Image of Yaktocat](http://g.recordit.co/xptnpl7JlN.gif)

**Canceled request:**
filter?filtersGrid-filter%5Bname%5D=asd&filtersGrid-filter%5Bstatus%5D=&filtersGrid-filter%5Binserted%5D=&filtersGrid-filter%5Binserted2%5D%5Bfrom%5D=&filtersGrid-filter%5Binserted2%5D%5Bto%5D=&filtersGrid-filter%5Bid2%5D%5Bfrom%5D=&filtersGrid-filter%5Bid2%5D%5Bto%5D=&filtersGrid-filter%5Bfrom_to%5D%5Bfrom%5D=&filtersGrid-filter%5Bfrom_to%5D%5Bto%5D=&do=filtersGrid-resetFilter

**Following request:**
filter?filter%5Bid2%5D%5Bfrom%5D=&filter%5Bid2%5D%5Bto%5D=&filter%5Bname%5D=asd&filter%5Binserted%5D=&filter%5Binserted2%5D%5Bfrom%5D=&filter%5Binserted2%5D%5Bto%5D=&filter%5Bstatus%5D=&do=filtersGrid-filter-submit&

**Comment by paveljanda** [comment]
This happens immediately after typing something in filter and than clicking Reset.

JQuery fires "change" event on filter input "blur". I will look at that.

**Comment by jelen07** [comment]
:+1: Thanks a lot.
