### ISSUE TITLE
Doctrine: Missing table alias of the column

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#76]
When I use filter, there is problem with missing table alias. [Here](https://github.com/o5/grido/blob/master/src/DataSources/Doctrine.php#L139) is example on how to fix this.

Example of current usage:
```php
$grid->addFilterText('email', 'client.user.email');
```
When I search the email input I get:
`[Syntax Error] line 0, col 52: Error: Expected '.' or '(', got 'email'`
_because it expected u.email_

**Comment by paveljanda** [comment]
When you filter, you use table aliases. When datagrid is rendering data, it uses "property accessor". So filter definition will look differently than definition of column:

```php
$this->entityManager->getRepository(Example::class)
$grid->setDataSource(
	$exampleRepository->createQueryBuilder('e')
		->addSelect('g')
		->leftJoin('e.grandma', 'g')
);

/**
 * Filter in dql
 */
$grid->addFilterText('name', 'Search', ['e.name', 'e.id', 'g.name']);

/**
 * Dump via property accessor
 */
$grid->addColumnText('grandma_name', Grandma', 'grandma.name');
```

**Comment by juniwalk** [comment]
Yes I do get this, it is just sugar-coat to use default table alias if there is none given. :)

**Comment by paveljanda** [comment]
Haaa, I was looking for that, will take a look at it.

Thx.

**Comment by juniwalk** [comment]
Great! :)
