### ISSUE TITLE
Notice  Undefined variable: data_source

### ISSUE THREAD

**Issue by Achse** [ublaboo/datagrid#77]
When I send into `DataGrid` datasource directly (Api annotation allows that) I got that notice -> exception.

**How to reproduce**:
```php
/**
	 * @return DataGrid
	 */
	public function createComponentGrid()
	{
		$grid = new DataGrid();
		$grid->addColumnNumber('id', 'Id')
			->setSortable()
			->setFormat(2);

		$queryBuilder = $this->queryBuilderProvider->getQueryBuilder();
		$grid->setDataSource(new DoctrineDataSource($queryBuilder, 'id'));

		return $grid;
	}
```

**Cause** (In: `DataGrid::setDataSource($source):` 
```php
# here in this case nothing happens actually after that if-else three

if ($source instanceof DataSource\IDataSource) {
			// $source is ready for interact
} else ...
...
...

# After if-else three $data_source remains undefined
$this->dataModel = new DataModel($data_source);
....

**Comment by Achse** [comment]
![error](https://cloud.githubusercontent.com/assets/383295/12948068/044a1efe-d000-11e5-911d-12ea36f9baac.png)

**Comment by paveljanda** [comment]
When you are using doctrine query builder, you should set a datasource like this:

`$grid->setDataSource($queryBuilder);`

Ublaboo\DataGrid\DataSource\DoctrineDataSource uses query builder directly.

There is a example how to set different data sources in documentation: http://ublaboo.paveljanda.com/datagrid/data-source#datasources. I will add a example for doctrine query builder.

**Comment by paveljanda** [comment]
But thanks, there is a bug of undefined property, i will fix that.

**Comment by Achse** [comment]
Thanks, you were faster :+1:  (https://github.com/ublaboo/datagrid/pull/78)
