### ISSUE TITLE
Doctrine: Item detail

### ISSUE THREAD

**Issue by chapcz** [ublaboo/datagrid#88]
Item detail for Doctrine source generate bad DQL (e.g.). 
SELECT u FROM App\User u WHERE id = 1
instead of
SELECT u FROM App\User u WHERE u.id = 1

**Comment by paveljanda** [comment]
Can you show me your datagrid component factory?

**Comment by chapcz** [comment]
```php
protected function createComponentTest(EntityManager $em) {
		$grid = new DataGrid;
		$grid->setDataSource($em->getRepository(User::class)->createQueryBuilder("u"));
		$grid->setItemsDetail(__DIR__ . '/custom/detail.latte'); 
        $grid->addColumnText("name", "Jméno");
		return $grid;
}
```

**Comment by paveljanda** [comment]
So far it works.

What do you have in that detail?

**Comment by paveljanda** [comment]
Try this:

$grid->setItemsDetail(__DIR__ . '/custom/detail.latte', 'er.id');

**Comment by paveljanda** [comment]
Thse aliases - i will implement some functionality to automatically detect them - at the weekend.

**Comment by chapcz** [comment]
Oh - I don't know, why I omitted this parameter :) It works .... but I am looking forward to autodetection. Thanks.  => close
