### ISSUE TITLE
Callback actions

### ISSUE THREAD

**Issue by chapcz** [ublaboo/datagrid#90]
Hi, I would appreciate possibility of action Events (similarly as o5/Grido). I am creating standalone components, where I would like to work with items from grid (prefiltered in datasource). Now I can only create handle methods in presenter but no inside component. Do you plan to implement something like this?

```php
$grid->addActionEvent('delete', 'Delete', function($id) {
    // delete row or do something else ... 
})->icon('trash')->confirm('Do you really want to delete row %s?', 'name');

$grid->addActionEvent('worker', 'DO something', $this->callback);
```

**Comment by paveljanda** [comment]
Yes I can add this.

But, did you know about group acitons and exports? As you mentioned, you would like to work with item**S** - prefiltered.
This DataGrid allows you to create exports to custom callbacks and these filters can be both filtered and not-fitlered.
Also group actions give you an ability to fire custom callback with selected data.

This ActionEvent would work only with one row, right?

**Comment by chapcz** [comment]
Yes I know about groups, but this one is for "one row" - as you mention ...  actions like delete, activate by button in actions column. And another feature TIP is to have a chance to hide any action by condition for each row ( e.g. actiovation button only for non active rows). Thanks

**Comment by paveljanda** [comment]
That functionality is already there. :) Take a look at http://ublaboo.paveljanda.com/datagrid/row at the demo code. Argh, i forgot to write the documentation for `DataGrid:: allowRowsAction ` and `DataGrid:: allowRowsGroupAction `.

**Comment by paveljanda** [comment]
Please checkout master branch and test if this behaviour is satisfying enough.

Docu: http://ublaboo.paveljanda.com/datagrid/action#action-callback

**Comment by chapcz** [comment]
Hi, nice. Only one thing - in my opinion should be better to define 
->addActionCallback('custom_callback', '', function($id){....});
But onClick event handler is satisfying too:
``` php 
	public function addActionCallback($key, $name, $callback = null)
	{
		$this->addActionCheck($key);
		$params = ['__id' => $this->primary_key];

		$action = $this->actions[$key] = new Column\ActionCallback($this, $key, $name, $params);
		if (!is_null($callback)){
			$action->onClick[] = $callback;
		}
		return $action;
	}
```
... but it depends on you.

**Comment by paveljanda** [comment]
Checkout master - now you can defined your callback both in third argument of `DataGrid::accActionCallback` and also using `::onClick` event
