### ISSUE TITLE
$grid->setDefaultSort()  - Creating default object from empty value

### ISSUE THREAD

**Issue by Daaarkling** [ublaboo/datagrid#92]
Hi,
first of all great datagrid. But i ran into problem with $grid->setDefaultSort(['created' => 'ASC']);, I'm using doctrine datasource. It's end up with warning "Creating default object from empty value" 
```php
public function saveSessionData($key, $value)
       {
            if ($this->remember_state) {
                $this->grid_session->{$key} = $value; // -> here
            }
        }
```

If i skip this error everything works fine including default sort.

Hope that problem is not on my side :dancer: 
Thanks

**Comment by paveljanda** [comment]
I will probably skip setting session value if the value is NULL.

Can you show me your filters please?

**Comment by Daaarkling** [comment]
there it is:
```php
$grid->setDefaultSort(['created' => 'ASC']);   // this is causing the problem, without it it's working just fine

$grid->addFilterText('title', 'Title', 'qb.title');
$grid->addFilterDate('created', 'Created', 'qb.created');
```

DataSource:
```php
$em->createQueryBuilder()->select('qb')->from(Article::class, 'qb')
```

**Comment by paveljanda** [comment]
Can u please cleaning your session and cache? I can not get this behaviour on my computer.

**Comment by Achse** [comment]
I got this problem too. Problem is here: You call `$this->grid_session->{$key} = $value;` **before** you initialize `$this->grid_session`c in `DataGrid::attached()`.

This can happen it you call `$grid = new DataGrid();` without `$parent` in constructor and therefore attach is called much more later.

**Comment by Achse** [comment]
Because giving parent in contructor is depreccated (AFAIK), this is a bug. I'll send pull request soon, because I need to fix this in our project.

**Comment by paveljanda** [comment]
It should be fixed in master. Thank you for reporting.
