### ISSUE TITLE
Action: Texts not being send to ITranslator

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#94]
Texts of the Action (name, title, confirm, etc.) should be send to ITranslator for translation before rendering.

**Comment by paveljanda** [comment]
Right.

**Comment by juniwalk** [comment]
@paveljanda Hey, could you also add option to set data-* attributes? I use [ladda buttons](http://lab.hakim.se/ladda/) and they require data attributes.

**Comment by paveljanda** [comment]
Great idea, I will add that.

**Comment by juniwalk** [comment]
Thanks! :)
