### ISSUE TITLE
Column: Switchable button (with state)

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#97]
Hey,
is it possible to make column with buttons as "switches"? Meaning each row will have its own state and the button would render accordingly. It should not be coupled to the action buttons.

**Example:**

Column | Action                      | On click
---------- | ------------------------ | ------------------------
Value 1 | Published (green)   | Unpublished (red)
Value 2 | Unpublished (red)   | Publishes (green)

It is something like this: http://grid.mesour.com/version2/column/status/

**The reason:**
Right now I do this using custom renderer and I do it quite often, it would be great to have some option to do this natively.

**Comment by paveljanda** [comment]
1, You know - it is project/client/developer specific, thought it's used very often.
2, It is not so hard to implement that in some base datagrid factory.

But i will think about it.

**Comment by juniwalk** [comment]
Thanks :)

**Comment by paveljanda** [comment]
It is in master for now. I have to put in in documentation before tagging.

**Comment by juniwalk** [comment]
So you decided to go for it? Great! Thanks.

**Comment by paveljanda** [comment]
It is tagged as v2.3 now. Is it suitable for your projects? Or do you need another behaviour?

**Comment by juniwalk** [comment]
I'll get back to you once I get time to check it out, busy right now. :/

**Comment by juniwalk** [comment]
Hey, I've quickly checked the docs and the status column looks great!
